import { AppLanguage } from '../types/models';

/**
 * Exercise names are stored, matched and filtered as their English text — the
 * library ships from a public English database and the program catalogs name
 * their lifts the same way. So the English name stays the id and only the
 * label moves, exactly like equipment items and caution refinements.
 *
 * The map covers every exercise the program catalogs actually prescribe plus
 * the common library lifts a user meets while browsing. Anything else passes
 * through in English rather than guessing at a translation, which keeps a
 * missing entry honest instead of wrong.
 */
const EXERCISE_NAME_FI: Record<string, string> = {
  // ── Squat pattern ────────────────────────────────────────────────────
  'Back Squat': 'Takakyykky',
  'Barbell Squat': 'Takakyykky',
  // One name on purpose: the app's lift identity holds the two rows as one
  // lift (liftIdentity's squat group, the alias table filing "Back Squat" on
  // the full squat; tests/lib/liftHistoryIdentity.test.cjs), so a
  // one-row-per-name list showing one of them is right, and the library
  // keeps both (picker audit, 2026-10-06).
  'Barbell Full Squat': 'Takakyykky',
  'Front Squat': 'Etukyykky',
  'Hack Squat': 'Hack squat',
  'Box Squat': 'Laatikkokyykky',
  'Chair Squat': 'Tuolikyykky',
  'Bodyweight Squat': 'Kehonpainokyykky',
  'Goblet Squat': 'Goblet-kyykky',
  'Bulgarian Split Squat': 'Bulgarialainen askelkyykky',
  'Barbell Side Split Squat': 'Sivuaskelkyykky tangolla',
  'Sumo Squat': 'Sumokyykky',
  'Leg Press': 'Jalkaprässi',
  'Wall Sit': 'Seinäistunta',

  // ── Hinge pattern ────────────────────────────────────────────────────
  Deadlift: 'Maastaveto',
  'Barbell Deadlift': 'Maastaveto',
  'Romanian Deadlift': 'Romanialainen maastaveto',
  'Trap Bar Deadlift': 'Trap bar -maastaveto',
  'Sumo Deadlift': 'Sumomaastaveto',
  'Stiff-Legged Deadlift': 'Suorin jaloin maastaveto',
  'Good Morning': 'Aamunavaus',
  'Hip Thrust': 'Lantionnosto',
  'Barbell Hip Thrust': 'Lantionnosto tangolla',
  'Machine Hip Thrust': 'Lantionnosto laitteessa',
  'Bodyweight Calf Raise': 'Pohjenosto ilman painoa',
  'Glute Bridge': 'Lantionnosto lattialla',
  'Kettlebell Swing': 'Kahvakuulaheilautus',
  'Band Curl': 'Hauiskääntö kuminauhalla',
  'One-Arm Kettlebell Swings': 'Yhden käden kahvakuulaheilautus',
  'Cable Kickback': 'Taljapotku',

  // ── Lunges and single leg ────────────────────────────────────────────
  Lunge: 'Askelkyykky',
  'Walking Lunge': 'Kävelevä askelkyykky',
  'Bodyweight Walking Lunge': 'Kävelevä askelkyykky kehonpainolla',
  'Reverse Lunge': 'Taakse astuva askelkyykky',
  'Step-Up': 'Askelnousu',
  'Step-up with Knee Raise': 'Askelnousu polvennostolla',

  // ── Horizontal press ─────────────────────────────────────────────────
  'Bench Press': 'Penkkipunnerrus',
  'Barbell Bench Press - Medium Grip': 'Penkkipunnerrus',
  'Dumbbell Bench Press': 'Penkkipunnerrus käsipainoilla',
  'Incline Bench Press': 'Vinopenkkipunnerrus',
  'Barbell Incline Bench Press - Medium Grip': 'Vinopenkkipunnerrus',
  'Incline Dumbbell Press': 'Vinopenkkipunnerrus käsipainoilla',
  'Decline Bench Press': 'Laskeva penkkipunnerrus',
  'Close-Grip Bench Press': 'Kapea penkkipunnerrus',
  'Machine Chest Press': 'Rintaprässi',
  'Push-Up': 'Punnerrus',
  Pushups: 'Punnerrus',
  'Push-Up Wide': 'Leveä punnerrus',
  'Incline Push-Up': 'Vinopunnerrus',
  'Decline Push-Up': 'Laskeva punnerrus',
  Dips: 'Dipit',
  'Chest Dip': 'Rintadippi',

  // ── Vertical press ───────────────────────────────────────────────────
  'Overhead Press': 'Pystypunnerrus',
  'Standing Military Press': 'Pystypunnerrus',
  'Dumbbell Shoulder Press': 'Pystypunnerrus käsipainoilla',
  'Arnold Press': 'Arnold-punnerrus',
  'Push Press': 'Työntöpunnerrus',
  'Handstand Push-Ups': 'Käsilläseisontapunnerrus',

  // ── Chest isolation ──────────────────────────────────────────────────
  'Cable Fly': 'Taljaristikkäisveto',
  'Dumbbell Fly': 'Vipunosto rinnalle',
  // The pools spell it plural; the lookup is exact, so both spellings need an entry.
  'Dumbbell Flyes': 'Vipunosto rinnalle',
  'Pec Deck': 'Pec deck',

  // ── Vertical pull ────────────────────────────────────────────────────
  'Pull-Up': 'Leuanveto',
  Pullups: 'Leuanveto',
  // A chin-up is the supinated pull-up, and this app's word for that grip is
  // `alaote` (Ylätalja alaotteella). It read "Myötäotteinen" — the overhand
  // grip, i.e. the plain Leuanveto above it (user, 2026-09-27).
  'Chin-Up': 'Leuanveto alaotteella',
  Chinups: 'Leuanveto alaotteella',
  'Scapular Pull-Up': 'Lapaleuanveto',
  'Lat Pulldown': 'Ylätalja',
  // Plain, like its English label 'Lat Pulldown': this is THE lat pulldown
  // ("haluisin vain ylätalja", #bugs 2026-08-28), not one of its variants.
  'Wide-Grip Lat Pulldown': 'Ylätalja',
  'Close-Grip Front Lat Pulldown': 'Kapea ylätalja',

  // ── Horizontal pull ──────────────────────────────────────────────────
  'Barbell Row': 'Tankosoutu',
  'Bent Over Barbell Row': 'Tankosoutu',
  'Dumbbell Row': 'Käsipainosoutu',
  'One-Arm Dumbbell Row': 'Yhden käden käsipainosoutu',
  'Seated Cable Row': 'Istuen taljasoutu',
  'Chest-Supported Row': 'Rintatuettu soutu',
  'T-Bar Row': 'T-tankosoutu',
  'Inverted Row': 'Kehonpainosoutu',
  'Face Pull': 'Kasvoilleveto',
  Shrug: 'Kohautus',
  'Barbell Shrug': 'Kohautus tangolla',

  // ── Shoulders ────────────────────────────────────────────────────────
  'Lateral Raise': 'Sivunosto',
  'Side Lateral Raise': 'Sivunosto',
  'Front Raise': 'Etunosto',
  'Rear Delt Fly': 'Takaolkapään vipunosto',
  'Reverse Machine Flyes': 'Takaolkapään laitevipunosto',
  'Band Pull Apart': 'Kuminauhan levitys',
  'Upright Row': 'Pystysoutu',

  // ── Biceps ───────────────────────────────────────────────────────────
  'Barbell Curl': 'Hauiskääntö tangolla',
  'Dumbbell Curl': 'Hauiskääntö käsipainoilla',
  'Dumbbell Bicep Curl': 'Hauiskääntö käsipainoilla',
  'Hammer Curl': 'Vasarakääntö',
  'Preacher Curl': 'Saarnaajakääntö',
  'Cable Curl': 'Taljakääntö',
  'Concentration Curls': 'Keskittymiskääntö',

  // ── Triceps ──────────────────────────────────────────────────────────
  'Triceps Pushdown': 'Ojentajapushdown',
  'Triceps Pushdown - Rope Attachment': 'Ojentajapushdown köydellä',
  'Overhead Triceps Extension': 'Ojentajapunnerrus pään yli',
  'Skull Crusher': 'Ranskalainen punnerrus',
  'Lying Triceps Press': 'Ranskalainen punnerrus',
  'Bench Dip': 'Penkkidippi',
  'Bench Dips': 'Penkkidippi',

  // ── Legs isolation ───────────────────────────────────────────────────
  'Leg Curl': 'Takareisikoukistus',
  'Seated Leg Curl': 'Istuen takareisikoukistus',
  'Lying Leg Curl': 'Maaten takareisikoukistus',
  'Leg Extension': 'Reiden ojennus',
  'Calf Raise': 'Pohjenosto',
  'Standing Calf Raise': 'Seisten pohjenosto',
  'Seated Calf Raise': 'Istuen pohjenosto',
  'Calf Press': 'Pohjeprässi',

  // ── Core ─────────────────────────────────────────────────────────────
  Plank: 'Lankku',
  'Side Plank': 'Kylkilankku',
  'Cable Crunch': 'Taljavatsarutistus',
  Crunches: 'Vatsarutistus',
  'Hanging Knee Raise': 'Roikkuen polvennosto',
  'Hanging Leg Raise': 'Roikkuen jalannosto',
  'Russian Twist': 'Venäläinen kierto',
  'Ab Wheel': 'Vatsarulla',
  'Mountain Climbers': 'Vuorikiipeilijä',
  'Mountain Climber': 'Vuorikiipeilijä',
  'Bicycle Crunch': 'Polkupyörärutistus',
  'Farmer Carry': 'Maanviljelijän kävely',

  // ── Conditioning and flows (catalog-only names) ──────────────────────
  Burpee: 'Burpee',
  'Treadmill HIIT (30s on / 30s off)': 'Juoksumatto-HIIT (30 s / 30 s)',
  'Bike HIIT (45s sprint / 15s rest)': 'Pyörä-HIIT (45 s veto / 15 s lepo)',
  // The app's own rows these two prescriptions open (extraExerciseLibrary).
  'Treadmill HIIT': 'Juoksumatto-HIIT',
  'Bike HIIT': 'Pyörä-HIIT',
  'Easy Run Blocks': 'Kevyet juoksublokit',
  'Tempo Run Blocks': 'Tempojuoksublokit',
  'Stride Finishers': 'Askelkiihdytykset',
  'Rowing, Stationary': 'Soutulaite',
  'Bicycling, Stationary': 'Kuntopyörä',
  'Jump Rope': 'Hyppynaru',
  'Mobility Flow': 'Liikkuvuussarja',
  'Hip Mobility Flow': 'Lonkan liikkuvuussarja',
  'Recovery Stretch Flow': 'Palauttava venyttelysarja',
  'Sun Salutation Flow': 'Aurinkotervehdys',
  'Yoga Balance Flow': 'Joogan tasapainosarja',
  'Breath Reset': 'Hengityspalautus',
  'Dead Hang': 'Roikunta tangossa',

  // ═══ Reachable through the swap sheet and the plan composer ═════════
  // Everything above is what the ready programs prescribe. Everything
  // below is what a user can swap TO, or what the composer can add — the
  // substitution groups and the focus/supplemental pools. Those lists are
  // four times the size of the catalog, and until now they arrived in
  // English the moment anyone opened "Vaihda liike".

  // ── Squat and single leg ─────────────────────────────────────────────
  Squat: 'Kyykky',
  'Competition Back Squat': 'Kilpakyykky',
  'Pause Squat': 'Pysäytyskyykky',
  'Jump Squat': 'Hyppykyykky',
  'Squat Jump (20s on / 10s off)': 'Hyppykyykky (20 s / 10 s)',
  'Goblet Squat (Light)': 'Goblet-kyykky kevyellä',
  'Sit-to-Stand (Chair Squat)': 'Ylösnousu tuolilta',
  'Cossack Squat': 'Kasakkakyykky',
  'Deep Squat Hold': 'Syvä kyykkypito',
  'Supported Deep Squat Hold': 'Tuettu syvä kyykkypito',
  'Shrimp Squat': 'Shrimp-kyykky',
  'Sissy Squat': 'Sissy-kyykky',
  'Pistol Squat (each leg)': 'Pistoolikyykky (kumpikin jalka)',
  'Bulgarian Split Squat (Jumping)': 'Bulgarialainen askelkyykky hypyllä',
  'Step-Up (High Box)': 'Askelnousu korkealle',
  'Step-Up (Low Box)': 'Askelnousu matalalle',
  'Bodyweight Reverse Lunge': 'Taakse astuva askelkyykky kehonpainolla',
  'Curtsy Lunge': 'Ristiaskelkyykky',
  'Lateral Lunge': 'Sivuaskelkyykky',
  'Dumbbell Lunges': 'Askelkyykky käsipainoilla',

  // ── Hinge, glutes and hamstrings ─────────────────────────────────────
  'Conventional Deadlift': 'Perinteinen maastaveto',
  'Competition Deadlift': 'Kilpamaastaveto',
  'Deficit Deadlift': 'Maastaveto korokkeelta',
  'Single-Leg RDL': 'Yhden jalan romanialainen maastaveto',
  'Single-Leg Romanian Deadlift': 'Yhden jalan romanialainen maastaveto',
  'Romanian Deadlift (Light)': 'Romanialainen maastaveto kevyellä',
  'Glute Ham Raise': 'Takareisinosto',
  'Floor Glute-Ham Raise': 'Takareisinosto lattialla',
  'Nordic Hamstring Curl (Assisted)': 'Nordic-takareisikoukistus (avustettu)',
  'Hamstring Walkout': 'Takareisikävely',
  'Reverse Hyperextension': 'Käänteinen selänojennus',
  'Band Good Morning': 'Aamunavaus kuminauhalla',
  'Cable Pull-Through': 'Taljaveto jalkojen välistä',
  'Hip Thrust (Bodyweight)': 'Lantionnosto kehonpainolla',
  'Hip Thrust (Bodyweight or Light Bar)': 'Lantionnosto kehonpainolla tai kevyellä tangolla',
  'Single-Leg Hip Thrust': 'Yhden jalan lantionnosto',
  'Banded Hip Thrust': 'Lantionnosto kuminauhalla',
  'Glute Bridge (Banded)': 'Lantionnosto lattialla kuminauhalla',
  'Banded Glute Bridge': 'Lantionnosto lattialla kuminauhalla',
  'Single-Leg Glute Bridge': 'Yhden jalan lantionnosto lattialla',
  'Glute Bridge Hold': 'Lantionnostopito',
  'Glute Bridge March': 'Lantionnosto marssilla',
  'Butt Lift (Bridge)': 'Lantionnosto lattialla',
  'Frog Pump': 'Sammakkolantionnosto',
  'Frog Pump (Banded)': 'Sammakkolantionnosto kuminauhalla',
  'Glute Kickback': 'Pakarapotku',
  'Cable Glute Kickback': 'Pakarapotku taljassa',
  'One-Legged Cable Kickback': 'Yhden jalan taljapotku',
  'Banded Fire Hydrant': 'Palopostiliike kuminauhalla',
  'Standing Hip Abduction': 'Seisten lonkan loitonnus',
  'Cable Abductor': 'Lonkan loitonnus taljassa',
  'Side-Lying Leg Raise': 'Kylkimakuulla jalannosto',
  'Banded Lateral Walk': 'Sivuaskellus kuminauhalla',

  // ── Press ────────────────────────────────────────────────────────────
  'Barbell Bench Press': 'Penkkipunnerrus',
  'Competition Bench Press': 'Kilpapenkkipunnerrus',
  'Paused Bench Press': 'Pysäytyspenkkipunnerrus',
  'Incline Barbell Press': 'Vinopenkkipunnerrus tangolla',
  'Dumbbell Floor Press': 'Lattiapunnerrus käsipainoilla',
  'Machine Shoulder Press': 'Olkaprässi',
  'Seated Dumbbell Press': 'Istuen käsipainopunnerrus',
  'Standing Dumbbell Shoulder Press': 'Seisten käsipainopunnerrus',
  'Standing Overhead Press': 'Seisten pystypunnerrus',
  'Arnold Dumbbell Press': 'Arnold-punnerrus',
  'Dumbbell Thruster': 'Thruster käsipainoilla',
  'Push Up to Side Plank': 'Punnerrus kylkilankkuun',
  'Diamond Push-Up': 'Timanttipunnerrus',
  'Pike Push-Up': 'Pike-punnerrus',
  'Pike Push-Up (Elevated)': 'Pike-punnerrus korokkeelta',
  'Wall Push-Up': 'Seinäpunnerrus',
  'Push-Up (or Knee Push-Up)': 'Punnerrus (tai polvipunnerrus)',
  'Push-Up (20s on / 10s off)': 'Punnerrus (20 s / 10 s)',
  // A pseudo planche is a push-up leaning towards one, not the planche itself.
  'Pseudo Planche Push-Up': 'Pseudo planche -punnerrus',
  'Plank-Up': 'Lankkunousu',
  'Body-Up': 'Lankkunousu',
  'Weighted Dips': 'Lisäpainodipit',
  'Triceps Dip (Chair)': 'Penkkidippi tuolilla',

  // ── Pull ─────────────────────────────────────────────────────────────
  'Weighted Pull-Up': 'Lisäpainoleuanveto',
  'Assisted Pull-Up': 'Avustettu leuanveto',
  'Explosive Pull-Up': 'Räjähtävä leuanveto',
  'Muscle-Up Progression (Negative)': 'Muscle up -harjoite (negatiivinen)',
  'Toes-to-Bar': 'Varpaat tankoon',
  'Rows (Bar or Rings)': 'Kehonpainosoutu (tanko tai renkaat)',
  'Inverted Row (Table)': 'Kehonpainosoutu pöydän alla',
  // Not the same starting position as 'Inverted Row' above: the legs hook
  // over the bar itself rather than staying grounded, so both shared
  // 'Kehonpainosoutu' until the sweep in the recheck round 2026-09-29.
  'Bodyweight Mid Row': 'Kehonpainosoutu jalat tangon päällä',
  'Bent-Over Row': 'Tankosoutu',
  'Bent Over Two-Dumbbell Row': 'Käsipainosoutu kumarrettuna',
  'Single-Arm Dumbbell Row': 'Yhden käden käsipainosoutu',
  'Dumbbell Renegade Row': 'Renegade-soutu käsipainoilla',
  'Renegade Row': 'Renegade-soutu',
  'Pendlay Row': 'Pendlay-soutu',
  'Seated Machine Row': 'Istuen laitesoutu',
  'Machine High Row': 'Laitesoutu ylhäältä',
  'Cable Row': 'Taljasoutu',
  'Seated Cable Row (Wide)': 'Istuen leveä taljasoutu',
  'Standing Band Row': 'Seisten kuminauhasoutu',
  'Chest-Supported T-Bar Row': 'Rintatuettu T-tankosoutu',
  'Cable Pullover': 'Taljapullover',
  // Keeps its own name. This is the catalog's wide-grip entry and it shares
  // the vertical_pull substitution group with the catalog's plain
  // 'Lat Pulldown' (= "Ylätalja"). Giving both the same Finnish label made
  // the swap sheet offer an apparent no-op, and hid the library's
  // 'Wide-Grip Lat Pulldown' row, which the player filters by label.
  'Lat Pulldown (Wide Grip)': 'Leveä ylätalja',

  // ── Chest isolation ──────────────────────────────────────────────────
  'Cable Crossover': 'Taljaristikkäisveto',
  'Reverse Pec Deck': 'Käänteinen pec deck',
  'Doorway Pec Stretch': 'Rintalihasvenytys ovensuussa',
  'Inchworm to Push-Up': 'Toukkakävely punnerrukseen',

  // ── Shoulders ────────────────────────────────────────────────────────
  'Dumbbell Lateral Raise': 'Sivunosto käsipainoilla',
  'Cable Lateral Raise': 'Sivunosto taljassa',
  'Cable Front Raise': 'Etunosto taljassa',
  'Lateral Raise Superset': 'Sivunostosupersarja',
  'Dumbbell Rear Delt Fly': 'Takaolkapään vipunosto käsipainoilla',
  'Cable Rear Delt Fly': 'Takaolkapään vipunosto taljassa',
  'Band Pull-Apart': 'Kuminauhan levitys',
  'Arm Circles': 'Käsien pyöritykset',
  'Shoulder Dislocations (PVC)': 'Olkapään kierrot kepillä',
  'Wall Slide': 'Seinäliuku',
  'Thread the Needle': 'Neulansilmä',
  'Sphinx Pose': 'Sfinksiasento',

  // ── Arms ─────────────────────────────────────────────────────────────
  'Bicep Curl': 'Hauiskääntö',
  'EZ-Bar Curl': 'Hauiskääntö EZ-tangolla',
  'Cable Bicep Curl': 'Hauiskääntö taljassa',
  'Cable Hammer Curl': 'Vasarakääntö taljassa',
  'Alternate Hammer Curl': 'Vuorotteleva vasarakääntö',
  'Incline Dumbbell Curl': 'Vinopenkkihauiskääntö',
  'Cable Triceps Extension': 'Ojentajaojennus taljassa',
  'Cable Triceps Kickback': 'Ojentajapotku taljassa',
  'Triceps Kickback': 'Ojentajapotku',
  'Cable Triceps Pushdown': 'Ojentajapushdown taljassa',
  'Rope Pushdown': 'Ojentajapushdown köydellä',
  'Wrist Curl': 'Ranteen koukistus',
  'Reverse Wrist Curl': 'Ranteen ojennus',

  // ── Calves ───────────────────────────────────────────────────────────
  'Single-Leg Calf Raise': 'Yhden jalan pohjenosto',
  'Donkey Calf Raises': 'Aasipohjenosto',
  'Calf Raises - With Bands': 'Pohjenosto kuminauhalla',

  // ── Core ─────────────────────────────────────────────────────────────
  // Loan words keep their shape and take Finnish capitalisation, the way
  // "Hack squat" and "Pec deck" already do above.
  'Dead Bug': 'Dead bug',
  'Dead Bug (Modified)': 'Dead bug (helpotettu)',
  'Bird Dog': 'Bird dog',
  'Hollow Body Hold': 'Hollow-pito',
  'Dragon Flag': 'Dragon flag',
  'Front Lever Tuck Hold': 'Front lever -kippupito',
  'Tuck Planche Hold': 'Planche-kippupito',
  'L-Sit Hold': 'L-istunta',
  'V-Up': 'V-nosto',
  'Plank Jack': 'Lankkuhyppy',
  'Plank Shoulder Tap': 'Lankku olkakosketuksella',
  'Plank to Pike': 'Lankusta pikeen',
  'Side Plank (Knees Down)': 'Kylkilankku polvilta',
  'Transverse Abdominis Activation': 'Poikittaisen vatsalihaksen aktivointi',
  'Pelvic Floor Activation (Kegel)': 'Lantionpohjan aktivointi (Kegel)',
  'Vacuum (Stomach)': 'Vatsan vakuumi',
  'Standing Side Bend': 'Seisten kylkitaivutus',
  'Heel Slide': 'Kantapään liuku',
  'Standing Marching': 'Seisten marssi',
  'Medicine Ball Slam': 'Kuntopallon iskeminen',
  'Handstand Wall Walk': 'Käsilläseisonta seinää pitkin',
  'Wall Handstand Hold': 'Käsilläseisontapito seinää vasten',

  // ── Conditioning, jumps and sprints ──────────────────────────────────
  'High Knees': 'Polvennostojuoksu',
  'Jumping Jack': 'Haaraperushyppy',
  'Pogo Hops': 'Pogo-hypyt',
  'Box Jump': 'Laatikkohyppy',
  'Broad Jump': 'Pituushyppy paikaltaan',
  'Skater Jump': 'Luisteluhyppy',
  'Lateral Bound': 'Sivuloikka',
  'Sprint 40m': 'Sprintti 40 m',
  'Sprint Interval (200m)': 'Sprinttiveto (200 m)',
  Sprint: 'Sprintti',
  'Cone Drill (Pro Agility)': 'Kartioharjoite (ketteryys)',
  'Ladder Drill': 'Tikasharjoite',
  'Heel-to-Toe Walk': 'Kantapää-varvas-kävely',
  'Battle Rope Slam': 'Battle rope -isku',
  'Battle Rope Wave': 'Battle rope -aalto',
  'Battling Ropes': 'Battle rope',
  'Sled Push': 'Kelkan työntö',
  "Farmer's Walk": 'Maanviljelijän kävely',
  // "Voima-", as Power Snatch and Power Clean from Blocks: "Rinnalleveto" is
  // the clean caught in a full squat, and both are in the library.
  'Power Clean': 'Voimarinnalleveto',
  'Air Bike (30s sprint)': 'Air bike (30 s veto)',
  'Stationary Bike (Easy Pace)': 'Kuntopyörä (kevyt vauhti)',
  'Recumbent Bike': 'Kuntopyörä selkänojalla',
  'Elliptical Trainer': 'Crosstrainer',
  'Jogging, Treadmill': 'Hölkkä juoksumatolla',
  'Trail Running/Walking': 'Polkujuoksu tai -kävely',
  'Rowing Machine (500m intervals)': 'Soutulaite (500 m vedot)',
  'Rowing Machine HIIT': 'Soutulaite-HIIT',
  'Stairmaster (Moderate)': 'Porraskone (kohtalainen)',
  'Burpee (20s on / 10s off)': 'Burpee (20 s / 10 s)',
  'Burpee with Push-Up': 'Burpee punnerruksella',
  'Mountain Climber (20s on / 10s off)': 'Vuorikiipeilijä (20 s / 10 s)',

  // ── Mobility, stretches and breathing ────────────────────────────────
  'Cat-Cow': 'Kissa-lehmä',
  'Cat Stretch': 'Kissavenytys',
  'Cobra Pose': 'Kobra-asento',
  'Cobra to Down Dog Flow': 'Kobrasta alaspäin katsovaan koiraan',
  "Child's Pose with Reach": 'Lapsen asento kurotuksella',
  'Pigeon Pose': 'Kyyhkynen',
  'Pigeon Pose (each side)': 'Kyyhkynen (kumpikin puoli)',
  'Butterfly Stretch': 'Perhosvenytys',
  'Frog Stretch': 'Sammakkovenytys',
  '90/90 Hip Stretch': '90/90-lonkkavenytys',
  'Seated Hip Stretch': 'Istuen lonkkavenytys',
  'Hip Flexor Stretch': 'Lonkankoukistajan venytys',
  'Couch Stretch (each side)': 'Lonkankoukistajan venytys (kumpikin puoli)',
  'Seated Pancake Stretch': 'Istuen haara-aukivenytys',
  'Seated Spinal Twist': 'Istuen selkärangan kierto',
  'Spinal Twist (Supine)': 'Selkärangan kierto selinmakuulla',
  'Sleeper Stretch': 'Sleeper-venytys',
  'Lying Quad Stretch': 'Etureiden venytys maaten',
  'All Fours Quad Stretch': 'Etureiden venytys konttausasennossa',
  'Standing Forward Fold': 'Seisten eteentaivutus',
  'Chin To Chest Stretch': 'Niskan venytys leuka rintaan',
  'Ankle Circles': 'Nilkan pyöritykset',
  'Ankle Mobility Drill': 'Nilkan liikkuvuusharjoite',
  'Hip Circles': 'Lonkan pyöritykset',
  'Thoracic Extension on Roller': 'Rintarangan ojennus rullalla',
  'Legs Up the Wall': 'Jalat seinää vasten',
  "World's Greatest Stretch": 'Maailman paras venytys',
  'Single-Leg Balance Hold': 'Yhden jalan tasapainopito',
  'Single-Leg Balance Reach': 'Yhden jalan tasapainokurotus',
  'Supported Single-Leg Balance': 'Tuettu yhden jalan tasapaino',
  'Box Breathing': 'Laatikkohengitys',
  'Diaphragmatic Breathing': 'Palleahengitys',
  // No catalog prescribes these six any more — they were the xlsx import's
  // inert warmup/cooldown rows and were removed from the programs. They stay
  // translated because they are still in users' data: anyone who ran a gainer
  // session before the removal has them in their logged history, and a
  // dead-code sweep that deletes these turns that history back into English.
  'Breathing Reset': 'Hengityspalautus',
  'Cooldown Flow': 'Palautumissarja',
  'Recovery Stretch': 'Palauttava venytys',
  'Dynamic Warm-Up': 'Dynaaminen lämmittely',
  'Mobility Warm-Up': 'Liikkuvuuslämmittely',
  'Joint Prep Flow': 'Nivelten herättely',

  // ═══ The rest of the library ════════════════════════════════════════
  // Everything above is what the catalogs prescribe and what the swap
  // sheet and composer can reach. This block is the remaining 771 names
  // in the browsable library — the ones a user meets in Liikekirjasto and
  // when building their own program, which arrived in English for every
  // Finnish reader.
  //
  // Sorted by their English name so a missing entry is findable. Loanwords
  // that Finnish gyms use as-is (muscle up, rack pull, thruster) are
  // lower-cased rather than invented around, matching the "Pec deck" and
  // "Hack squat" entries above.
  '3/4 Sit-Up': '3/4 istumaannousu',
  '90/90 Hamstring': '90/90 takareiden venytys',
  'Ab Crunch Machine': 'Vatsarutistuslaite',
  'Ab Roller': 'Vatsarulla',
  Adductor: 'Lähentäjän venytys',
  'Adductor/Groin': 'Lähentäjän ja nivusen venytys',
  'Advanced Kettlebell Windmill': 'Edistynyt kahvakuulan tuulimylly',
  'Air Bike': 'Polkupyörärutistus',
  'Alternate Heel Touchers': 'Vuorottainen kantapään kosketus',
  'Alternate Incline Dumbbell Curl': 'Vuorottainen hauiskääntö vinopenkillä käsipainoilla',
  'Alternate Leg Diagonal Bound': 'Vuorottainen vinoloikka',
  'Alternating Cable Shoulder Press': 'Vuorottainen pystypunnerrus taljassa',
  'Alternating Deltoid Raise': 'Vuorottainen olkapäännosto',
  'Alternating Floor Press': 'Vuorottainen lattiapunnerrus',
  'Alternating Hang Clean': 'Vuorottainen rinnalleveto riipunnasta',
  'Alternating Kettlebell Press': 'Vuorottainen punnerrus kahvakuulilla',
  'Alternating Kettlebell Row': 'Vuorottainen soutu kahvakuulilla',
  'Alternating Renegade Row': 'Vuorottainen renegade-soutu',
  'Ankle On The Knee': 'Nilkka polvella -venytys',
  'Anterior Tibialis-SMR': 'Etummaisen säärilihaksen rullaus',
  'Anti-Gravity Press': 'Anti-gravity-punnerrus',
  'Around The Worlds': 'Ympyränosto käsipainoilla',
  'Atlas Stone Trainer': 'Atlas-kiven harjoitusvedin',
  'Atlas Stones': 'Atlas-kivet',
  'Axle Deadlift': 'Maastaveto paksulla tangolla',
  'Back Flyes - With Bands': 'Takaolkapään vipunosto kuminauhoilla',
  'Backward Drag': 'Taaksepäin veto reellä',
  'Backward Medicine Ball Throw': 'Kuntopallon heitto taaksepäin',
  'Balance Board': 'Tasapainolauta',
  'Ball Leg Curl': 'Takareisikoukistus jumppapallolla',
  'Band Assisted Pull-Up': 'Avustettu leuanveto kuminauhalla',
  'Band Good Morning (Pull Through)': 'Aamunavaus kuminauhalla (veto jalkojen välistä)',
  'Band Hip Adductions': 'Lonkan lähennys kuminauhalla',
  'Band Skull Crusher': 'Ranskalainen punnerrus kuminauhalla',
  'Barbell Ab Rollout': 'Vatsarullaus tangolla',
  'Barbell Ab Rollout - On Knees': 'Vatsarullaus tangolla polvillaan',
  'Barbell Curls Lying Against An Incline': 'Hauiskääntö tangolla vinopenkkiin nojaten',
  'Barbell Glute Bridge': 'Lantionnosto lattialla tangolla',
  'Barbell Guillotine Bench Press': 'Giljotiinipenkkipunnerrus',
  'Barbell Hack Squat': 'Hack squat tangolla',
  'Barbell Incline Shoulder Raise': 'Olkapäännosto vinopenkillä tangolla',
  'Barbell Lunge': 'Askelkyykky tangolla',
  'Barbell Rear Delt Row': 'Takaolkapään soutu tangolla',
  'Barbell Rollout from Bench': 'Vatsarullaus tangolla penkiltä',
  'Barbell Seated Calf Raise': 'Istuen pohjenosto tangolla',
  'Barbell Shoulder Press': 'Pystypunnerrus tangolla',
  'Barbell Shrug Behind The Back': 'Kohautus tangolla takaa',
  'Barbell Side Bend': 'Kylkitaivutus tangolla',
  'Barbell Squat To A Bench': 'Kyykky penkille tangolla',
  'Barbell Step Ups': 'Askelnousu tangolla',
  'Barbell Walking Lunge': 'Kävelevä askelkyykky tangolla',
  'Bear Crawl Sled Drags': 'Karhukävely reen kanssa',
  'Behind Head Chest Stretch': 'Rinnan venytys kädet niskan takana',
  'Bench Jump': 'Penkkihyppy',
  'Bench Press - Powerlifting': 'Penkkipunnerrus (voimanosto)',
  'Bench Press - With Bands': 'Penkkipunnerrus kuminauhoilla',
  'Bench Press with Chains': 'Penkkipunnerrus ketjuilla',
  'Bench Sprint': 'Penkkisprintti',
  'Bent Over Dumbbell Rear Delt Raise With Head On Bench': 'Takaolkapään vipunosto kumarrettuna otsa penkillä',
  'Bent Over Low-Pulley Side Lateral': 'Sivunosto kumarrettuna alataljasta',
  'Bent Over One-Arm Long Bar Row': 'Yhden käden tankosoutu kumarrettuna',
  'Bent Over Two-Arm Long Bar Row': 'Kahden käden tankosoutu kumarrettuna',
  'Bent Over Two-Dumbbell Row With Palms In': 'Käsipainosoutu kumarrettuna neutraaliotteella',
  'Bent Press': 'Kylkipunnerrus',
  'Bent-Arm Barbell Pullover': 'Pullover tangolla kyynärpäät koukussa',
  'Bent-Arm Dumbbell Pullover': 'Pullover käsipainolla kyynärpäät koukussa',
  'Bent-Knee Hip Raise': 'Lantionnosto polvet koukussa',
  Bicycling: 'Pyöräily',
  'Board Press': 'Lautapenkkipunnerrus',
  'Body Tricep Press': 'Ojentajapunnerrus kehonpainolla',
  'Bodyweight Flyes': 'Vipunosto kehonpainolla',
  'Bosu Ball Cable Crunch With Side Bends': 'Taljavatsarutistus Bosu-pallolla kylkitaivutuksin',
  'Bottoms Up': 'Lantion rullaus ylös',
  'Bottoms-Up Clean From The Hang Position': 'Bottoms-up-rinnalleveto riipunnasta',
  'Box Jump (Multiple Response)': 'Laatikkohyppy (sarjana)',
  'Box Skip': 'Laatikkoloikka',
  'Box Squat with Bands': 'Laatikkokyykky kuminauhoilla',
  'Box Squat with Chains': 'Laatikkokyykky ketjuilla',
  'Brachialis-SMR': 'Olkalihaksen rullaus',
  'Bradford/Rocky Presses': 'Bradford-punnerrus',
  'Butt-Ups': 'Lantionnosto kyynärnojassa',
  Butterfly: 'Perhoslaite',
  'Cable Chest Press': 'Rintapunnerrus taljassa',
  'Cable Deadlifts': 'Maastaveto taljassa',
  'Cable Hammer Curls - Rope Attachment': 'Vasarakääntö taljassa köydellä',
  'Cable Hip Adduction': 'Lonkan lähennys taljassa',
  'Cable Incline Pushdown': 'Ojentajapushdown taljassa kumarrettuna',
  'Cable Incline Triceps Extension': 'Ojentajapunnerrus taljassa vinopenkillä',
  'Cable Internal Rotation': 'Sisäkierto taljassa',
  'Cable Iron Cross': 'Rautaristi taljassa',
  'Cable Judo Flip': 'Judoheitto taljassa',
  'Cable Lying Triceps Extension': 'Ranskalainen punnerrus taljassa maaten',
  'Cable One Arm Tricep Extension': 'Yhden käden ojentajapunnerrus taljassa',
  'Cable Preacher Curl': 'Saarnaajakääntö taljassa',
  'Cable Reverse Crunch': 'Käänteinen vatsarutistus taljassa',
  'Cable Rope Overhead Triceps Extension': 'Ojentajapunnerrus pään yli taljassa köydellä',
  'Cable Rope Rear-Delt Rows': 'Takaolkapään soutu taljassa köydellä',
  'Cable Russian Twists': 'Venäläinen kierto taljassa',
  'Cable Seated Crunch': 'Istuen vatsarutistus taljassa',
  'Cable Seated Lateral Raise': 'Istuen sivunosto taljassa',
  'Cable Shoulder Press': 'Pystypunnerrus taljassa',
  'Cable Shrugs': 'Kohautus taljassa',
  'Cable Wrist Curl': 'Ranteen koukistus taljassa',
  'Calf Press On The Leg Press Machine': 'Pohjeprässi jalkaprässillä',
  'Calf Raise On A Dumbbell': 'Pohjenosto käsipainon päällä',
  'Calf Stretch Elbows Against Wall': 'Pohkeen venytys kyynärpäät seinää vasten',
  'Calf Stretch Hands Against Wall': 'Pohkeen venytys kädet seinää vasten',
  'Calf-Machine Shoulder Shrug': 'Kohautus pohjelaitteessa',
  'Calves-SMR': 'Pohkeiden rullaus',
  'Car Deadlift': 'Autonnosto',
  'Car Drivers': 'Levypainon kierto edessä',
  'Carioca Quick Step': 'Carioca-sivuaskellus',
  'Catch and Overhead Throw': 'Kiinniotto ja heitto pään yli',
  'Chain Handle Extension': 'Ojentajapunnerrus ketjukahvalla',
  // Cable chain handles, lying like a dumbbell press — a different lift and
  // a different piece of equipment from the barbell 'Bench Press with
  // Chains' below, which shared this label until the sweep in the recheck
  // round 2026-09-29.
  'Chain Press': 'Punnerrus ketjukahvoilla',
  'Chair Leg Extended Stretch': 'Takareiden venytys tuolilla jalka suorana',
  'Chair Lower Back Stretch': 'Alaselän venytys tuolilla',
  'Chair Upper Body Stretch': 'Ylävartalon venytys tuolilla',
  'Chest And Front Of Shoulder Stretch': 'Rinnan ja etuolkapään venytys',
  'Chest Push (multiple response)': 'Rintatyöntö (sarjana)',
  'Chest Push (single response)': 'Rintatyöntö (yksittäin)',
  'Chest Push from 3 point stance': 'Rintatyöntö kolmen pisteen asennosta',
  'Chest Push with Run Release': 'Rintatyöntö juoksulähdöllä',
  'Chest Stretch on Stability Ball': 'Rinnan venytys jumppapallolla',
  "Child's Pose": 'Lapsen asento',
  'Circus Bell': 'Sirkuskuula',
  Clean: 'Rinnalleveto',
  'Clean and Jerk': 'Rinnalleveto ja työntö',
  'Clean and Press': 'Rinnalleveto ja punnerrus',
  'Clean Deadlift': 'Rinnallevedon maastaveto',
  'Clean from Blocks': 'Rinnalleveto korokkeilta',
  'Clean Pull': 'Rinnallevedon veto',
  'Clean Shrug': 'Rinnallevedon kohautus',
  'Clock Push-Up': 'Kellopunnerrus',
  'Close-Grip Barbell Bench Press': 'Kapea penkkipunnerrus tangolla',
  'Close-Grip Dumbbell Press': 'Kapea penkkipunnerrus käsipainoilla',
  'Close-Grip EZ Bar Curl': 'Kapea hauiskääntö EZ-tangolla',
  'Close-Grip EZ-Bar Curl with Band': 'Kapea hauiskääntö EZ-tangolla ja kuminauhalla',
  'Close-Grip EZ-Bar Press': 'Kapea punnerrus EZ-tangolla',
  'Close-Grip Push-Up off of a Dumbbell': 'Kapea punnerrus käsipainon päältä',
  'Close-Grip Standing Barbell Curl': 'Kapea hauiskääntö seisten tangolla',
  Cocoons: 'Vatsarutistus polvet rintaan',
  "Conan's Wheel": 'Conanin pyörä',
  'Cross Body Hammer Curl': 'Vasarakääntö vartalon yli',
  'Cross Over - With Bands': 'Ristikkäisveto kuminauhoilla',
  'Cross-Body Crunch': 'Ristikkäinen vatsarutistus',
  'Crossover Reverse Lunge': 'Ristiin taakse astuva askelkyykky',
  Crucifix: 'Ristiinpito käsipainoilla',
  'Crunch - Hands Overhead': 'Vatsarutistus kädet pään yli',
  'Crunch - Legs On Exercise Ball': 'Vatsarutistus jalat jumppapallolla',
  'Cuban Press': 'Kuubalainen punnerrus',
  "Dancer's Stretch": 'Tanssijan venytys',
  'Deadlift with Bands': 'Maastaveto kuminauhoilla',
  'Deadlift with Chains': 'Maastaveto ketjuilla',
  'Decline Barbell Bench Press': 'Laskeva penkkipunnerrus tangolla',
  'Decline Close-Grip Bench To Skull Crusher': 'Laskeva kapea penkkipunnerrus ja ranskalainen punnerrus',
  'Decline Crunch': 'Laskeva vatsarutistus',
  'Decline Dumbbell Bench Press': 'Laskeva penkkipunnerrus käsipainoilla',
  'Decline Dumbbell Flyes': 'Laskeva vipunosto käsipainoilla',
  'Decline Dumbbell Triceps Extension': 'Laskeva ojentajapunnerrus käsipainoilla',
  'Decline EZ Bar Triceps Extension': 'Laskeva ojentajapunnerrus EZ-tangolla',
  'Decline Oblique Crunch': 'Laskeva vinovatsarutistus',
  'Decline Reverse Crunch': 'Laskeva käänteinen vatsarutistus',
  'Decline Smith Press': 'Laskeva penkkipunnerrus Smith-laitteessa',
  'Depth Jump Leap': 'Pudotushyppy loikalla',
  'Dip Machine': 'Dippilaite',
  'Dips - Chest Version': 'Dipit rinnalle',
  'Dips - Triceps Version': 'Dipit ojentajille',
  'Double Kettlebell Alternating Hang Clean': 'Vuorottainen rinnalleveto riipunnasta kahdella kahvakuulalla',
  'Double Kettlebell Jerk': 'Työntö kahdella kahvakuulalla',
  'Double Kettlebell Push Press': 'Työntöpunnerrus kahdella kahvakuulalla',
  'Double Kettlebell Snatch': 'Tempaus kahdella kahvakuulalla',
  'Double Kettlebell Windmill': 'Tuulimylly kahdella kahvakuulalla',
  'Double Leg Butt Kick': 'Kahden jalan kantapotku',
  'Downward Facing Balance': 'Vaakatasapaino eteen',
  'Drag Curl': 'Vetokääntö tangolla',
  'Drop Push': 'Pudotuspunnerrus',
  'Dumbbell Alternate Bicep Curl': 'Vuorottainen hauiskääntö käsipainoilla',
  'Dumbbell Bench Press with Neutral Grip': 'Penkkipunnerrus käsipainoilla neutraaliotteella',
  'Dumbbell Clean': 'Rinnalleveto käsipainoilla',
  'Dumbbell Incline Row': 'Soutu vinopenkillä käsipainoilla',
  'Dumbbell Incline Shoulder Raise': 'Olkapäännosto vinopenkillä käsipainoilla',
  'Dumbbell Lying One-Arm Rear Lateral Raise': 'Yhden käden takaolkapään vipunosto maaten käsipainolla',
  'Dumbbell Lying Pronation': 'Kyynärvarren sisäkierto maaten käsipainolla',
  'Dumbbell Lying Rear Lateral Raise': 'Takaolkapään vipunosto maaten käsipainoilla',
  'Dumbbell Lying Supination': 'Kyynärvarren ulkokierto maaten käsipainolla',
  'Dumbbell One-Arm Shoulder Press': 'Yhden käden pystypunnerrus käsipainolla',
  'Dumbbell One-Arm Triceps Extension': 'Yhden käden ojentajapunnerrus käsipainolla',
  'Dumbbell One-Arm Upright Row': 'Yhden käden pystysoutu käsipainolla',
  'Dumbbell Prone Incline Curl': 'Hauiskääntö vinopenkillä vatsallaan käsipainoilla',
  'Dumbbell Raise': 'Nosto käsipainoilla',
  'Dumbbell Rear Lunge': 'Taakse astuva askelkyykky käsipainoilla',
  'Dumbbell Scaption': 'Vinonosto käsipainoilla',
  'Dumbbell Seated Box Jump': 'Istuen laatikkohyppy käsipainoilla',
  'Dumbbell Seated One-Leg Calf Raise': 'Istuen yhden jalan pohjenosto käsipainolla',
  'Dumbbell Shrug': 'Kohautus käsipainoilla',
  'Dumbbell Side Bend': 'Kylkitaivutus käsipainolla',
  'Dumbbell Squat': 'Kyykky käsipainoilla',
  'Dumbbell Squat To A Bench': 'Kyykky penkille käsipainoilla',
  'Dumbbell Step Ups': 'Askelnousu käsipainoilla',
  'Dumbbell Tricep Extension -Pronated Grip': 'Ojentajapunnerrus käsipainoilla yläotteella',
  'Dynamic Back Stretch': 'Dynaaminen selän venytys',
  'Dynamic Chest Stretch': 'Dynaaminen rinnan venytys',
  'Elbow Circles': 'Kyynärpään pyöritykset',
  'Elbow to Knee': 'Kyynärpää polveen',
  'Elbows Back': 'Kyynärpäät taakse -venytys',
  'Elevated Back Lunge': 'Taakse astuva askelkyykky korokkeelta',
  'Elevated Cable Rows': 'Soutu ylätaljasta korokkeelta',
  'Exercise Ball Crunch': 'Vatsarutistus jumppapallolla',
  'Exercise Ball Pull-In': 'Polvenveto jumppapallolla',
  'Extended Range One-Arm Kettlebell Floor Press': 'Yhden käden lattiapunnerrus kahvakuulalla laajalla liikeradalla',
  'External Rotation': 'Ulkokierto',
  'External Rotation with Band': 'Ulkokierto kuminauhalla',
  'External Rotation with Cable': 'Ulkokierto taljassa',
  'EZ-Bar Skullcrusher': 'Ranskalainen punnerrus EZ-tangolla',
  'Fast Skipping': 'Nopea hyppely',
  'Finger Curls': 'Sormien koukistus',
  'Flat Bench Cable Flyes': 'Vipunosto taljassa tasapenkillä',
  'Flat Bench Leg Pull-In': 'Polvenveto penkillä',
  'Flat Bench Lying Leg Raise': 'Jalannosto penkillä maaten',
  'Flexor Incline Dumbbell Curls': 'Koukistajakääntö vinopenkillä käsipainoilla',
  'Floor Press': 'Lattiapunnerrus',
  'Floor Press with Chains': 'Lattiapunnerrus ketjuilla',
  'Flutter Kicks': 'Saksipotkut',
  'Foot-SMR': 'Jalkapohjan rullaus',
  'Forward Drag with Press': 'Reen veto eteen punnerruksella',
  'Frankenstein Squat': 'Frankenstein-kyykky',
  'Freehand Jump Squat': 'Hyppykyykky ilman lisäpainoa',
  'Frog Hops': 'Sammakkohypyt',
  'Frog Sit-Ups': 'Sammakkoistumaannousu',
  'Front Barbell Squat': 'Etukyykky tangolla',
  'Front Barbell Squat To A Bench': 'Etukyykky penkille tangolla',
  'Front Box Jump': 'Laatikkohyppy eteen',
  'Front Cable Raise': 'Etunosto taljassa',
  'Front Cone Hops (or hurdle hops)': 'Kartiohypyt eteen',
  'Front Dumbbell Raise': 'Etunosto käsipainoilla',
  'Front Incline Dumbbell Raise': 'Etunosto vinopenkillä käsipainoilla',
  'Front Leg Raises': 'Jalannosto eteen',
  'Front Plate Raise': 'Etunosto levypainolla',
  'Front Raise And Pullover': 'Etunosto ja pullover',
  'Front Squat (Clean Grip)': 'Etukyykky rinnalleveto-otteella',
  'Front Squats With Two Kettlebells': 'Etukyykky kahdella kahvakuulalla',
  'Front Two-Dumbbell Raise': 'Etunosto kahdella käsipainolla',
  'Full Range-Of-Motion Lat Pulldown': 'Ylätalja täydellä liikeradalla',
  'Gironda Sternum Chins': 'Girondan rintalastaleuanveto',
  'Good Morning off Pins': 'Aamunavaus tapeilta',
  'Gorilla Chin/Crunch': 'Gorillaleuanveto vatsarutistuksella',
  'Groin and Back Stretch': 'Nivusen ja selän venytys',
  Groiners: 'Nivusavaus punnerrusasennossa',
  'Hammer Curls': 'Vasarakääntö',
  'Hammer Grip Incline DB Bench Press': 'Vinopenkkipunnerrus käsipainoilla neutraaliotteella',
  'Hamstring Stretch': 'Takareiden venytys',
  'Hamstring-SMR': 'Takareiden rullaus',
  'Hang Clean': 'Rinnalleveto riipunnasta',
  'Hang Clean - Below the Knees': 'Rinnalleveto riipunnasta polvien alta',
  'Hang Snatch': 'Tempaus riipunnasta',
  'Hang Snatch - Below Knees': 'Tempaus riipunnasta polvien alta',
  'Hanging Bar Good Morning': 'Aamunavaus tanko niskassa roikkuen',
  'Hanging Pike': 'Roikkuen taittoliike',
  'Heaving Snatch Balance': 'Tempaustasapaino työnnöllä',
  'Heavy Bag Thrust': 'Nyrkkeilysäkin työntö',
  'High Cable Curls': 'Hauiskääntö ylätaljassa',
  'Hip Circles (prone)': 'Lonkan pyöritykset konttausasennossa',
  'Hip Extension with Bands': 'Lonkan ojennus kuminauhalla',
  'Hip Flexion with Band': 'Lonkan koukistus kuminauhalla',
  'Hip Lift with Band': 'Lantionnosto kuminauhalla',
  'Hug A Ball': 'Pallon halaus -venytys',
  'Hug Knees To Chest': 'Polvet rintaan -venytys',
  'Hurdle Hops': 'Aitahypyt',
  'Hyperextensions (Back Extensions)': 'Selän ojennus',
  'Hyperextensions With No Hyperextension Bench': 'Selän ojennus ilman penkkiä',
  'Iliotibial Tract-SMR': 'IT-jänteen rullaus',
  Inchworm: 'Mittarimato',
  'Incline Barbell Triceps Extension': 'Ojentajapunnerrus vinopenkillä tangolla',
  'Incline Bench Pull': 'Soutu vinopenkillä vatsallaan',
  'Incline Cable Chest Press': 'Vinorintapunnerrus taljassa',
  'Incline Cable Flye': 'Vipunosto taljassa vinopenkillä',
  'Incline Dumbbell Bench With Palms Facing In': 'Vinopenkkipunnerrus käsipainoilla neutraaliotteella',
  'Incline Dumbbell Flyes': 'Vinovipunosto käsipainoilla',
  'Incline Dumbbell Flyes - With A Twist': 'Vinovipunosto käsipainoilla kierrolla',
  'Incline Hammer Curls': 'Vasarakääntö vinopenkillä',
  'Incline Inner Biceps Curl': 'Sisemmän hauiksen kääntö vinopenkillä',
  'Incline Push-Up Close-Grip': 'Vinopunnerrus kapealla otteella',
  'Incline Push-Up Depth Jump': 'Vinopunnerrus pudotushypyllä',
  'Incline Push-Up Medium': 'Vinopunnerrus keskiotteella',
  'Incline Push-Up Reverse Grip': 'Vinopunnerrus käänteisotteella',
  'Incline Push-Up Wide': 'Vinopunnerrus leveällä otteella',
  'Intermediate Groin Stretch': 'Nivusen venytys, keskitaso',
  'Intermediate Hip Flexor and Quad Stretch': 'Lonkankoukistajan ja etureiden venytys, keskitaso',
  'Internal Rotation with Band': 'Sisäkierto kuminauhalla',
  'Inverted Row with Straps': 'Kehonpainosoutu remmeillä',
  'Iron Cross': 'Rautaristi',
  'Iron Crosses (stretch)': 'Rautaristivenytys',
  'Isometric Chest Squeezes': 'Isometrinen rinnan puristus',
  'Isometric Neck Exercise - Front And Back': 'Isometrinen niskaharjoite eteen ja taakse',
  'Isometric Neck Exercise - Sides': 'Isometrinen niskaharjoite sivuille',
  'Isometric Wipers': 'Isometriset tuulilasinpyyhkijät',
  'IT Band and Glute Stretch': 'IT-jänteen ja pakaran venytys',
  'Jackknife Sit-Up': 'Linkkuveitsi-istumaannousu',
  'Janda Sit-Up': 'Janda-istumaannousu',
  'Jefferson Squats': 'Jefferson-kyykky',
  'Jerk Balance': 'Työntötasapaino',
  'Jerk Dip Squat': 'Työnnön joustokyykky',
  'JM Press': 'JM-punnerrus',
  'Keg Load': 'Tynnyrin nosto',
  'Kettlebell Arnold Press': 'Arnold-punnerrus kahvakuulilla',
  'Kettlebell Dead Clean': 'Rinnalleveto kahvakuulalla lattiasta',
  'Kettlebell Figure 8': 'Kahvakuulan kahdeksikko',
  'Kettlebell Hang Clean': 'Rinnalleveto kahvakuulalla riipunnasta',
  'Kettlebell One-Legged Deadlift': 'Yhden jalan maastaveto kahvakuulalla',
  'Kettlebell Pass Between The Legs': 'Kahvakuulan siirto jalkojen välistä',
  'Kettlebell Pirate Ships': 'Kahvakuulan merirosvolaivat',
  'Kettlebell Pistol Squat': 'Pistoolikyykky kahvakuulalla',
  'Kettlebell Seated Press': 'Istuen punnerrus kahvakuulilla',
  'Kettlebell Seesaw Press': 'Vuorottainen punnerrus kahvakuulilla',
  'Kettlebell Sumo High Pull': 'Sumopystysoutu kahvakuulalla',
  'Kettlebell Thruster': 'Thruster kahvakuulilla',
  'Kettlebell Turkish Get-Up (Lunge style)': 'Turkish get-up kahvakuulalla (askelkyykkytyyli)',
  'Kettlebell Turkish Get-Up (Squat style)': 'Turkish get-up kahvakuulalla (kyykkytyyli)',
  'Kettlebell Windmill': 'Kahvakuulan tuulimylly',
  'Kipping Muscle Up': 'Muscle up vauhdilla',
  'Knee Across The Body': 'Polvi vartalon yli -venytys',
  'Knee Circles': 'Polvien pyöritykset',
  'Knee Tuck Jump': 'Polvennostohyppy',
  'Knee/Hip Raise On Parallel Bars': 'Polven- ja lonkannosto dippitelineessä',
  'Kneeling Arm Drill': 'Polvillaan käsien juoksuharjoite',
  'Kneeling Cable Crunch With Alternating Oblique Twists': 'Polvillaan taljavatsarutistus vuorottaisin kierroin',
  'Kneeling Cable Triceps Extension': 'Polvillaan ojentajapunnerrus taljassa',
  'Kneeling Forearm Stretch': 'Polvillaan kyynärvarren venytys',
  'Kneeling High Pulley Row': 'Polvillaan soutu ylätaljasta',
  'Kneeling Hip Flexor': 'Polvillaan lonkankoukistajan venytys',
  'Kneeling Jump Squat': 'Hyppykyykky polviltaan',
  'Kneeling Single-Arm High Pulley Row': 'Polvillaan yhden käden soutu ylätaljasta',
  'Kneeling Squat': 'Kyykky polviltaan',
  "Landmine 180's": 'Landmine-kierto 180°',
  'Landmine Linear Jammer': 'Landmine-työntö suoraan',
  'Landmine Press': 'Landmine-punnerrus',
  'Lateral Box Jump': 'Laatikkohyppy sivulle',
  'Lateral Cone Hops': 'Kartiohypyt sivulle',
  'Lateral Raise - With Bands': 'Sivunosto kuminauhoilla',
  'Latissimus Dorsi-SMR': 'Leveän selkälihaksen rullaus',
  'Leg Extensions': 'Reiden ojennus',
  'Leg Lift': 'Jalannosto',
  'Leg Pull-In': 'Polvenveto',
  'Leg-Over Floor Press': 'Lattiapunnerrus jalka ristissä',
  'Leg-Up Hamstring Stretch': 'Takareiden venytys jalka koholla',
  'Leverage Chest Press': 'Rintapunnerrus vipuvarsilaitteessa',
  'Leverage Deadlift': 'Maastaveto vipuvarsilaitteessa',
  'Leverage Decline Chest Press': 'Laskeva rintapunnerrus vipuvarsilaitteessa',
  'Leverage High Row': 'Yläsoutu vipuvarsilaitteessa',
  'Leverage Incline Chest Press': 'Vinorintapunnerrus vipuvarsilaitteessa',
  'Leverage Iso Row': 'Yksipuolinen soutu vipuvarsilaitteessa',
  'Leverage Shoulder Press': 'Pystypunnerrus vipuvarsilaitteessa',
  'Leverage Shrug': 'Kohautus vipuvarsilaitteessa',
  'Linear 3-Part Start Technique': 'Kolmivaiheinen lähtötekniikka',
  'Linear Acceleration Wall Drill': 'Kiihdytysharjoite seinää vasten',
  'Linear Depth Jump': 'Pudotushyppy eteen',
  'Log Lift': 'Tukin nosto',
  'London Bridges': 'London bridges',
  'Looking At Ceiling': 'Katse kattoon -venytys',
  'Low Cable Crossover': 'Ristikkäisveto alataljasta',
  'Low Cable Triceps Extension': 'Ojentajapunnerrus alataljasta',
  'Low Pulley Row To Neck': 'Soutu alataljasta niskaan',
  // A prone floor back extension (lift the chest with the lower back
  // muscles, no bench) — a different lift from the -SMR entry below it,
  // which is a foam-roller massage drill. Both shared 'Alaselän rullaus'
  // ("lower back rolling") until the recheck round 2026-09-29, so
  // matchAppLabel always resolved this label to whichever of the two the
  // stored-name map listed first.
  'Lower Back Curl': 'Selän ojennus lattialla',
  'Lower Back-SMR': 'Alaselän rullaus',
  'Lunge Pass Through': 'Askelkyykky pallon siirrolla',
  'Lunge Sprint': 'Askelkyykkysprintti',
  'Lying Bent Leg Groin': 'Nivusen venytys maaten polvet koukussa',
  'Lying Cable Curl': 'Hauiskääntö taljassa maaten',
  'Lying Cambered Barbell Row': 'Soutu maaten kaarevalla tangolla',
  'Lying Close-Grip Bar Curl On High Pulley': 'Kapea hauiskääntö maaten ylätaljassa',
  'Lying Close-Grip Barbell Triceps Extension Behind The Head': 'Kapea ojentajapunnerrus maaten tangolla pään taakse',
  'Lying Close-Grip Barbell Triceps Press To Chin': 'Kapea ojentajapunnerrus maaten tangolla leualle',
  'Lying Crossover': 'Ristiinkierto maaten',
  'Lying Dumbbell Tricep Extension': 'Ranskalainen punnerrus käsipainoilla',
  'Lying Face Down Plate Neck Resistance': 'Niskan vastusharjoite vatsallaan levypainolla',
  'Lying Face Up Plate Neck Resistance': 'Niskan vastusharjoite selällään levypainolla',
  'Lying Glute': 'Pakaran venytys maaten',
  'Lying Hamstring': 'Takareiden venytys maaten',
  'Lying High Bench Barbell Curl': 'Hauiskääntö tangolla korkealla penkillä maaten',
  'Lying Leg Curls': 'Maaten takareisikoukistus',
  'Lying Machine Squat': 'Kyykky makuulaitteessa',
  'Lying One-Arm Lateral Raise': 'Yhden käden sivunosto maaten',
  'Lying Prone Quadriceps': 'Etureiden venytys vatsallaan',
  'Lying Rear Delt Raise': 'Takaolkapään vipunosto maaten',
  'Lying Supine Dumbbell Curl': 'Hauiskääntö käsipainoilla selällään',
  'Lying T-Bar Row': 'T-tankosoutu vatsallaan',
  'Machine Bench Press': 'Penkkipunnerrus laitteessa',
  'Machine Bicep Curl': 'Hauiskääntö laitteessa',
  'Machine Preacher Curls': 'Saarnaajakääntö laitteessa',
  'Machine Shoulder (Military) Press': 'Pystypunnerrus laitteessa',
  'Machine Triceps Extension': 'Ojentajapunnerrus laitteessa',
  'Medicine Ball Chest Pass': 'Kuntopallon rintasyöttö',
  'Medicine Ball Full Twist': 'Kuntopallon täyskierto',
  'Medicine Ball Scoop Throw': 'Kuntopallon alakauttaheitto',
  'Middle Back Shrug': 'Keskiselän kohautus',
  'Middle Back Stretch': 'Keskiselän venytys',
  'Mixed Grip Chin': 'Leuanveto sekaotteella',
  'Monster Walk': 'Hirviökävely kuminauhalla',
  'Moving Claw Series': 'Liikkuva raapaisuharjoite',
  'Muscle Snatch': 'Muscle snatch',
  'Muscle Up': 'Muscle up',
  'Narrow Stance Hack Squats': 'Hack squat kapealla haara-asennolla',
  'Narrow Stance Leg Press': 'Jalkaprässi kapealla haara-asennolla',
  'Narrow Stance Squats': 'Kyykky kapealla haara-asennolla',
  'Natural Glute Ham Raise': 'Nordic-takareisiliike',
  'Neck Press': 'Niskapunnerrus',
  'Neck-SMR': 'Niskan rullaus',
  'Oblique Crunches': 'Vinovatsarutistus',
  'Oblique Crunches - On The Floor': 'Vinovatsarutistus lattialla',
  'Olympic Squat': 'Olympiakyykky',
  'On Your Side Quad Stretch': 'Etureiden venytys kyljellään',
  'On-Your-Back Quad Stretch': 'Etureiden venytys selällään',
  'One Arm Against Wall': 'Rinnan venytys käsi seinää vasten',
  'One Arm Chin-Up': 'Yhden käden leuanveto',
  'One Arm Dumbbell Bench Press': 'Yhden käden penkkipunnerrus käsipainolla',
  'One Arm Dumbbell Preacher Curl': 'Yhden käden saarnaajakääntö käsipainolla',
  'One Arm Floor Press': 'Yhden käden lattiapunnerrus',
  'One Arm Lat Pulldown': 'Yhden käden ylätalja',
  'One Arm Pronated Dumbbell Triceps Extension': 'Yhden käden ojentajapunnerrus käsipainolla yläotteella',
  'One Arm Supinated Dumbbell Triceps Extension': 'Yhden käden ojentajapunnerrus käsipainolla alaotteella',
  'One Half Locust': 'Puolikas heinäsirkka',
  'One Handed Hang': 'Yhden käden roikunta',
  'One Knee To Chest': 'Toinen polvi rintaan -venytys',
  'One Leg Barbell Squat': 'Yhden jalan kyykky tangolla',
  'One-Arm Flat Bench Dumbbell Flye': 'Yhden käden vipunosto tasapenkillä',
  'One-Arm High-Pulley Cable Side Bends': 'Yhden käden kylkitaivutus ylätaljassa',
  'One-Arm Incline Lateral Raise': 'Yhden käden sivunosto vinopenkillä',
  'One-Arm Kettlebell Clean': 'Yhden käden rinnalleveto kahvakuulalla',
  'One-Arm Kettlebell Clean and Jerk': 'Yhden käden rinnalleveto ja työntö kahvakuulalla',
  'One-Arm Kettlebell Floor Press': 'Yhden käden lattiapunnerrus kahvakuulalla',
  'One-Arm Kettlebell Jerk': 'Yhden käden työntö kahvakuulalla',
  'One-Arm Kettlebell Military Press To The Side': 'Yhden käden pystypunnerrus kahvakuulalla sivulle',
  'One-Arm Kettlebell Para Press': 'Yhden käden para-punnerrus kahvakuulalla',
  'One-Arm Kettlebell Push Press': 'Yhden käden työntöpunnerrus kahvakuulalla',
  'One-Arm Kettlebell Row': 'Yhden käden soutu kahvakuulalla',
  'One-Arm Kettlebell Snatch': 'Yhden käden tempaus kahvakuulalla',
  'One-Arm Kettlebell Split Jerk': 'Yhden käden askeltyöntö kahvakuulalla',
  'One-Arm Kettlebell Split Snatch': 'Yhden käden askeltempaus kahvakuulalla',
  'One-Arm Long Bar Row': 'Yhden käden tankosoutu',
  'One-Arm Medicine Ball Slam': 'Yhden käden kuntopallon iskuheitto',
  'One-Arm Open Palm Kettlebell Clean': 'Yhden käden rinnalleveto kahvakuulalla avokämmenellä',
  'One-Arm Overhead Kettlebell Squats': 'Yhden käden kyykky kahvakuula pään yllä',
  'One-Arm Side Deadlift': 'Yhden käden maastaveto sivulta',
  'One-Arm Side Laterals': 'Yhden käden sivunosto',
  'Open Palm Kettlebell Clean': 'Rinnalleveto kahvakuulalla avokämmenellä',
  'Otis-Up': 'Otis-istumaannousu',
  'Overhead Cable Curl': 'Hauiskääntö taljassa pään korkeudella',
  'Overhead Lat': 'Leveän selkälihaksen venytys pään yli',
  'Overhead Slam': 'Iskuheitto pään yli',
  'Overhead Squat': 'Kyykky tanko pään yllä',
  'Overhead Stretch': 'Venytys pään yli',
  'Overhead Triceps': 'Ojentajan venytys pään yli',
  'Pallof Press': 'Pallof-punnerrus',
  'Pallof Press With Rotation': 'Pallof-punnerrus kierrolla',
  'Palms-Down Dumbbell Wrist Curl Over A Bench': 'Ranteen ojennus käsipainoilla penkin yli',
  'Palms-Down Wrist Curl Over A Bench': 'Ranteen ojennus tangolla penkin yli',
  'Palms-Up Barbell Wrist Curl Over A Bench': 'Ranteen koukistus tangolla penkin yli',
  'Palms-Up Dumbbell Wrist Curl Over A Bench': 'Ranteen koukistus käsipainoilla penkin yli',
  'Parallel Bar Dip': 'Dippi nojapuilla',
  'Pelvic Tilt Into Bridge': 'Lantion kallistus ja nosto',
  'Peroneals Stretch': 'Pohkeen ulkosivun venytys',
  'Peroneals-SMR': 'Pohkeen ulkosivun rullaus',
  'Physioball Hip Bridge': 'Lantionnosto jumppapallolla',
  'Pin Presses': 'Penkkipunnerrus tapeilta',
  'Piriformis-SMR': 'Päärynälihaksen rullaus',
  'Plate Pinch': 'Levypainon puristusote',
  'Plate Twist': 'Levypainon kierto',
  'Platform Hamstring Slides': "Takareiden liu'utukset",
  'Plie Dumbbell Squat': 'Plie-kyykky käsipainolla',
  'Plyo Kettlebell Pushups': 'Plyometrinen punnerrus kahvakuulilla',
  'Plyo Push-up': 'Plyometrinen punnerrus',
  'Posterior Tibialis Stretch': 'Takimmaisen säärilihaksen venytys',
  'Power Clean from Blocks': 'Voimarinnalleveto korokkeilta',
  'Power Jerk': 'Voimatyöntö',
  'Power Partials': 'Osaliikkeet sivunostossa',
  'Power Snatch': 'Voimatempaus',
  'Power Snatch from Blocks': 'Voimatempaus korokkeilta',
  'Power Stairs': 'Voimaportaat',
  'Preacher Hammer Dumbbell Curl': 'Saarnaajavasarakääntö käsipainoilla',
  'Press Sit-Up': 'Istumaannousu punnerruksella',
  'Prone Manual Hamstring': 'Takareisikoukistus vastuksella vatsallaan',
  'Prowler Sprint': 'Kelkkasprintti',
  'Pull Through': 'Veto jalkojen välistä',
  'Push Press - Behind the Neck': 'Työntöpunnerrus niskan takaa',
  'Push-Ups - Close Triceps Position': 'Punnerrus kapealla ojentajaotteella',
  'Push-Ups With Feet Elevated': 'Punnerrus jalat koholla',
  'Push-Ups With Feet On An Exercise Ball': 'Punnerrus jalat jumppapallolla',
  'Pushups (Close and Wide Hand Positions)': 'Punnerrus kapealla ja leveällä otteella',
  Pyramid: 'Pyramidi',
  'Quad Stretch': 'Etureiden venytys',
  'Quadriceps-SMR': 'Etureiden rullaus',
  'Quick Leap': 'Nopea loikka',
  'Rack Delivery': 'Nosto rintakannatukseen',
  'Rack Pull with Bands': 'Rack pull kuminauhoilla',
  'Rack Pulls': 'Rack pull',
  'Rear Leg Raises': 'Jalannosto taakse',
  'Return Push from Stance': 'Työntö paluuasennosta',
  'Reverse Band Bench Press': 'Penkkipunnerrus käänteisillä kuminauhoilla',
  'Reverse Band Box Squat': 'Laatikkokyykky käänteisillä kuminauhoilla',
  'Reverse Band Deadlift': 'Maastaveto käänteisillä kuminauhoilla',
  'Reverse Band Power Squat': 'Voimakyykky käänteisillä kuminauhoilla',
  'Reverse Band Sumo Deadlift': 'Sumomaastaveto käänteisillä kuminauhoilla',
  'Reverse Barbell Curl': 'Käänteinen hauiskääntö tangolla',
  'Reverse Barbell Preacher Curls': 'Käänteinen saarnaajakääntö tangolla',
  'Reverse Cable Curl': 'Käänteinen hauiskääntö taljassa',
  'Reverse Crunch': 'Käänteinen vatsarutistus',
  'Reverse Flyes': 'Takaolkapään vipunosto',
  'Reverse Flyes With External Rotation': 'Takaolkapään vipunosto ulkokierrolla',
  'Reverse Grip Bent-Over Rows': 'Tankosoutu alaotteella kumarrettuna',
  'Reverse Grip Triceps Pushdown': 'Ojentajapushdown alaotteella',
  'Reverse Plate Curls': 'Käänteinen kääntö levypainolla',
  'Reverse Triceps Bench Press': 'Penkkipunnerrus alaotteella ojentajille',
  'Rhomboids-SMR': 'Suunnikaslihasten rullaus',
  'Rickshaw Carry': 'Riksakävely',
  'Rickshaw Deadlift': 'Riksamaastaveto',
  'Ring Dips': 'Dipit renkailla',
  'Rocket Jump': 'Rakettihyppy',
  'Rocking Standing Calf Raise': 'Keinuva pohjenosto seisten',
  'Rocky Pull-Ups/Pulldowns': 'Rocky-leuanveto',
  'Romanian Deadlift from Deficit': 'Romanialainen maastaveto korokkeelta',
  'Rope Climb': 'Köysikiipeily',
  'Rope Crunch': 'Vatsarutistus köydellä',
  'Rope Jumping': 'Hyppynaru',
  'Rope Straight-Arm Pulldown': 'Suorin käsin veto alas köydellä',
  'Round The World Shoulder Stretch': 'Olkapään ympyräpyöritys',
  "Runner's Stretch": 'Juoksijan venytys',
  'Running, Treadmill': 'Juoksumatto',
  'Sandbag Load': 'Hiekkasäkin nosto',
  'Scissor Kick': 'Saksipotku',
  'Scissors Jump': 'Saksihyppy',
  'Seated Band Hamstring Curl': 'Istuen takareisikoukistus kuminauhalla',
  'Seated Barbell Military Press': 'Istuen pystypunnerrus tangolla',
  'Seated Barbell Twist': 'Istuen kierto tangolla',
  'Seated Bent-Over One-Arm Dumbbell Triceps Extension': 'Istuen yhden käden ojentajapunnerrus kumarrettuna käsipainolla',
  'Seated Bent-Over Rear Delt Raise': 'Istuen takaolkapään vipunosto kumarrettuna',
  'Seated Bent-Over Two-Arm Dumbbell Triceps Extension': 'Istuen ojentajapunnerrus kumarrettuna käsipainoilla',
  'Seated Biceps': 'Istuen hauiksen venytys',
  'Seated Cable Rows': 'Istuen taljasoutu',
  'Seated Cable Shoulder Press': 'Istuen pystypunnerrus taljassa',
  'Seated Calf Stretch': 'Istuen pohkeen venytys',
  'Seated Close-Grip Concentration Barbell Curl': 'Istuen kapea keskittymiskääntö tangolla',
  'Seated Dumbbell Curl': 'Istuen hauiskääntö käsipainoilla',
  'Seated Dumbbell Inner Biceps Curl': 'Istuen sisemmän hauiksen kääntö käsipainoilla',
  'Seated Dumbbell Palms-Down Wrist Curl': 'Istuen ranteen ojennus käsipainoilla',
  'Seated Dumbbell Palms-Up Wrist Curl': 'Istuen ranteen koukistus käsipainoilla',
  'Seated Flat Bench Leg Pull-In': 'Istuen polvenveto penkillä',
  'Seated Floor Hamstring Stretch': 'Istuen takareiden venytys lattialla',
  'Seated Front Deltoid': 'Istuen etuolkapään venytys',
  'Seated Glute': 'Istuen pakaran venytys',
  'Seated Good Mornings': 'Istuen aamunavaus',
  'Seated Hamstring': 'Istuen takareiden venytys',
  'Seated Hamstring and Calf Stretch': 'Istuen takareiden ja pohkeen venytys',
  'Seated Head Harness Neck Resistance': 'Istuen niskan vastusharjoite valjailla',
  'Seated Leg Tucks': 'Istuen polvenveto',
  'Seated One-arm Cable Pulley Rows': 'Istuen yhden käden taljasoutu',
  'Seated One-Arm Dumbbell Palms-Down Wrist Curl': 'Istuen yhden käden ranteen ojennus käsipainolla',
  'Seated One-Arm Dumbbell Palms-Up Wrist Curl': 'Istuen yhden käden ranteen koukistus käsipainolla',
  'Seated Overhead Stretch': 'Istuen venytys pään yli',
  'Seated Palm-Up Barbell Wrist Curl': 'Istuen ranteen koukistus tangolla',
  'Seated Palms-Down Barbell Wrist Curl': 'Istuen ranteen ojennus tangolla',
  'Seated Side Lateral Raise': 'Istuen sivunosto',
  'Seated Triceps Press': 'Istuen ojentajapunnerrus',
  'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl': 'Istuen ranteen koukistus alataljassa',
  'See-Saw Press (Alternating Side Press)': 'Vuorottainen sivupunnerrus',
  'Shotgun Row': 'Haulikkosoutu taljassa',
  'Shoulder Circles': 'Olkapään pyöritykset',
  'Shoulder Press - With Bands': 'Pystypunnerrus kuminauhoilla',
  'Shoulder Raise': 'Olkapäännosto',
  'Shoulder Stretch': 'Olkapään venytys',
  'Side Bridge': 'Kylkilankku',
  'Side Hop-Sprint': 'Sivuhyppy ja sprintti',
  'Side Jackknife': 'Kyljen linkkuveitsi',
  'Side Laterals to Front Raise': 'Sivunosto etunostoksi',
  'Side Leg Raises': 'Jalannosto sivulle',
  'Side Lying Groin Stretch': 'Nivusen venytys kyljellään',
  'Side Neck Stretch': 'Niskan sivuvenytys',
  'Side Standing Long Jump': 'Pituushyppy sivulle',
  'Side to Side Box Shuffle': 'Sivuttaisaskellus laatikon yli',
  'Side To Side Chins': 'Leuanveto puolelta toiselle',
  'Side Wrist Pull': 'Ranteen sivuveto',
  'Side-Lying Floor Stretch': 'Kyljellään lattiavenytys',
  'Single Dumbbell Raise': 'Nosto yhdellä käsipainolla',
  'Single Leg Butt Kick': 'Yhden jalan kantapotku',
  'Single Leg Glute Bridge': 'Yhden jalan lantionnosto',
  'Single Leg Push-off': 'Yhden jalan ponnistus',
  'Single-Arm Cable Crossover': 'Yhden käden ristikkäisveto taljassa',
  'Single-Arm Linear Jammer': 'Yhden käden landmine-työntö',
  'Single-Arm Push-Up': 'Yhden käden punnerrus',
  'Single-Cone Sprint Drill': 'Yhden kartion sprinttiharjoite',
  'Single-Leg High Box Squat': 'Yhden jalan kyykky korkealle laatikolle',
  'Single-Leg Hop Progression': 'Yhden jalan hyppyprogressio',
  'Single-Leg Lateral Hop': 'Yhden jalan sivuhyppy',
  'Single-Leg Leg Extension': 'Yhden jalan reiden ojennus',
  'Single-Leg Stride Jump': 'Yhden jalan askelhyppy',
  'Sit Squats': 'Istumakyykky',
  'Sit-Up': 'Istumaannousu',
  Skating: 'Luistelu',
  'Sled Drag - Harness': 'Reen veto valjailla',
  'Sled Overhead Backward Walk': 'Reen kävely taaksepäin kädet ylhäällä',
  'Sled Overhead Triceps Extension': 'Ojentajapunnerrus pään yli reellä',
  'Sled Reverse Flye': 'Takaolkapään vipunosto reellä',
  'Sled Row': 'Soutu reellä',
  'Sledgehammer Swings': 'Moukarin lyönnit',
  'Smith Incline Shoulder Raise': 'Olkapäännosto vinopenkillä Smith-laitteessa',
  'Smith Machine Behind the Back Shrug': 'Kohautus takaa Smith-laitteessa',
  'Smith Machine Bench Press': 'Penkkipunnerrus Smith-laitteessa',
  'Smith Machine Bent Over Row': 'Tankosoutu kumarrettuna Smith-laitteessa',
  'Smith Machine Calf Raise': 'Pohjenosto Smith-laitteessa',
  'Smith Machine Close-Grip Bench Press': 'Kapea penkkipunnerrus Smith-laitteessa',
  'Smith Machine Decline Press': 'Laskeva penkkipunnerrus Smith-laitteessa',
  'Smith Machine Hang Power Clean': 'Voimarinnalleveto riipunnasta Smith-laitteessa',
  'Smith Machine Hip Raise': 'Lantionnosto Smith-laitteessa',
  'Smith Machine Incline Bench Press': 'Vinopenkkipunnerrus Smith-laitteessa',
  'Smith Machine Leg Press': 'Jalkaprässi Smith-laitteessa',
  'Smith Machine One-Arm Upright Row': 'Yhden käden pystysoutu Smith-laitteessa',
  'Smith Machine Overhead Shoulder Press': 'Pystypunnerrus Smith-laitteessa',
  'Smith Machine Pistol Squat': 'Pistoolikyykky Smith-laitteessa',
  'Smith Machine Reverse Calf Raises': 'Käänteinen pohjenosto Smith-laitteessa',
  'Smith Machine Squat': 'Kyykky Smith-laitteessa',
  'Smith Machine Stiff-Legged Deadlift': 'Suorin jaloin maastaveto Smith-laitteessa',
  'Smith Machine Upright Row': 'Pystysoutu Smith-laitteessa',
  'Smith Single-Leg Split Squat': 'Yhden jalan askelkyykky Smith-laitteessa',
  Snatch: 'Tempaus',
  'Snatch Balance': 'Tempaustasapaino',
  'Snatch Deadlift': 'Tempauksen maastaveto',
  'Snatch from Blocks': 'Tempaus korokkeilta',
  'Snatch Pull': 'Tempauksen veto',
  'Snatch Shrug': 'Tempauksen kohautus',
  'Speed Band Overhead Triceps': 'Nopeusojentajapunnerrus kuminauhalla pään yli',
  'Speed Box Squat': 'Nopeuslaatikkokyykky',
  'Speed Squats': 'Nopeuskyykky',
  'Spell Caster': 'Spell caster käsipainoilla',
  'Spider Crawl': 'Hämähäkkikävely',
  'Spider Curl': 'Hämähäkkikääntö',
  'Spinal Stretch': 'Selkärangan venytys',
  'Split Clean': 'Askelrinnalleveto',
  'Split Jerk': 'Askeltyöntö',
  'Split Jump': 'Askelhyppy',
  'Split Snatch': 'Askeltempaus',
  // Rear foot elevated, not a step: a different stance from the plain
  // 'Dumbbell Lunges' ("Askelkyykky käsipainoilla") above, which shared this
  // label until the sweep in the recheck round 2026-09-29.
  'Split Squat with Dumbbells': 'Askelkyykky käsipainoilla takajalka koholla',
  'Split Squats': 'Askelkyykky paikallaan',
  'Squat Jerk': 'Kyykkytyöntö',
  'Squat with Bands': 'Kyykky kuminauhoilla',
  'Squat with Chains': 'Kyykky ketjuilla',
  'Squat with Plate Movers': 'Kyykky levypainon siirrolla',
  // Bodyweight, band held in the hands (no bar) — a different exercise from
  // the barbell 'Squat with Bands' above, which shared this label until the
  // sweep in the recheck round 2026-09-29.
  'Squats - With Bands': 'Kehonpainokyykky kuminauhalla',
  Stairmaster: 'Porraskone',
  'Standing Alternating Dumbbell Press': 'Seisten vuorottainen punnerrus käsipainoilla',
  'Standing Barbell Calf Raise': 'Seisten pohjenosto tangolla',
  'Standing Barbell Press Behind Neck': 'Seisten pystypunnerrus niskan takaa',
  'Standing Bent-Over One-Arm Dumbbell Triceps Extension': 'Seisten yhden käden ojentajapunnerrus kumarrettuna',
  'Standing Bent-Over Two-Arm Dumbbell Triceps Extension': 'Seisten ojentajapunnerrus kumarrettuna käsipainoilla',
  'Standing Biceps Cable Curl': 'Seisten hauiskääntö taljassa',
  'Standing Biceps Stretch': 'Seisten hauiksen venytys',
  'Standing Bradford Press': 'Seisten Bradford-punnerrus',
  'Standing Cable Chest Press': 'Seisten rintapunnerrus taljassa',
  'Standing Cable Lift': 'Seisten nosto taljassa',
  'Standing Cable Wood Chop': 'Seisten puunhakkuu taljassa',
  'Standing Calf Raises': 'Seisten pohjenosto',
  'Standing Concentration Curl': 'Seisten keskittymiskääntö',
  'Standing Dumbbell Calf Raise': 'Seisten pohjenosto käsipainoilla',
  'Standing Dumbbell Press': 'Seisten pystypunnerrus käsipainoilla',
  'Standing Dumbbell Reverse Curl': 'Seisten käänteinen kääntö käsipainoilla',
  'Standing Dumbbell Straight-Arm Front Delt Raise Above Head': 'Seisten etunosto suorin käsin pään yli käsipainoilla',
  'Standing Dumbbell Triceps Extension': 'Seisten ojentajapunnerrus käsipainoilla',
  'Standing Dumbbell Upright Row': 'Seisten pystysoutu käsipainoilla',
  'Standing Elevated Quad Stretch': 'Seisten etureiden venytys jalka koholla',
  'Standing Front Barbell Raise Over Head': 'Seisten etunosto tangolla pään yli',
  'Standing Gastrocnemius Calf Stretch': 'Seisten kaksoiskantalihaksen venytys',
  'Standing Hamstring and Calf Stretch': 'Seisten takareiden ja pohkeen venytys',
  'Standing Hip Circles': 'Seisten lonkan pyöritykset',
  'Standing Hip Flexors': 'Seisten lonkankoukistajan venytys',
  'Standing Inner-Biceps Curl': 'Seisten sisemmän hauiksen kääntö',
  'Standing Lateral Stretch': 'Seisten kylkivenytys',
  'Standing Leg Curl': 'Seisten takareisikoukistus',
  'Standing Long Jump': 'Pituushyppy paikaltaan',
  'Standing Low-Pulley Deltoid Raise': 'Seisten olkapäännosto alataljassa',
  'Standing Low-Pulley One-Arm Triceps Extension': 'Seisten yhden käden ojentajapunnerrus alataljassa',
  'Standing Olympic Plate Hand Squeeze': 'Seisten levypainon puristusote',
  'Standing One-Arm Cable Curl': 'Seisten yhden käden hauiskääntö taljassa',
  'Standing One-Arm Dumbbell Curl Over Incline Bench': 'Seisten yhden käden hauiskääntö vinopenkin yli',
  'Standing One-Arm Dumbbell Triceps Extension': 'Seisten yhden käden ojentajapunnerrus käsipainolla',
  'Standing Overhead Barbell Triceps Extension': 'Seisten ojentajapunnerrus tangolla pään yli',
  'Standing Palm-In One-Arm Dumbbell Press': 'Seisten yhden käden punnerrus käsipainolla neutraaliotteella',
  'Standing Palms-In Dumbbell Press': 'Seisten punnerrus käsipainoilla neutraaliotteella',
  'Standing Palms-Up Barbell Behind The Back Wrist Curl': 'Seisten ranteen koukistus tangolla selän takaa',
  'Standing Pelvic Tilt': 'Seisten lantion kallistus',
  'Standing Rope Crunch': 'Seisten vatsarutistus köydellä',
  'Standing Soleus And Achilles Stretch': 'Seisten leveän kantalihaksen ja akillesjänteen venytys',
  'Standing Toe Touches': 'Seisten varpaidenkosketus',
  'Standing Towel Triceps Extension': 'Seisten ojentajapunnerrus pyyhkeellä',
  'Standing Two-Arm Overhead Throw': 'Seisten kahden käden heitto pään yli',
  'Star Jump': 'Tähtihyppy',
  // An actual moving staircase you climb, not the pedal stepper above
  // ('Stairmaster' — its own instructions say "driving the pedals down", vs.
  // this one's "climb the stairs"). Both shared 'Porraskone' until the
  // sweep in the recheck round 2026-09-29.
  'Step Mill': 'Porrasmylly',
  'Stiff Leg Barbell Good Morning': 'Aamunavaus tangolla suorin jaloin',
  'Stiff-Legged Barbell Deadlift': 'Suorin jaloin maastaveto tangolla',
  'Stiff-Legged Dumbbell Deadlift': 'Suorin jaloin maastaveto käsipainoilla',
  'Stomach Vacuum': 'Vatsan sisäänveto',
  'Straight Bar Bench Mid Rows': 'Keskisoutu suoralla tangolla penkiltä',
  'Straight Raises on Incline Bench': 'Suorin käsin nosto vinopenkillä',
  'Straight-Arm Dumbbell Pullover': 'Pullover suorin käsin käsipainolla',
  'Straight-Arm Pulldown': 'Suorin käsin veto alas',
  'Stride Jump Crossover': 'Ristiin askelhyppy',
  'Sumo Deadlift with Bands': 'Sumomaastaveto kuminauhoilla',
  'Sumo Deadlift with Chains': 'Sumomaastaveto ketjuilla',
  Superman: 'Supermies',
  'Supine Chest Throw': 'Rintaheitto selällään',
  'Supine One-Arm Overhead Throw': 'Yhden käden heitto pään yli selällään',
  'Supine Two-Arm Overhead Throw': 'Kahden käden heitto pään yli selällään',
  'Suspended Fallout': 'Vatsarullaus riippukahvoilla',
  'Suspended Push-Up': 'Punnerrus riippukahvoilla',
  'Suspended Reverse Crunch': 'Käänteinen vatsarutistus riippukahvoilla',
  'Suspended Row': 'Soutu riippukahvoilla',
  'Suspended Split Squat': 'Askelkyykky riippukahvoilla',
  'Svend Press': 'Svend-punnerrus',
  'T-Bar Row with Handle': 'T-tankosoutu kahvalla',
  'Tate Press': 'Tate-punnerrus',
  'The Straddle': 'Haara-asennon venytys',
  'Thigh Abductor': 'Reiden loitonnus laitteessa',
  'Thigh Adductor': 'Reiden lähennys laitteessa',
  'Tire Flip': 'Renkaan kääntö',
  'Toe Touchers': 'Varpaidenkosketus',
  'Torso Rotation': 'Vartalon kierto',
  'Tricep Dumbbell Kickback': 'Ojentajapotku käsipainolla',
  'Tricep Side Stretch': 'Ojentajan sivuvenytys',
  'Triceps Overhead Extension with Rope': 'Ojentajapunnerrus pään yli köydellä',
  'Triceps Pushdown - V-Bar Attachment': 'Ojentajapushdown V-kahvalla',
  'Triceps Stretch': 'Ojentajan venytys',
  'Tuck Crunch': 'Koukkuvatsarutistus',
  'Two-Arm Dumbbell Preacher Curl': 'Saarnaajakääntö kahdella käsipainolla',
  'Two-Arm Kettlebell Clean': 'Rinnalleveto kahdella kahvakuulalla',
  'Two-Arm Kettlebell Jerk': 'Työntö kahdella kahvakuulalla',
  'Two-Arm Kettlebell Military Press': 'Pystypunnerrus kahdella kahvakuulalla',
  'Two-Arm Kettlebell Row': 'Soutu kahdella kahvakuulalla',
  'Underhand Cable Pulldowns': 'Ylätalja alaotteella',
  'Upper Back Stretch': 'Yläselän venytys',
  'Upper Back-Leg Grab': 'Yläselän venytys jaloista ottaen',
  'Upright Barbell Row': 'Pystysoutu tangolla',
  'Upright Cable Row': 'Pystysoutu taljassa',
  'Upright Row - With Bands': 'Pystysoutu kuminauhoilla',
  'Upward Stretch': 'Venytys ylöspäin',
  'V-Bar Pulldown': 'Ylätalja V-kahvalla',
  'V-Bar Pullup': 'Leuanveto V-kahvalla',
  'Vertical Swing': 'Pystyheilautus',
  'Walking, Treadmill': 'Kävelymatto',
  'Weighted Ball Hyperextension': 'Selän ojennus jumppapallolla lisäpainolla',
  'Weighted Ball Side Bend': 'Kylkitaivutus jumppapallolla lisäpainolla',
  'Weighted Bench Dip': 'Penkkidippi lisäpainolla',
  'Weighted Crunches': 'Vatsarutistus lisäpainolla',
  'Weighted Jump Squat': 'Hyppykyykky lisäpainolla',
  'Weighted Pull Ups': 'Leuanveto lisäpainolla',
  'Weighted Sissy Squat': 'Sissy-kyykky lisäpainolla',
  'Weighted Sit-Ups - With Bands': 'Istumaannousu kuminauhoilla',
  'Weighted Squat': 'Kyykky lisäpainolla',
  'Wide Stance Barbell Squat': 'Kyykky tangolla leveällä haara-asennolla',
  'Wide Stance Stiff Legs': 'Suorin jaloin maastaveto leveällä haara-asennolla',
  'Wide-Grip Barbell Bench Press': 'Leveä penkkipunnerrus tangolla',
  'Wide-Grip Decline Barbell Bench Press': 'Leveä laskeva penkkipunnerrus tangolla',
  'Wide-Grip Decline Barbell Pullover': 'Leveä laskeva pullover tangolla',
  'Wide-Grip Pulldown Behind The Neck': 'Leveä ylätalja niskan taakse',
  'Wide-Grip Rear Pull-Up': 'Leveä leuanveto niskan taakse',
  'Wide-Grip Standing Barbell Curl': 'Leveä hauiskääntö seisten tangolla',
  'Wind Sprints': 'Vauhtisprintit',
  Windmills: 'Tuulimylly',
  'Wrist Circles': 'Ranteen pyöritykset',
  'Wrist Roller': 'Rannerulla',
  'Wrist Rotations with Straight Bar': 'Ranteen kierrot suoralla tangolla',
  'Yoke Walk': 'Yoke-kävely',
  'Zercher Squats': 'Zercher-kyykky',
  'Zottman Curl': 'Zottman-kääntö',
  'Zottman Preacher Curl': 'Zottman-saarnaajakääntö',
};

/**
 * What a lifter calls the lift, in English.
 *
 * The library ships from a public exercise database, and the database is
 * pedantic where a gym is not: "Barbell Bench Press - Medium Grip" is the
 * bench press, "Barbell Full Squat" is the squat, "Pullups" is a pull-up. The
 * stored English name stays the id — everything matches, filters and swaps on
 * it — and only the label moves, exactly as the Finnish table does.
 *
 * Every entry here is the SAME lift said plainly. That is the whole rule, and
 * it is why this is hand-written rather than inverted out of
 * GUIDED_LIBRARY_ALIASES: that table maps a catalog name onto the nearest
 * library row it can train with, so inverting it would rename Hanging Leg
 * Raise to "hanging knee raise" and Split Squats to "bulgarian split squat" —
 * different exercises wearing each other's names.
 *
 * Covers the lifts a reader meets as a headline first — the ten target lifts
 * and the common barbell and machine work — and grows from there, the same
 * rule the instructions and the Finnish names already follow.
 */
const EXERCISE_NAME_EN: Record<string, string> = {
  // ── The target lifts ─────────────────────────────────────────────────
  // 'Barbell Squat' is already plain and stays as it is: relabelling it
  // "Back Squat" would collide with this row, which is the same lift under
  // a second database name.
  'Barbell Full Squat': 'Back Squat',
  'Front Barbell Squat': 'Front Squat',
  'Barbell Bench Press - Medium Grip': 'Bench Press',
  'Barbell Incline Bench Press - Medium Grip': 'Incline Bench Press',
  'Barbell Deadlift': 'Deadlift',
  'Barbell Hip Thrust': 'Hip Thrust',
  'Bent Over Barbell Row': 'Barbell Row',

  // ── The rest of the main-lift vocabulary ─────────────────────────────
  'Standing Military Press': 'Overhead Press',
  'Side Lateral Raise': 'Lateral Raise',
  'Wide-Grip Lat Pulldown': 'Lat Pulldown',
  Pullups: 'Pull-Up',
  Pushups: 'Push-Up',
  'Weighted Pull Ups': 'Weighted Pull-Up',
  'Seated Cable Rows': 'Seated Cable Row',
  'One-Arm Dumbbell Row': 'Single-Arm Dumbbell Row',
  'Reverse Machine Flyes': 'Reverse Pec Deck',
  'Butt Lift (Bridge)': 'Glute Bridge',
  'Triceps Pushdown - Rope Attachment': 'Rope Pushdown',
  'Leverage Chest Press': 'Machine Chest Press',
};

/** The exercise name as the reader should see it; English is the stored id. */
export function exerciseNameLabel(language: AppLanguage, name: string): string {
  // Every row of every swap sheet goes through here while the reader types,
  // and a stored row with no name threw on `.trim()` — the leading suspect for
  // a crash mid-search that left no log (#bugs 2026-09-27).
  if (typeof name !== 'string') {
    return '';
  }
  const key = name.trim();
  if (language !== 'fi') {
    return EXERCISE_NAME_EN[key] ?? name;
  }
  return EXERCISE_NAME_FI[key] ?? name;
}

/** Exposed for the coverage test — every catalog lift should have an entry. */
export const TRANSLATED_EXERCISE_NAMES = EXERCISE_NAME_FI;

/**
 * Exposed for the sweep that keeps every entry the same lift said plainly.
 *
 * A display name that resolves to a DIFFERENT library row is a rename, not a
 * label, and it would show the reader one exercise under another's name.
 */
export const PLAIN_EXERCISE_NAMES = EXERCISE_NAME_EN;

/**
 * The gym's own short forms, for where a name has a row's width and no more.
 *
 * "Nimet ei kasva niin pitkiksi" (#bugs 2026-09-27): 269 of 860 Finnish names
 * ran past 30 characters, and the equipment words were most of it —
 * käsipainoilla in 39 of them, kahvakuulalla in 25, Smith-laitteessa in 14.
 * The user picked abbreviations ("sopii, tee noin"). Whole words only, so
 * "Käsipainosoutu" keeps its name.
 */
const SHORT_FORMS_FI: ReadonlyArray<readonly [RegExp, string]> = [
  [/(^|\s)käsipain(?:oilla|olla)(?=\s|$)/g, '$1KP'],
  [/(^|\s)kahvakuul(?:illa|alla)(?=\s|$)/g, '$1KK'],
  [/(^|\s)Smith-laitteessa(?=\s|$)/g, '$1Smithissä'],
];

/**
 * The exercise name for a list row or a heading: the label, shortened.
 *
 * Only where the name stands alone. A sentence ("Uusi ennätys: …"), the
 * search, the coach's context and a screen reader's label keep the full
 * `exerciseNameLabel` — "KP" is read once in the exercise sheet's title, not
 * decoded mid-sentence, and a screen reader would spell it out.
 */
export function exerciseListLabel(language: AppLanguage, name: string): string {
  const label = exerciseNameLabel(language, name);
  if (language !== 'fi') {
    return label;
  }
  return SHORT_FORMS_FI.reduce((text, [pattern, short]) => text.replace(pattern, short), label);
}
