import { AppLanguage } from '../types/models';

/**
 * Finnish performance instructions for the exercise library.
 *
 * The library ships from a public English database and is regenerated by
 * `npm run exercise:sync`, so nothing Finnish can live in it — this file is the
 * layer that survives the regeneration, exactly like `EXERCISE_NAME_FI` in
 * exerciseNameLabel.ts. The English name is the key, because the English name
 * is the id everywhere else in this app.
 *
 * COVERAGE. The library holds 873 exercises and 3722 steps. This file covers
 * the ones a reader actually meets inside a program — the lifts the ready
 * catalogs prescribe and that resolve to a library entry — and grows outward
 * from there. Anything not here falls back to the English steps rather than to
 * a blank: an honest English instruction beats a missing one, and it is the
 * same rule the name layer follows.
 *
 * ONE EXCEPTION TO THE BREATHING RULE, ON PURPOSE. Power Clean keeps its
 * "vedä henkeä" and "pidätä hengitystä" steps (user decision, 2026-09-08): in a
 * 24-step technical lift the breath marks where one phase ends and the next
 * begins, which is the opposite of narration. Stomach Vacuum keeps its for the
 * plainer reason that the breath IS the exercise. Do not sweep either out.
 *
 * AND SOMETIMES NOT THE SAME THING. Two cardio entries — the stationary bike
 * and the Stairmaster — describe the machine's menu upstream: manual mode, your
 * age and weight, the calorie estimate. That is not an instruction, and a
 * faithful translation of it is a Finnish reader opening a panel mid-session
 * and getting nothing. Those steps say something useful instead (2026-09-08,
 * user decision). The English still says what it says; this file is an overlay
 * for the Finnish reader, not a mirror.
 *
 * STEP FOR STEP. A Finnish entry has exactly as many steps as the English one.
 * A translation that merges two steps into one loses a number the reader is
 * counting along with, and a test enforces the pairing. The wording is not
 * literal, though: the source database narrates breathing and repeats "This
 * will be your starting position" in almost every entry, and Finnish gym
 * language does not.
 */
const EXERCISE_INSTRUCTIONS_FI: Record<string, string[]> = {
  'Alternating Renegade Row': [
    'Aseta kaksi kahvakuulaa lattialle hartioiden leveydelle. Asetu punnerrusasentoon kuulien kahvojen varaan, vartalo suorana varpaiden ja käsien päällä. Leveämpi jalkojen asento tuo lisää tukea.',
    'Paina toista kuulaa lattiaa vasten ja souda toinen kuula kylkeen. Vedä lapa taakse samalla kun koukistat kyynärpään.',
    'Laske kuula hallitusti alas ja toista liike toisella kädellä. Jatka vuorotellen.',
  ],
  'Arm Circles': [
    'Seiso ryhdikkäästi ja ojenna kädet suoraan sivuille hartioiden korkeudelle, kohtisuoraan vartaloon nähden.',
    'Ala pyörittää käsiä hitaasti noin 30 senttimetrin ympyröissä. Hengitä normaalisti.',
    'Jatka noin kymmenen sekuntia ja vaihda sitten pyörimissuunta.',
  ],
  // Added with the "Arnold Press" alias fix (bug hunt, 2026-10-04): the name used
  // to open the kettlebell version. Five steps, as in the English entry.
  'Arnold Dumbbell Press': [
    'Istu selkänojalliselle penkille ja pidä kahta käsipainoa edessäsi rintakorkeudella kämmenet vartaloa kohti ja kyynärpäät koukussa. Kyynärpäät ovat vartalon vieressä, ja alkuasento näyttää käsipainocurlin yläasennolta.',
    'Nosta käsipainoja ja kierrä samalla kämmeniä, kunnes ne osoittavat eteenpäin.',
    'Jatka nostoa, kunnes kädet ovat suorina pään yläpuolella. Hengitä ulos tämän vaiheen aikana.',
    'Pysähdy hetkeksi ylös ja laske käsipainot takaisin alkuasentoon kiertäen kämmenet takaisin kohti itseäsi. Vasen käsi kiertyy vastapäivään ja oikea myötäpäivään. Hengitä sisään laskun aikana.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Ball Leg Curl': [
    'Asetu selinmakuulle lattialle ja nosta jalat jumppapallon päälle.',
    'Säädä pallon paikka niin, että nilkat ovat pallon päällä jalkojen ollessa suorina.',
    'Nosta lantio irti lattiasta. Paino on lapaluilla ja jalkaterillä.',
    'Koukista polvet ja vedä palloa niin lähelle kuin saat. Purista takareidet kireiksi.',
    'Pidä hetki ja palaa hallitusti alkuasentoon.',
  ],
  'Band Skull Crusher': [
    'Kiinnitä kuminauha telineen tai penkin tyveen. Asetu penkille makuulle niin, että nauha tulee pään takaa.',
    'Ota nauhasta kiinni ja nosta kyynärpäät ylös niin, että olkavarret ovat kohtisuorassa lattiaan nähden. Kyynärpäät koukussa nauha on pään yläpuolella.',
    'Ojenna kyynärpäät suoriksi pitäen olkavarret paikallaan. Pidä hetki ylhäällä ja palaa hallitusti alas.',
  ],
  'Barbell Bench Press - Medium Grip': [
    'Asetu selinmakuulle penkille. Ota tangosta keskileveä ote — sellainen, jossa kyynärvarsi ja olkavarsi ovat liikkeen puolivälissä 90 asteen kulmassa. Nosta tanko telineestä suorille käsille.',
    'Laske tankoa hallitusti alas, kunnes se koskettaa rintaa keskeltä.',
    'Pidä lyhyt tauko ja työnnä tanko takaisin ylös rintalihaksilla. Ojenna kädet suoriksi ja purista rinta kireäksi. Laskuvaihe saa kestää noin kaksi kertaa niin kauan kuin nosto.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Palauta tanko telineeseen sarjan päätteeksi.',
  ],
  'Barbell Curl': [
    'Seiso ryhdikkäästi tanko hartioiden levyisellä otteella, kämmenet eteenpäin ja kyynärpäät lähellä vartaloa.',
    'Pidä olkavarret paikallaan ja käännä tanko ylös hauiksilla. Vain kyynärvarret liikkuvat.',
    'Jatka, kunnes hauikset ovat täysin supistuneet ja tanko on hartioiden korkeudella. Purista sekunnin ajan.',
    'Laske tanko hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Barbell Deadlift': [
    'Asetu seisomaan ladatun tangon taakse.',
    'Pidä selkä suorana, koukista polvet ja taivuta lantiosta eteen. Ota tangosta hartioiden levyinen yliote. Jos ote ei kestä, käytä sekaotetta tai rannelenkkejä.',
    'Aloita nosto työntämällä jaloilla ja suorista vartalo pystyyn. Ylhäällä rinta ulos ja lavat yhteen.',
    'Palaa alas koukistamalla polvia ja taivuttamalla lantiosta selkä suorana. Kun levyt koskettavat lattiaa, olet valmis seuraavaan toistoon.',
    'Tee ohjelman mukainen määrä toistoja.',
  ],
  'Barbell Full Squat': [
    'Tee liike turvallisuuden vuoksi kyykkytelineessä. Aseta tanko hieman hartioiden alapuolelle ja astu tangon alle niin, että se lepää selän yläosassa.',
    'Ota tangosta kiinni molemmin käsin ja nosta se telineestä työntämällä jaloilla ja suoristamalla vartalo.',
    'Astu taaksepäin ja asetu hartioiden levyiseen haara-asentoon varpaat hieman ulospäin. Pidä katse eteenpäin ja selkä suorana.',
    'Laskeudu hitaasti koukistamalla polvia ja työntämällä lantiota taakse. Jatka alas niin syvälle kuin liikkuvuutesi sallii.',
    'Nouse ylös työntämällä kantapäillä ja ojentamalla polvet ja lantio suoriksi.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Barbell Glute Bridge': [
    'Istu lattialle ladattu tanko jalkojen päällä. Tangon pehmuste vähentää painetta lantiolla. Rullaa tanko suoraan lantion päälle ja asetu selinmakuulle.',
    'Aloita liike työntämällä kantapäillä ja ojenna lantio ylös tangon läpi. Paino on yläselällä ja kantapäillä.',
    'Ojenna niin ylös kuin pystyt ja palaa hallitusti alkuasentoon.',
  ],
  'Barbell Hip Thrust': [
    'Istu lattialle penkki selän takana ja ladattu tanko jalkojen päällä. Tangon pehmuste vähentää painetta lantiolla.',
    'Rullaa tanko suoraan lantion päälle ja nojaa penkkiin niin, että lapaluut ovat sen yläreunan kohdalla.',
    'Työnnä jalkaterillä ja ojenna lantio ylös tangon läpi. Paino on lapaluilla ja jalkaterillä. Ojenna niin ylös kuin pystyt ja palaa hallitusti alas.',
  ],
  'Burpee': [
    'Seiso suorassa, laskeudu kyykkyyn ja aseta molemmat kämmenet lattiaan jalkaterien ulkopuolelle.',
    'Hyppää tai kävele jalat taakse punnerrusasentoon, laske rintakehä lattiaan ja punnerra takaisin ylös.',
    'Hyppää jalat takaisin käsien viereen ja nouse hyppyyn kädet ylhäällä. Laskeudu pehmeästi ja jatka suoraan seuraavaan toistoon.',
  ],
  'Kettlebell Swing': [
    'Aseta kahvakuula lattialle noin jalan päähän eteesi, jalat hieman lantiota leveämmällä. Työnnä lantio taakse selkä suorana ja ota kahvasta molemmin käsin.',
    'Heilauta kuula jalkojen välistä taakse ja ojenna lantio räjähtävästi eteen. Kädet vain ohjaavat — työn tekee lantio, ja kuula nousee itsestään rintakehän korkeudelle.',
    'Anna kuulan pudota takaisin jalkojen väliin lantio taakse työntäen ja jatka suoraan seuraavaan toistoon. Selkä pysyy suorana ensimmäisestä toistosta viimeiseen.',
  ],
  'Band Curl': [
    'Seiso kuminauhan keskellä jalat noin lantion leveydellä ja ota kummastakin päästä kiinni, kädet suorina ja kämmenet eteenpäin.',
    'Pidä kyynärpäät kyljissä ja koukista kädet kohti olkapäitä. Purista hauis tiukaksi yläasennossa.',
    'Laske hitaasti nauhaa vastaan, kunnes kädet ovat taas suorat. Seiso nauhalla leveämmin, jos haluat enemmän vastusta, ja kapeammin, jos vähemmän.',
  ],
  'Bodyweight Calf Raise': [
    'Seiso ryhdikkäästi jalat lantion leveydellä ja varpaat eteenpäin. Ota tukea seinästä tai kaiteesta, jos tarvitset. Käsipainot käsissä ovat valinnaiset: käytä niitä, jos ohjelmasi kirjaa painon, muuten riittää oma kehonpaino.',
    'Nouse varpaille niin korkealle kuin pystyt, polvet suorina mutta ei lukittuina, ja pysähdy hetkeksi ylös.',
    'Laske kantapäät hitaasti lattian tasolle tai hieman sen alle, jos seisot askelmalla, ja jatka suoraan seuraavaan toistoon.',
  ],
  'Single-Leg Calf Raise': [
    'Seiso yhdellä jalalla, toinen jalka irti lattiasta tai nilkan taakse koukistettuna. Ota tukea seinästä tai kaiteesta. Käsipaino vapaassa kädessä on valinnainen: käytä sitä, jos ohjelmasi kirjaa painon, muuten riittää oma kehonpaino.',
    'Nouse seisovan jalan päkiälle niin korkealle kuin pystyt, polvi suorana mutta ei lukittuna, ja pysähdy hetkeksi ylös.',
    'Laske kantapää hitaasti lattian tasolle tai hieman sen alle, jos seisot askelmalla, ja jatka suoraan seuraavaan toistoon. Tee kaikki toistot yhdellä jalalla ja vaihda sitten.',
  ],
  'Machine Hip Thrust': [
    'Asetu laitteeseen selkä tukea vasten ja lantiotyyny tai -tanko lantion päälle, aivan lonkkaluiden alapuolelle.',
    'Säädä istuin niin, että sääret ovat pystysuorassa liikkeen yläasennossa, ja työnnä kantapäillä lantio ylös.',
    'Purista pakarat yläasennossa ilman että alaselkä notkahtaa, ja laske hallitusti alas niin että paino ei jää lepäämään.',
  ],
  'Barbell Incline Bench Press - Medium Grip': [
    'Asetu selinmakuulle vinopenkkiin. Ota tangosta keskileveä ote ja nosta se telineestä suorille käsille.',
    'Laske tankoa hallitusti alas, kunnes se koskettaa ylärintaa.',
    'Pidä sekunnin tauko ja työnnä tanko takaisin ylös rintalihaksilla. Purista rinta kireäksi ylhäällä. Laskuvaihe saa kestää vähintään kaksi kertaa noston verran.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Palauta tanko telineeseen sarjan päätteeksi.',
  ],
  'Barbell Walking Lunge': [
    'Seiso jalat hartioiden leveydellä ja tanko yläselän päällä.',
    'Astu toisella jalalla eteen ja laskeudu koukistamalla polvia, kunnes takapolvi lähes koskettaa lattiaa. Pidä ryhti pystynä ja etupolvi jalkaterän yläpuolella.',
    'Työnnä etujalan kantapäällä ja nouse ylös ojentamalla molemmat polvet.',
    'Astu takajalalla eteen ja toista askelkyykky toisella jalalla.',
  ],
  'Battling Ropes': [
    'Tarvitset paksun köyden, joka on ankkuroitu keskeltä noin viiden metrin päähän. Seiso köyden edessä pää kummassakin kädessä, kädet suorina sivuilla.',
    'Aloita nostamalla toinen käsi nopeasti hartioiden korkeudelle.',
    'Kun käsi laskeutuu alas, nosta toinen käsi ylös.',
    'Jatka vuorotellen ja piiskaa köysiä ylös ja alas niin nopeasti kuin pystyt.',
  ],
  'Bench Press - Powerlifting': [
    'Asetu penkille niin, että pää on tangon takana. Vedä jalat vartalon alle ja kaarra selkää. Nosta lavat irti penkistä ja purista ne yhteen. Työnnä jaloilla epäkäslihakset penkkiä vasten ja pidä keho tiukkana koko liikkeen ajan.',
    'Olipa ote miten leveä tahansa, sen tulee peittää tangon merkkirengas. Vedä tanko telineestä lapoja irrottamatta. Purista tankoa ja yritä repiä sitä auki.',
    'Laske tanko alarinnalle tai ylävatsalle. Tangon, ranteen ja kyynärpään tulee pysyä samassa linjassa.',
    'Pidä tauko tangon koskettaessa vartaloa ja työnnä sitten ylös niin voimakkaasti kuin pystyt. Kyynärpäät pysyvät lähellä vartaloa lukkoon asti.',
  ],
  'Bent Over Barbell Row': [
    'Ota tangosta yliote, koukista polvia hieman ja taivuta ylävartalo lantiosta lähes vaakatasoon selkä suorana. Pidä katse eteenpäin. Tanko roikkuu suoraan edessäsi kädet suorina.',
    'Pidä ylävartalo paikallaan ja vedä tanko vartaloa kohti. Kyynärpäät kulkevat lähellä kylkiä. Purista selkälihakset ylhäällä yhteen.',
    'Laske tanko hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Bodyweight Squat': [
    'Seiso jalat hartioiden leveydellä. Voit pitää kädet niskan takana.',
    'Aloita liike koukistamalla polvia ja työntämällä lantiota taakse.',
    'Laskeudu niin syvälle kuin liikkuvuutesi sallii ja nouse nopeasti takaisin ylös. Pidä rinta ylhäällä ja polvet ulospäin.',
  ],
  'Bodyweight Walking Lunge': [
    'Seiso jalat hartioiden leveydellä kädet lantiolla.',
    'Astu toisella jalalla eteen ja laskeudu koukistamalla polvia, kunnes takapolvi lähes koskettaa lattiaa. Pidä ryhti pystynä ja etupolvi jalkaterän yläpuolella.',
    'Työnnä etujalan kantapäällä ja nouse ylös ojentamalla molemmat polvet.',
    'Astu takajalalla eteen ja toista askelkyykky toisella jalalla.',
  ],
  'Box Squat': [
    'Laatikkokyykyssä voit kyykätä haluamaasi syvyyteen ja kehittää räjähtävää voimaa. Asetu telineeseen laatikko takanasi sopivalla korkeudella. Tavallisesti laatikko on sellainen, että kyykky tulee vaakatasoon, mutta voit harjoitella myös korkeammalta tai matalammalta.',
    'Astu tangon alle ja aseta se yläselän päälle. Purista lavat yhteen ja kierrä kyynärpäät eteen, ikään kuin taivuttaisit tankoa hartioidesi päällä. Nosta tanko telineestä, jännitä alaselkä notkolle ja astu taakse. Leveämpi asento painottaa selkää, pakaroita ja takareisiä, kapeampi etureisiä. Katse eteenpäin.',
    'Pidä selkä, hartiat ja keskivartalo tiukkana ja työnnä polvia ja lantiota ulospäin laskeutuessasi. Istu lantio edellä alas laatikolle. Sääret ovat mieluiten kohtisuorassa lattiaan nähden. Pysähdy laatikolle ja rentouta lonkankoukistajat. Älä koskaan pompi laatikolta.',
    'Pidä paino kantapäillä, työnnä jalkateriä ja polvia ulos ja nouse laatikolta pää edellä. Jatka ylös pitäen koko keho tiukkana.',
  ],
  'Cable Crossover': [
    'Aseta taljojen väkipyörät yläasentoon pään yläpuolelle, valitse vastus ja ota kahvat käsiin.',
    'Astu eteenpäin taljojen välissä ja vedä kädet yhteen eteesi. Ylävartalo nojaa hieman eteen.',
    'Pidä kyynärpäissä kevyt koukku ja avaa kädet sivuille laajassa kaaressa, kunnes tunnet venytyksen rinnassa. Kädet ja ylävartalo pysyvät muuten paikallaan — liike tapahtuu vain olkanivelestä.',
    'Palauta kädet takaisin yhteen samaa kaarta pitkin.',
    'Pidä hetki alkuasennossa ja toista ohjelman mukainen määrä toistoja.',
  ],
  'Cable Crunch': [
    'Asetu polvilleen ylätaljan alle, jossa on naruvedin.',
    'Ota narusta kiinni ja vedä se kasvojen viereen.',
    'Koukista lantiota hieman ja anna painon venyttää alaselkää kevyesti.',
    'Pidä lantio paikallaan ja koukista ylävartaloa vatsalihaksilla niin, että kyynärpäät kulkevat kohti reisiä. Purista supistus sekunnin ajan.',
    'Palaa hitaasti alkuasentoon. Pidä vatsalihakset jännityksessä koko ajan äläkä valitse niin raskasta painoa, että alaselkä tekee työn.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Cable Hammer Curls - Rope Attachment': [
    'Kiinnitä naruvedin alataljaan ja seiso noin 30 senttimetrin päässä laitteesta.',
    'Ota narusta neutraali ote kämmenet vastakkain ja seiso ryhdikkäästi ylävartalo paikallaan.',
    'Pidä kyynärpäät kylkiä vasten koko liikkeen ajan. Vain kyynärvarret liikkuvat.',
    'Käännä kädet ylös hauiksilla, kunnes hauis ja kyynärvarsi koskettavat. Kyynärpäät ja olkavarret pysyvät paikallaan.',
    'Purista sekunnin ajan ja laske paino hitaasti takaisin.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Cable Rear Delt Fly': [
    'Säädä taljat pään yläpuolelle ja valitse vastus.',
    'Ota vasen kahva oikeaan käteen ja oikea kahva vasempaan, kädet ristissä edessäsi.',
    'Vie kädet taakse ja ulospäin pitäen ne suorina koko liikkeen ajan.',
    'Pidä tauko liikkeen lopussa ja palauta kahvat hallitusti alkuasentoon.',
  ],
  'Cable Seated Lateral Raise': [
    'Asetu kahden vastakkaisen alataljan väliin ja aseta penkki taaksesi poikittain. Valitse vastus molempiin taljoihin.',
    'Istu penkin reunalle jalat polvien edessä.',
    'Taivuta ylävartalo eteen selkä suorana ja lepuuta rintakehä reisiä vasten.',
    'Ota kahvat käsiin ristikkäin: vasen talja oikeaan käteen ja oikea talja vasempaan. Vaijerit kulkevat polvien alta, kädet ovat lähes suorina kämmenet vastakkain.',
    'Pidä kädet suorina ja nosta olkavarret sivuille hartioiden korkeudelle. Purista supistus sekunnin ajan.',
    'Laske kädet hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja. Pidä olkavarret kohtisuorassa vartaloon nähden ja kyynärpäissä sama kevyt koukku koko liikkeen ajan.',
  ],
  'Cable Wrist Curl': [
    'Aseta penkki alataljan eteen ja kiinnitä taljaan suora tanko.',
    'Ota tangosta hartioiden levyinen alaote kämmenet ylöspäin ja aseta kyynärvarret reisien päälle. Ranteet jäävät roikkumaan polvien ulkopuolelle.',
    'Käännä ranteita ylöspäin ja pidä supistus sekunnin ajan.',
    'Laske ranteet hitaasti takaisin alas.',
    'Kyynärvarret pysyvät paikallaan — vain ranteet liikkuvat.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Cat Stretch': [
    'Asetu lattialle konttausasentoon käsien ja polvien varaan.',
    'Vedä vatsa sisään ja pyöristä selkäranka, alaselkä, hartiat ja niska. Anna pään pudota rennosti alas.',
    'Pidä asento 15 sekuntia.',
  ],
  "Child's Pose": [
    'Asetu konttausasentoon ja kävele kädet eteen.',
    'Laske pakarat kantapäiden päälle. Anna käsien liukua lattiaa pitkin, jolloin koko selkäranka venyy.',
    'Kun istut kantapäillä, tuo kädet jalkojen viereen ja rentoudu. Hengitä selkään ja lepuuta otsaa lattiaa vasten. Vältä asentoa, jos polvesi eivät kestä sitä.',
  ],
  'Chin-Up': [
    'Ota leukatangosta alaote hartioita kapeammalta, kämmenet itseäsi kohti.',
    'Roiku suorilla käsillä ylävartalo mahdollisimman suorana, alaselkä kevyessä notkossa ja rinta ulos. Suora ylävartalo painottaa hauista ja rajaa selän työtä.',
    'Vedä itsesi ylös, kunnes pää on tangon tasolla. Keskity vetämään hauiksilla ja pidä kyynärpäät lähellä vartaloa. Vain kädet tekevät työn.',
    'Purista hauikset sekunnin ajan ja laskeudu hitaasti takaisin suorille käsille.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  'Crossover Reverse Lunge': [
    'Seiso jalat hartioiden leveydellä.',
    'Astu toisella jalalla taakse ja laskeudu koukistamalla lantiota ja etupolvea. Kierrä samalla ylävartaloa etujalan yli.',
    'Pidä lyhyt tauko, palaa alkuasentoon ja toista toiselle puolelle. Jatka vuorotellen.',
  ],
  'Dead Bug': [
    'Asetu selinmakuulle kädet suoraan ylös kohti kattoa.',
    'Nosta jalat ilmaan niin, että lantio ja polvet ovat 90 asteen kulmassa.',
    'Puhalla ilmat ulos, laske kylkiluut alas ja paina alaselkä lattiaa vasten. Kallista lantiota ylös ja purista pakarat. Pidä tämä asento koko liikkeen ajan.',
    'Aloita ojentamalla toinen jalka suoraksi lattian yläpuolelle.',
    'Pidä alaselkä ja lantio paikallaan koko ajan — selkä pyrkii notkolle.',
    'Pysy tiukkana ja tuo jalka takaisin alkuasentoon.',
    'Toista toisella puolella ja jatka vuorotellen sarjan loppuun.',
  ],
  'Decline Barbell Bench Press': [
    'Kiinnitä jalat laskevan penkin päähän ja asetu hitaasti makuulle.',
    'Ota tangosta keskileveä ote ja nosta se telineestä suorille käsille kohtisuoraan lattiaan nähden. Avustaja tangon irrotuksessa säästää olkapäitä.',
    'Laske tankoa hallitusti alas, kunnes se koskettaa alarintaa.',
    'Pidä sekunnin tauko ja työnnä tanko ylös rintalihaksilla. Ojenna kädet ja purista rinta kireäksi. Laskuvaihe saa kestää vähintään kaksi kertaa noston verran.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Palauta tanko telineeseen sarjan päätteeksi.',
  ],
  'Deficit Deadlift': [
    'Ota koroke tai levyt, joiden päällä seisot — tavallisesti 3–8 senttimetriä. Asetu tangon taakse niin, että se on jalkaterien keskikohdan päällä, jalat lantion leveydellä. Taivuta lantiosta ja ota tangosta hartioiden levyinen ote. Käytä yliotetta tai raskaissa sarjoissa sekaotetta.',
    'Kun jalat ja ote ovat paikallaan, vedä henkeä, laske lantiota ja koukista polvia, kunnes sääret koskettavat tankoa. Katse eteen, rinta ylös ja selkä kevyessä notkossa. Työnnä kantapäillä ja aloita nosto. Kun tanko ohittaa polvet, vedä lavat yhteen ja työnnä lantio tankoa vasten.',
    'Laske tanko alas taivuttamalla lantiosta ja ohjaa se hallitusti lattiaan.',
  ],
  'Dumbbell Bench Press': [
    'Asetu selinmakuulle penkille käsipainot reisien päällä, kämmenet vastakkain.',
    'Auta reisillä ja nosta käsipainot yksi kerrallaan hartioiden leveydelle eteesi.',
    'Käännä ranteet niin, että kämmenet osoittavat eteenpäin. Painot ovat rintakehän sivuilla, olkavarsi ja kyynärvarsi 90 asteen kulmassa. Pidä painot hallinnassa koko ajan.',
    'Työnnä painot ylös rintalihaksilla. Ojenna kädet ylhäällä ja purista rinta kireäksi sekunnin ajan, laske sitten hitaasti alas. Laskuvaihe saa kestää noin kaksi kertaa noston verran.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  'Dumbbell Bicep Curl': [
    'Seiso ryhdikkäästi käsipainot suorilla käsillä. Pidä kyynärpäät lähellä vartaloa ja käännä kämmenet eteenpäin.',
    'Pidä olkavarret paikallaan ja käännä painot ylös hauiksilla. Jatka, kunnes hauikset ovat täysin supistuneet ja painot ovat hartioiden korkeudella. Purista hetken ajan.',
    'Laske painot hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Dumbbell Floor Press': [
    'Asetu selinmakuulle lattialle käsipainot käsissä. Polvet voivat olla koukussa. Aloita painot suorilla käsillä ylhäällä.',
    'Laske painoja, kunnes olkavarret koskettavat lattiaa. Kyynärpäät lähellä kylkiä painottaa ojentajia, sivummalla rintaa.',
    'Pidä tauko alhaalla ja työnnä painot ylös ojentamalla kyynärpäät suoriksi.',
  ],
  'Dumbbell Flyes': [
    'Asetu selinmakuulle penkille käsipainot reisien päällä, kämmenet vastakkain.',
    'Auta reisillä ja nosta painot hartioiden leveydelle eteesi kämmenet vastakkain. Nosta kuin punnertaisit, mutta pysähdy juuri ennen lukkoa.',
    'Pidä kyynärpäissä kevyt koukku ja laske kädet sivuille laajassa kaaressa, kunnes tunnet venytyksen rinnassa. Kädet pysyvät muuten paikallaan — liike tapahtuu vain olkanivelestä.',
    'Palauta kädet takaisin ylös puristamalla rintalihakset yhteen. Käytä samaa kaarta kuin laskiessa.',
    'Pidä sekunti ylhäällä ja toista ohjelman mukainen määrä toistoja.',
  ],
  'Dumbbell Incline Row': [
    'Nojaa vinopenkkiä vasten rinta edellä.',
    'Ota käsipainot neutraalilla otteella, kädet suorina alaspäin.',
    'Vedä lavat taakse ja koukista kyynärpäitä soutaen painot kylkiin.',
    'Pidä tauko ylhäällä ja laske hallitusti takaisin alas.',
  ],
  'Dumbbell Rear Lunge': [
    'Seiso ryhdikkäästi käsipainot käsissä vartalon sivuilla.',
    'Astu oikealla jalalla noin puoli metriä taakse ja laskeudu alas ylävartalo pystyssä. Älä anna etupolven ohittaa varpaita ja pidä etusääri kohtisuorassa lattiaan nähden. Pitkä askel painottaa pakaroita, lyhyt etureisiä.',
    'Työnnä itsesi takaisin alkuasentoon. Päkiällä työntäminen painottaa etureisiä, kantapäällä pakaroita.',
    'Toista toisella jalalla.',
  ],
  'Dumbbell Shoulder Press': [
    'Istu selkänojalliselle penkille käsipainot pystyssä reisien päällä.',
    'Nosta painot hartioiden korkeudelle yksi kerrallaan reisien avulla.',
    'Käännä ranteet niin, että kämmenet osoittavat eteenpäin.',
    'Työnnä painot ylös, kunnes ne koskettavat toisiaan ylhäällä.',
    'Pidä lyhyt tauko ylhäällä ja laske painot hitaasti takaisin alas.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Dynamic Back Stretch': [
    'Seiso jalat hartioiden leveydellä.',
    'Heiluta suoria käsiä eteen ja ylös 5–10 kertaa. Kasvata liikerataa joka kerralla, kunnes kädet nousevat pään yläpuolelle.',
  ],
  'Face Pull': [
    'Asetu ylätaljan eteen naru tai kaksoiskahvat kiinnitettynä. Vedä paino suoraan kohti kasvoja ja erota kädet vedon aikana. Pidä olkavarret vaakatasossa.',
  ],
  "Farmer's Walk": [
    'Farmarikävelyyn käy moni väline: raskaat käsipainot tai lyhyet tangot ajavat saman asian. Asetu seisomaan välineiden väliin.',
    'Ota kahvoista kiinni ja nouse ylös työntämällä kantapäillä. Selkä suorana ja katse eteenpäin.',
    'Kävele lyhyin, nopein askelin äläkä pidätä hengitystä. Kulje sovittu matka, tavallisesti 15–30 metriä, niin nopeasti kuin pystyt.',
  ],
  'Freehand Jump Squat': [
    'Vie kädet ristiin rinnan päälle.',
    'Pidä katse eteenpäin ja selkä suorana, jalat hartioiden leveydellä.',
    'Kyykkää alas selkä suorana ja rinta ylhäällä, kunnes reidet ovat vaakatasossa tai alempana.',
    'Ponnista päkiöillä suoraan ylös niin korkealle kuin pystyt. Käytä reisiä jousina.',
    'Kun osut lattiaan, kyykkää heti alas ja hyppää uudelleen.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Front Barbell Squat': [
    'Tee liike turvallisuuden vuoksi kyykkytelineessä. Aseta tanko oman pituutesi mukaiselle korkeudelle. Tuo kädet tangon alle kyynärpäät korkealla ja olkavarret hieman vaakatason yläpuolella. Anna tangon levätä olkapäiden päällä ja ristiä kädet sen päälle.',
    'Nosta tanko telineestä työntämällä jaloilla ja suoristamalla vartalo.',
    'Astu taaksepäin ja asetu hartioiden levyiseen haara-asentoon varpaat hieman ulospäin. Pidä katse eteenpäin — alas katsominen vie tasapainon — ja selkä suorana.',
    'Laskeudu hitaasti koukistamalla polvia ryhti pystyssä. Jatka, kunnes reidet ovat hieman vaakatason alapuolella. Oikein tehtynä polvet piirtävät kuvitteellisen suoran linjan varpaiden kanssa; jos polvet ohittavat varpaat, liike kuormittaa polvea väärin.',
    'Nouse ylös työntämällä jalkaterän keskiosalla ja ojentamalla jalat suoriksi.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Front Box Jump': [
    'Aseta sopivan korkuinen laatikko noin puolen metrin päähän eteesi ja seiso jalat hartioiden leveydellä.',
    'Tee lyhyt kyykky hyppyä varten ja heilauta kädet taakse.',
    'Ponnista ylös ojentamalla lantio, polvet ja nilkat. Heilauta kädet eteen ja ylös.',
    'Laskeudu laatikolle polvet joustaen. Voit hypätä laatikolta alas, mutta parempi on astua alas jalka kerrallaan.',
  ],
  'Front Cable Raise': [
    'Valitse vastus alataljaan ja ota yksittäinen kahva vasempaan käteen.',
    'Käänny poispäin taljasta ja pidä käsi suorana alhaalla reiden edessä kämmen reittä kohti.',
    'Pidä ylävartalo paikallaan — ei heilautusta — ja nosta vasen käsi eteen kevyt koukku kyynärpäässä, kämmen alaspäin. Jatka, kunnes käsi on hieman vaakatason yläpuolella. Pidä sekunti ylhäällä.',
    'Laske käsi hitaasti takaisin alkuasentoon.',
    'Kun olet tehnyt suositellut toistot tällä kädellä, vaihda oikeaan.',
  ],
  'Glute Ham Raise': [
    'Säädä laite mittoihisi. Asetu vatsalleen jalat tukilevyä vasten rullien väliin. Polvet jäävät juuri pehmusteen taakse.',
    'Aloita alhaalta. Pidä selkä kevyessä notkossa ja koukista polvia työntäen samalla varpailla tukilevyä. Pidä ylävartalo suorana ja jatka, kunnes olet pystyasennossa.',
    'Palaa alkuasentoon hallitusti.',
  ],
  'Goblet Squat': [
    'Seiso kevyt kahvakuula sarvista tai käsipaino pystyssä rintaa vasten.',
    'Kyykkää alas jalkojen väliin niin syvälle kuin liikkuvuutesi sallii. Pidä rinta ja katse ylhäällä ja selkä suorana.',
    'Pysähdy alhaalla ja työnnä kyynärpäillä polvia ulospäin. Nouse ylös ja toista 10–20 toistoa.',
  ],
  'Good Morning': [
    'Aseta tanko telineeseen hartioiden korkeudelle. Aseta se yläselän päälle kuten kyykyssä, ei niskan päälle. Pidä selkä jännitettynä, lavat yhdessä ja polvet kevyesti koukussa. Astu telineestä taakse.',
    'Taivuta lantiosta ja työnnä sitä taakse, kunnes ylävartalo on lähes vaakatasossa. Pidä selkä kevyessä notkossa ja niska selkärangan jatkeena.',
    'Palaa ylös ojentamalla lantio pakaroilla ja takareisillä. Jatka, kunnes olet takaisin pystyasennossa.',
  ],
  'Hack Squat': [
    'Asetu laitteeseen selkä tukea vasten ja hartiat pehmusteiden alle.',
    'Aseta jalat levylle hartioiden levyiseen asentoon varpaat hieman ulospäin. Pidä katse eteenpäin ja selkä tukea vasten koko ajan.',
    'Ota kiinni sivukahvoista ja vapauta turvatuet kääntämällä kahvat sivuasentoon.',
    'Ojenna jalat suoriksi lukitsematta polvia.',
    'Laskeudu hitaasti koukistamalla polvia ryhti pystyssä ja selkä tukea vasten. Jatka, kunnes reidet ovat hieman vaakatason alapuolella. Oikein tehtynä polvet eivät ohita varpaita.',
    'Nouse ylös työntämällä kantapäillä ja ojentamalla jalat suoriksi.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Hammer Curls': [
    'Seiso ryhdikkäästi käsipainot suorilla käsillä, kyynärpäät lähellä vartaloa.',
    'Kämmenet osoittavat vartaloa kohti.',
    'Pidä olkavarret paikallaan ja käännä paino ylös hauiksella. Jatka, kunnes hauis on täysin supistunut ja paino on hartian korkeudella. Purista hetken ajan. Vain kyynärvarsi liikkuu.',
    'Laske painot hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Hanging Leg Raise': [
    'Roiku leukatangossa suorilla käsillä leveällä tai keskileveällä otteella. Jalat ovat suorina alhaalla ja lantio hieman taaksepäin kallistettuna.',
    'Nosta jalat ylös, kunnes ylävartalo ja jalat ovat 90 asteen kulmassa. Pidä supistus hetken ajan.',
    'Laske jalat hitaasti takaisin alas.',
    'Toista suositeltu määrä toistoja.',
  ],
  'High Cable Curls': [
    'Seiso kahden ylätaljan välissä kahva kummassakin kädessä. Aseta olkavarret vaakatasoon kämmenet itseäsi kohti.',
    'Käännä kahvat korvien viereen ja purista hauikset. Olkavarret pysyvät paikallaan, vain kyynärvarret liikkuvat. Pidä sekunti supistuksessa.',
    'Palauta kädet hitaasti alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Hip Circles (prone)': [
    'Asetu konttausasentoon käsien ja polvien varaan. Pidä ryhti hyvänä ja nosta toinen koukussa oleva polvi irti lattiasta.',
    'Pidä polvi koukussa ja kierrä reisiluuta kaaressa, ikään kuin piirtäisit polvella suuren ympyrän.',
    'Tee liike hitaasti muutaman toiston ajan ja toista toisella jalalla.',
  ],
  Inchworm: [
    'Seiso jalat vierekkäin. Pidä jalat suorina, taivuta eteen ja aseta kädet lattialle suoraan eteesi.',
    'Kävele käsillä hitaasti eteenpäin vuorotellen vasenta ja oikeaa. Taivuta vain lantiosta ja pidä jalat suorina.',
    'Jatka, kunnes vartalo on punnerrusasennossa lattian suuntaisesti.',
    'Pidä kädet paikallaan ja ota jaloilla lyhyitä askelia, muutama sentti kerrallaan.',
    'Jatka kävelyä, kunnes jalat ovat käsien vieressä. Pidä jalat suorina koko ajan.',
  ],
  'Incline Cable Flye': [
    'Aseta taljojen väkipyörät alimpaan asentoon, vartalosi alapuolelle.',
    'Aseta 45 asteen vinopenkki taljojen väliin, valitse vastus molempiin ja ota kahva kumpaankin käteen.',
    'Asetu vinopenkille kahvat käsissä ja tuo kädet yhteen suorina kasvojen yläpuolelle.',
    'Pidä kyynärpäissä kevyt koukku ja laske kädet sivuille laajassa kaaressa, kunnes tunnet venytyksen rinnassa. Kädet pysyvät muuten paikallaan — liike tapahtuu vain olkanivelestä.',
    'Palauta kädet takaisin yhteen puristamalla rintalihakset. Pidä sekunti supistuksessa ja käytä samaa kaarta kuin laskiessa.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  'Incline Dumbbell Curl': [
    'Istu vinopenkille käsipainot suorilla käsillä. Pidä kyynärpäät lähellä vartaloa ja käännä kämmenet eteenpäin.',
    'Pidä olkavarret paikallaan ja käännä painot ylös hauiksilla. Vain kyynärvarret liikkuvat. Jatka, kunnes hauikset ovat täysin supistuneet ja painot ovat hartioiden korkeudella. Pidä sekunti supistuksessa.',
    'Laske painot hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Incline Dumbbell Press': [
    'Asetu vinopenkkiin käsipainot reisien päällä, kämmenet vastakkain.',
    'Auta reisillä ja nosta painot yksi kerrallaan hartioiden leveydelle.',
    'Käännä ranteet niin, että kämmenet osoittavat eteenpäin.',
    'Pidä painot hallinnassa koko ajan ja työnnä ne ylös rintalihaksilla.',
    'Ojenna kädet ylhäällä, pidä sekunti ja ala laskea hitaasti alas. Laskuvaihe saa kestää noin kaksi kertaa noston verran.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Laske painot lopuksi ensin reisille ja sitten lattialle. Se on turvallisin tapa päästää niistä irti.',
  ],
  'Incline Push-Up': [
    'Asetu penkin tai muun tukevan korokkeen eteen. Aseta kädet sen reunalle hieman hartioita leveämmälle.',
    'Vie jalat taakse niin, että kädet ja vartalo ovat suorina ja kädet kohtisuorassa vartaloon nähden. Pidä vartalo suorana ja laske rinta korokkeen reunaan koukistamalla käsiä.',
    'Työnnä itsesi ylös, kunnes kädet ovat suorina. Toista.',
  ],
  'Intermediate Hip Flexor and Quad Stretch': [
    'Asetu vatsalleen lattialle naru, vyö tai kuminauha toisen jalkaterän ympärillä.',
    'Koukista polvea ja ojenna lonkkaa venytettävästä jalasta vetämällä nauhasta molemmin käsin. Polven ja lonkan tulee nousta irti lattiasta, jolloin lonkankoukistaja ja etureisi venyvät. Pidä venytys 10–20 sekuntia ja toista toisella jalalla.',
  ],
  'Inverted Row': [
    'Aseta tanko telineeseen noin vyötärön korkeudelle. Voit käyttää myös smith-laitetta.',
    'Ota tangosta hartioita leveämpi ote ja asetu roikkumaan tangon alle. Vartalo on suorana, kantapäät lattiassa ja kädet suorina.',
    'Vedä rintaa kohti tankoa koukistamalla kyynärpäitä. Vedä lavat yhteen liikkeen aikana.',
    'Pidä tauko ylhäällä ja laskeudu takaisin alkuasentoon.',
    'Toista haluttu määrä toistoja.',
  ],
  'IT Band and Glute Stretch': [
    'Pujota vyö, naru tai kuminauha toisen jalkaterän ympäri ja heilauta jalka vartalon yli vastakkaiselle puolelle. Jalka pysyy suorana ja makaat selälläsi.',
    'Pidä jalka irti lattiasta ja vedä nauhasta niin, että varpaat nousevat kohti sinua. Pidä 10–20 sekuntia ja toista toisella puolella.',
  ],
  'Kettlebell Arnold Press': [
    'Nosta kahvakuula olkapäälle. Nosto tapahtuu ojentamalla jalat ja lantio samalla kun kuula nousee olkapäätä kohti. Kämmen osoittaa sisäänpäin.',
    'Katse eteenpäin, työnnä kuula ylös pään yläpuolelle ja kierrä rannetta niin, että kämmen osoittaa ylhäällä eteenpäin.',
    'Palauta kuula alkuasentoon kämmen sisäänpäin.',
  ],
  'Kettlebell Thruster': [
    'Nosta kaksi kahvakuulaa olkapäille ojentamalla jalat ja lantio samalla kun vedät kuulat ylös. Kierrä ranteet noston aikana.',
    'Kyykkää alas koukistamalla lantiota ja polvia. Pidä ylävartalo pystyssä ja laskeudu niin syvälle kuin pystyt.',
    'Nouse alhaalta ojentamalla polvet ja lantio ja työntämällä kantapäillä. Työnnä samalla molemmat kuulat suorille käsille pään yläpuolelle ja käytä kyykyn vauhtia apuna.',
    'Palauta kuulat olkapäille seuraavaa toistoa varten.',
  ],
  'Kneeling Hip Flexor': [
    'Asetu polvilleen alustalle ja nosta oikea polvi eteen niin, että jalkaterä on lattiassa. Ojenna vasen jalka taakse jalkapöytä lattiaa vasten.',
    'Siirrä painoa eteenpäin, kunnes tunnet venytyksen lonkassa. Pidä 15 sekuntia ja toista toisella puolella.',
  ],
  'Lateral Bound': [
    'Asetu puolikyykkyyn 90 asteen kulmassa kulkusuuntaan nähden.',
    'Anna etujalan tehdä pieni vastaliike sisäänpäin samalla kun siirrät painon ulommalle jalalle.',
    'Ponnista heti ja ojennu sivulle niin pitkälle kuin pystyt.',
    'Kun laskeudut, ponnista välittömästi takaisin vastakkaiseen suuntaan alkuasentoon.',
    'Jatka edestakaisin useita toistoja.',
  ],
  'Leg Extensions': [
    'Liikkeeseen tarvitaan reiden ojennuslaite. Valitse vastus ja istu laitteeseen jalat pehmusteen alle varpaat eteenpäin, kädet sivukahvoilla. Säädä pehmuste säären alaosaan juuri nilkkojen yläpuolelle ja varmista, että sääri ja reisi ovat 90 asteen kulmassa. Sitä ahtaampi kulma vie polven varpaiden yli ja kuormittaa polviniveltä turhaan.',
    'Ojenna jalat suoriksi etureisillä. Muu vartalo pysyy paikallaan penkissä. Pidä sekunti supistuksessa.',
    'Laske paino hitaasti takaisin alas äläkä mene 90 asteen kulmaa ahtaammalle.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Leg Press': [
    'Istu jalkaprässiin ja aseta jalat levylle hartioiden levyiseen asentoon.',
    'Vapauta turvatuet ja työnnä levy ylös, kunnes jalat ovat lähes suorina. Älä lukitse polvia. Ylävartalon ja jalkojen tulee muodostaa 90 asteen kulma.',
    'Laske levyä hitaasti alas, kunnes reisi ja sääri ovat 90 asteen kulmassa.',
    'Työnnä takaisin ylös kantapäillä ja etureisillä.',
    'Toista suositeltu määrä toistoja ja lukitse turvatuet huolellisesti lopuksi. Täyteen ladattu levy ei saa päästä putoamaan päällesi.',
  ],
  'Leverage Chest Press': [
    'Aseta sopiva vastus ja säädä istuin pituutesi mukaan. Kahvojen tulee olla rintalihasten alaosan tai keskiosan kohdalla liikkeen alussa.',
    'Pidä rinta ja katse ylhäällä ja lavat vedettyinä taakse.',
    'Työnnä kahvat eteen ojentamalla kyynärpäät.',
    'Pidä lyhyt tauko ja palauta paino juuri alkuasennon yläpuolelle. Älä laske painoa telineeseen asti ennen kuin sarja on ohi, niin lihasjännitys säilyy.',
  ],
  'Leverage High Row': [
    'Aseta sopiva vastus ja säädä istuimen korkeus niin, että yletät kahvoihin yläpuoleltasi. Säädä polvituki paikalleen. Ota kahvoista yliote.',
    'Vedä kahvat kohti vartaloa ja vedä lavat yhteen samalla kun koukistat kyynärpäitä.',
    'Pidä tauko liikkeen lopussa ja palauta kahvat hitaasti alkuasentoon.',
    'Useammassa toistossa älä laske painoa telineeseen asti, niin lihasjännitys säilyy.',
  ],
  'Low Cable Triceps Extension': [
    'Valitse vastus ja asetu selinmakuulle soutulaitteen penkille, jossa on naruvedin. Pää osoittaa vedintä kohti.',
    'Ota narun päistä kiinni kämmenet vastakkain.',
    'Aseta kyynärpäät 90 asteen kulmaan niin, että olkavarret ovat kohtisuorassa vartaloon nähden. Pidä kyynärpäät lähellä toisiaan, olkavarret osoittavat kattoon ja kyynärvarret pään takana olevaa taljaa kohti.',
    'Ojenna kyynärvarret suoriksi pystysuuntaan. Olkavarret ja kyynärpäät pysyvät paikallaan — vain kyynärvarret liikkuvat. Purista ojentajat sekunnin ajan.',
    'Palaa hitaasti alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Lying Leg Curls': [
    'Säädä laite pituutesi mukaan ja asetu vatsalleen niin, että pehmuste on säärten takana hieman pohkeiden alapuolella. Kulmassa oleva laite aktivoi takareidet paremmin kuin tasainen.',
    'Pidä ylävartalo penkkiä vasten, jalat suorina ja ota kiinni sivukahvoista. Varpaat osoittavat suoraan eteenpäin.',
    'Koukista jalat niin ylös kuin pystyt nostamatta reisiä pehmusteelta. Pidä sekunti täydessä supistuksessa.',
    'Laske jalat takaisin alkuasentoon. Toista suositeltu määrä toistoja.',
  ],
  'Lying T-Bar Row': [
    'Lataa T-tankosoutulaite ja säädä korkeus niin, että ylärinta on tuen yläreunassa. Joissakin laitteissa korkeus säädetään astumalla sopivalle askelmalle.',
    'Asetu vatsalleen tukea vasten ja ota kahvoista kiinni. Voit käyttää ylä-, ala- tai neutraalia otetta sen mukaan, mitä selän osaa haluat painottaa.',
    'Nosta tanko telineestä ja ojenna kädet suoriksi eteesi.',
    'Vedä paino hitaasti ylös ja purista selkä yhteen liikkeen lopussa. Pidä olkavarret lähellä vartaloa, jotta selkä tekee työn. Älä irrota vartaloa tuesta äläkä vedä hauiksilla.',
    'Pidä sekunti supistuksessa ja laske hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Machine Bicep Curl': [
    'Säädä istuin sopivalle korkeudelle ja valitse vastus. Aseta olkavarret pehmusteita vasten ja ota kahvoista kiinni.',
    'Tee liike koukistamalla kyynärpäitä ja vedä kyynärvarret kohti olkavarsia.',
    'Pidä tauko liikkeen lopussa ja palauta paino hitaasti alkuasentoon.',
    'Älä laske painoa telineeseen asti ennen kuin sarja on ohi, niin lihasjännitys säilyy.',
  ],
  'Monster Walk': [
    'Aseta kuminauha nilkkojen ympärille ja toinen polvien ympärille. Nauhojen tulee olla kireällä, kun jalat ovat hartioiden leveydellä.',
    'Ota lyhyitä askelia eteenpäin vuorotellen vasemmalla ja oikealla jalalla.',
    'Kävele muutaman askeleen jälkeen takaperin takaisin lähtöpisteeseen.',
  ],
  'Mountain Climbers': [
    'Asetu punnerrusasentoon käsien ja varpaiden varaan. Koukista toista polvea ja lantiota ja tuo polvi suunnilleen lantion alle.',
    'Vaihda jalkojen paikkaa räjähtävästi: ojenna koukussa ollut jalka suoraksi varpaan varaan ja tuo toinen jalka eteen polvi ja lantio koukussa. Jatka vuorotellen 20–30 sekuntia.',
  ],
  'One-Arm Dumbbell Row': [
    'Ota tasainen penkki ja aseta käsipaino sen kummallekin puolelle.',
    'Aseta oikea polvi penkin päähän, taivuta ylävartalo lantiosta vaakatasoon ja tue oikealla kädellä penkin toisesta päästä.',
    'Nosta käsipaino lattiasta vasemmalla kädellä alaselkä suorana. Kämmen osoittaa vartaloa kohti.',
    'Vedä paino suoraan ylös rintakehän sivulle. Pidä olkavarsi lähellä kylkeä ja ylävartalo paikallaan. Purista selkälihakset liikkeen lopussa. Voima tulee selästä, ei käsistä — kyynärvarsi vain pitää painoa kiinni.',
    'Laske paino suoraan alas alkuasentoon.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Vaihda puolta ja toista toisella kädellä.',
  ],
  'One-Arm Medicine Ball Slam': [
    'Seiso käyntiasennossa urheilullisessa asennossa. Pidä kuntopalloa toisessa kädessä, samalla puolella kuin takajalka.',
    'Vie käsi taakse ja nosta pallo pään yläpuolelle. Ojenna samalla lantio, polvet ja nilkat latautuaksesi iskuun.',
    'Ojennuksen huipulla koukista olkapäätä, selkärankaa ja lantiota ja iske pallo voimalla lattiaan suoraan eteesi.',
    'Ota pallo kiinni pompusta ja jatka halutun toistomäärän ajan.',
  ],
  'One-Legged Cable Kickback': [
    'Kiinnitä nilkkalenkki alataljaan ja pujota lenkki nilkkaasi.',
    'Asetu painopakkaa kohti noin puolen metrin päähän ja ota tukea rungosta.',
    'Pidä polvet ja lantio kevyesti koukussa ja keskivartalo tiukkana. Potkaise työskentelevä jalka taakse kaaressa niin ylös kuin mukavasti pääset puristamalla pakaraa. Purista pakara sekunnin ajan ääriasennossa.',
    'Tuo jalka hitaasti takaisin eteen vastustaen taljan vetoa.',
    'Toista suositeltu määrä toistoja.',
    'Vaihda jalkaa ja toista toiselle puolelle.',
  ],
  'Palms-Down Wrist Curl Over A Bench': [
    'Aseta tanko tasaisen penkin toiselle puolelle.',
    'Asetu polvillesi penkin eteen.',
    'Ota tangosta yliote kämmenet alaspäin ja nosta kyynärvarret penkin päälle. Ranteet jäävät roikkumaan reunan yli.',
    'Käännä ranteita ylöspäin.',
    'Laske ranteet hitaasti takaisin alkuasentoon.',
    'Kyynärvarret pysyvät paikallaan — vain ranteet liikkuvat.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Parallel Bar Dip': [
    'Asetu dippitankojen väliin. Ota kummastakin tangosta kiinni ja ponnista kevyesti ylös suorille käsille.',
    'Laskeudu koukistamalla kyynärpäitä, kunnes olkavarret ohittavat 90 asteen kulman. Älä heilu ja pidä ryhti hyvänä koko laskun ajan.',
    'Työnnä itsesi takaisin ylös ojentamalla kyynärpäät.',
    'Toista haluttu määrä toistoja.',
  ],
  Plank: [
    'Asetu vatsalleen lattialle varpaiden ja kyynärvarsien varaan. Kyynärpäät ovat koukussa suoraan olkapäiden alla.',
    'Pidä vartalo suorana ja asento niin kauan kuin jaksat. Vaikeutta saa lisää nostamalla toisen käden tai jalan irti.',
  ],
  'Power Clean': [
    'Seiso jalat hieman hartioita leveämmällä varpaat kevyesti ulospäin.',
    'Kyykkää alas ja ota tangosta yliote kädet hieman hartioita leveämmällä polvien ulkopuolelta, kädet suorina.',
    'Tanko on noin kolme senttimetriä säärten edessä päkiöiden yläpuolella.',
    'Selkä on suorana tai kevyessä notkossa, rinta ylhäällä ja lavat vedettyinä taakse.',
    'Pidä pää selkärangan jatkeena ja katse suoraan eteen. Vedä henkeä tässä vaiheessa.',
    'Nosta tanko lattiasta ojentamalla lantio ja polvet voimakkaasti. Ylävartalon kulma pysyy samana — älä taivuta vielä vyötäröstä äläkä anna lantion nousta hartioita nopeammin.',
    'Kädet pysyvät suorina, pää neutraalina ja hartiat tangon yläpuolella.',
    'Pidä tanko mahdollisimman lähellä sääriä noston aikana.',
    'Kun tanko ohittaa polvet, työnnä lantio eteen ja koukista polvia hieman, jotta ne eivät lukkiudu. Tässä kohtaa reidet ovat tankoa vasten.',
    'Selkä pysyy suorana tai kevyessä notkossa, kädet suorina ja pää neutraalina. Pidätä hengitystä seuraavaan vaiheeseen asti.',
    'Vedä henkeä ja ojenna lantio ja polvet nopeasti ja voimakkaasti nousten päkiöille.',
    'Pidä tanko mahdollisimman lähellä vartaloa. Selkä suorana, kyynärpäät sivuille osoittaen ja pää neutraalina. Pidä hartiat tangon yläpuolella ja kädet suorina niin pitkään kuin pystyt.',
    'Kun alavartalo on täysin ojentunut, kohauta hartioita nopeasti ylös antamatta kyynärpäiden vielä koukistua.',
    'Kun hartiat ovat korkeimmillaan, koukista kyynärpäät ja ala vetää itseäsi tangon alle.',
    'Jatka vetoa niin korkealle ja pitkään kuin pystyt. Räjähtävyyden takia ylävartalo on pysty tai kevyessä notkossa, pää hieman taaksepäin ja jalat voivat irrota lattiasta.',
    'Kun alavartalo on ojentunut ja tanko lähes korkeimmillaan, vedä itsesi tangon alle ja kierrä kädet tangon ympäri ja alle.',
    'Koukista samanaikaisesti lantio ja polvet neljännyskyykkyyn.',
    'Kun kädet ovat tangon alla, vedä henkeä ja nosta kyynärpäät niin, että olkavarret ovat vaakatasossa. Tanko lepää solisluiden ja etuolkapäiden päällä.',
    'Ota tanko kiinni ylävartalo pystyssä ja tiukkana, pää neutraalina ja jalkaterät maassa.',
    'Nouse pystyyn ojentamalla lantio ja polvet suoriksi.',
    'Laske tanko alas vähentämällä käsien jännitystä vähitellen ja ohjaa se hallitusti reisille.',
    'Koukista samalla lantiota ja polvia vaimentamaan tangon isku reisiin.',
    'Kyykkää alas kädet suorina, kunnes tanko koskettaa lattiaa.',
    'Aloita alusta ja toista suositeltu määrä toistoja.',
  ],
  'Preacher Curl': [
    'Tarvitset saarnaajapenkin ja EZ-tangon. Ota tangosta kiinni sisemmistä kahvoista. Kämmenet osoittavat eteenpäin ja kääntyvät tangon muodon mukaan hieman sisäänpäin.',
    'Aseta olkavarret pehmustetta vasten ja rinta tukea vasten. Pidä tankoa suorilla käsillä.',
    'Laske tankoa hitaasti, kunnes olkavarsi on ojentunut ja hauis täysin venynyt.',
    'Käännä paino ylös hauiksilla, kunnes hauikset ovat täysin supistuneet ja tanko on hartioiden korkeudella. Purista hauikset ja pidä asento sekunnin ajan.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Pull Through': [
    'Seiso muutaman askeleen päässä alataljan edessä naru tai kahva kiinnitettynä. Käänny poispäin laitteesta niin, että vaijeri kulkee jalkojen välistä, jalat leveässä haara-asennossa.',
    'Kurota kädet jalkojen välistä niin pitkälle taakse kuin pystyt taivuttamalla lantiosta. Polvet ovat kevyesti koukussa. Pidä kädet suorina ja ojenna lantio pystyasentoon. Älä vedä hartioilla — koko liike tulee lantiosta.',
  ],
  Pullups: [
    'Ota leukatangosta yliote ohjelman mukaisella otteella. Leveä ote on hartioita leveämpi, keskileveä hartioiden levyinen ja kapea hartioita kapeampi.',
    'Roiku suorilla käsillä ja kallista ylävartaloa noin 30 astetta taakse. Alaselkä kevyessä notkossa ja rinta ulos.',
    'Vedä itsesi ylös, kunnes tanko koskettaa ylärintaa. Vedä hartiat ja olkavarret alas ja taakse. Purista selkälihakset ääriasennossa. Ylävartalo pysyy suorana ja vain kädet liikkuvat.',
    'Pidä sekunti supistuksessa ja laskeudu hitaasti takaisin suorille käsille, jolloin leveät selkälihakset venyvät täysin.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  'Push Up to Side Plank': [
    'Asetu punnerrusasentoon varpaiden varaan kädet hieman hartioita leveämmällä.',
    'Punnerra koukistamalla kyynärpäitä. Pidä vartalo suorana laskeutuessasi.',
    'Tee yksi punnerrus ja siirrä ylös noustessasi paino vasemmalle puolelle. Kierry sivulle ja nosta oikea käsi kohti kattoa kylkilankkuun.',
    'Laske käsi takaisin lattialle uutta punnerrusta varten ja kierry sitten toiselle puolelle.',
    'Toista sarjaa vuorotellen puolelta toiselle vähintään 10 toistoa.',
  ],
  'Push-Up Wide': [
    'Asetu lankkuasentoon varpaiden ja käsien varaan kädet leveällä. Kyynärpäät ovat suorina ja vartalo suorassa linjassa — älä anna lantion pudota.',
    'Laskeudu koukistamalla kyynärpäitä, kunnes rinta on lähellä lattiaa.',
    'Työnnä itsesi takaisin ylös rintalihaksilla ojentamalla kyynärpäät.',
    'Pidä lyhyt tauko ylhäällä ja toista ohjelman mukainen määrä toistoja.',
  ],
  Pushups: [
    'Asetu vatsalleen lattialle kädet hieman hartioita leveämmällä ja työnnä vartalo ylös suorille käsille.',
    'Laskeudu alas, kunnes rinta lähes koskettaa lattiaa.',
    'Työnnä ylävartalo takaisin ylös ja purista rintalihakset.',
    'Pidä lyhyt tauko ylhäällä ja laskeudu uudelleen. Toista tarvittava määrä toistoja.',
  ],
  'Reverse Flyes': [
    'Asetu vinopenkille vatsalleen niin, että rinta ja vatsa ovat tukea vasten. Ota käsipainot käsiin kämmenet vastakkain.',
    'Ojenna kädet eteesi kohtisuoraan penkin kulmaan nähden. Jalat pysyvät paikallaan päkiöillä tukien.',
    'Pidä kyynärpäissä kevyt koukku ja vie painot sivuille kaaressa poispäin toisistaan. Purista lapaluita yhteen.',
    'Nosta kädet vaakatasoon asti.',
    'Tunne supistus ja laske painot hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Reverse Grip Bent-Over Rows': [
    'Seiso ryhdikkäästi tanko alaotteella kämmenet ylöspäin.',
    'Koukista polvia hieman ja taivuta ylävartalo lantiosta lähes vaakatasoon selkä suorana. Pidä katse eteenpäin. Tanko roikkuu suoraan edessäsi kädet suorina.',
    'Pidä ylävartalo paikallaan ja vedä tanko ylös kyynärpäät lähellä vartaloa. Kyynärvarsi vain pitää painoa kiinni. Purista selkälihakset ääriasennossa ja pidä sekunti.',
    'Laske paino hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Reverse Hyperextension': [
    'Aseta sopiva vastus ja pujota jalat pehmusteiden väliin. Asetu vatsalleen ylätuen päälle niin, että lantio jää tuen reunan yli, ja ota kahvoista kiinni.',
    'Aloita liike koukistamalla lantiota ja vedä jalat eteen.',
    'Palaa ojentamalla lantio ja potkaise jalat taakse. Älä yliojenna lantiota — pysähdy ennen liikeradan ääriasentoa.',
    'Palaa koukistamalla lantiota ja vedä kelkka eteen niin pitkälle kuin pystyt.',
    'Toista haluttu määrä toistoja.',
  ],
  'Reverse Machine Flyes': [
    'Säädä kahvat kokonaan taakse. Valitse vastus ja säädä istuimen korkeus niin, että kahvat ovat hartioiden korkeudella. Ota kahvoista kiinni kämmenet sisäänpäin.',
    'Vedä kädet kaaressa sivuille ja taakse ja purista takaolkapäät.',
    'Pidä kädet kevyesti koukussa koko liikkeen ajan — liike tapahtuu vain olkanivelestä.',
    'Pidä tauko ääriasennossa ja palauta paino hitaasti alkuasentoon.',
  ],
  'Romanian Deadlift': [
    'Aseta tanko lattialle eteesi ja ota siitä yliote hieman hartioita leveämmältä. Painon mukaan voit tarvita rannelenkkejä ja korokkeen, joka sallii pidemmän liikeradan.',
    'Koukista polvia hieman, pidä sääret pystyssä, lantio taakse ja selkä suorana.',
    'Pidä selkä ja kädet täysin suorina ja nosta tanko ojentamalla lantio. Liike ei ole nopea vaan tasainen ja hallittu.',
    'Kun olet täysin pystyssä, laske tanko työntämällä lantiota taakse ja koukistamalla polvia vain hieman — toisin kuin kyykyssä. Vedä henkeä liikkeen alussa ja pidä rinta ylhäällä.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Russian Twist': [
    'Asetu selinmakuulle lattialle ja lukitse jalat jonkin painavan alle tai anna kaverin pitää niistä kiinni. Polvet ovat koukussa.',
    'Nosta ylävartalo ylös niin, että vartalo ja reidet muodostavat V-kirjaimen. Kädet ovat suorina edessäsi kohtisuoraan vartaloon nähden sormet lomittain.',
    'Kierrä ylävartaloa oikealle, kunnes kädet ovat lattian suuntaisesti.',
    'Pidä supistus sekunnin ajan ja palaa alkuasentoon. Kierrä sitten samalla tavalla vasemmalle.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Seated Cable Rows': [
    'Tarvitset alataljasoutulaitteen ja V-kahvan, joka antaa neutraalin otteen kämmenet vastakkain. Istu laitteeseen ja aseta jalat etulevylle polvet kevyesti koukussa.',
    'Nojaa eteen selän luonnollinen asento säilyttäen ja ota V-kahvasta kiinni.',
    'Vedä kädet suorina takaisin, kunnes ylävartalo on 90 asteen kulmassa jalkoihin nähden. Selkä on kevyessä notkossa ja rinta ulkona. Tunnet venytyksen leveissä selkälihaksissa.',
    'Pidä ylävartalo paikallaan ja vedä kahvat vartaloa kohti kädet lähellä kylkiä, kunnes kosketat vatsaa. Purista selkälihakset kunnolla, pidä sekunti ja palaa hitaasti alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Seated Calf Raise': [
    'Istu laitteeseen ja aseta päkiät levyn alaosaan kantapäät ilmassa. Valitse varpaiden asento: eteenpäin, sisään tai ulos.',
    'Aseta reidet pehmusteen alle ja säädä se reisien korkeuden mukaan. Aseta kädet pehmusteen päälle, jottei se pääse luiskahtamaan eteen.',
    'Nosta vipua hieman työntämällä kantapäillä ja vapauta turvatuki.',
    'Laske kantapäät hitaasti alas nilkoista taivuttaen, kunnes pohkeet ovat täysin venyneet.',
    'Nosta kantapäät niin ylös kuin pystyt ojentamalla nilkat ja purista pohkeet. Pidä sekunti ääriasennossa.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Seated Dumbbell Curl': [
    'Istu tasaiselle penkille käsipainot suorilla käsillä, kyynärpäät lähellä vartaloa.',
    'Käännä kämmenet vartaloa kohti.',
    'Pidä olkavarret paikallaan ja käännä painot ylös. Kierrä ranteita, kun painot ohittavat reidet, niin että kämmenet osoittavat lopussa eteenpäin. Vain kyynärvarret liikkuvat. Jatka, kunnes hauikset ovat täysin supistuneet ja painot ovat hartioiden korkeudella. Pidä sekunti supistuksessa.',
    'Laske painot hitaasti takaisin alas ja kierrä ranteet takaisin neutraaliksi.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Seated Dumbbell Press': [
    'Ota käsipainot ja istu selkänojalliselle penkille painot pystyssä reisien päällä.',
    'Nosta painot hartioiden korkeudelle yksi kerrallaan reisien avulla.',
    'Käännä ranteet niin, että kämmenet osoittavat eteenpäin.',
    'Työnnä painot ylös, kunnes ne koskettavat toisiaan ylhäällä.',
    'Pidä sekunnin tauko ja laske hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Seated Floor Hamstring Stretch': [
    'Istu alustalle oikea jalka suorana edessäsi ja vasen polvi koukussa jalkaterä oikeaa sisäreittä vasten.',
    'Nojaa eteen lantiosta ja kurota kohti nilkkaa, kunnes tunnet venytyksen takareidessä. Pidä 15 sekuntia ja toista toisella puolella.',
  ],
  'Seated Leg Curl': [
    'Säädä laite pituutesi mukaan ja istu selkä tukea vasten.',
    'Aseta säärten takaosa pehmusteen päälle hieman pohkeiden alapuolelle ja lukitse reisituki polvien yläpuolelle. Ota kiinni sivukahvoista, varpaat suoraan eteenpäin ja jalat suorina edessäsi.',
    'Vedä vipu niin pitkälle reisien alle kuin pystyt koukistamalla polvia. Ylävartalo pysyy paikallaan. Pidä sekunti supistuksessa.',
    'Palaa hitaasti alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Side Lateral Raise': [
    'Ota käsipainot ja seiso ryhdikkäästi kädet suorina sivuilla kämmenet vartaloa kohti.',
    'Pidä ylävartalo paikallaan — ei heilautusta — ja nosta painot sivuille kevyt koukku kyynärpäissä. Kallista käsiä hieman eteen kuin kaataisit vettä lasiin. Jatka, kunnes kädet ovat vaakatasossa. Pidä sekunti ylhäällä.',
    'Laske painot hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Decline Push-Up': [
    'Asetu vatsalleen lattialle, kädet noin olkapäitä leveämmällä ja vartalo ylhäällä suorien käsien varassa. Nosta jalat korokkeelle, esimerkiksi tuolille tai penkille.',
    'Laske itseäsi alas, kunnes rinta melkein koskettaa lattiaa.',
    'Työnnä ylävartalo takaisin ylös alkuasentoon ja purista rintaa.',
    'Pidä lyhyt tauko ylhäällä ja toista haluttu määrä toistoja.',
  ],
  'Single Leg Glute Bridge': [
    'Asetu selinmakuulle jalkaterät lattiassa ja polvet koukussa.',
    'Nosta toinen jalka irti lattiasta ja vedä polvi rintaa kohti.',
    'Työnnä tukijalan kantapäällä, ojenna lantio ylös ja nosta pakarat irti lattiasta.',
    'Ojenna niin ylös kuin pystyt, pidä tauko ja palaa alkuasentoon.',
  ],
  'Sled Overhead Triceps Extension': [
    'Kiinnitä kaksoiskahvat rekeen ketjulla tai köydellä ja lastaa reki sopivaan painoon.',
    'Käänny poispäin reestä ja astu eteen, kunnes köysi kiristyy. Nosta kädet pään yläpuolelle yhteen kämmenet vastakkain. Kyynärpäät osoittavat ylös ja ovat koukussa.',
    'Ojenna kyynärpäät suoriksi. Pidä olkavarret paikallaan, jotta ojentajat tekevät työn.',
    'Kun kädet ovat suorina, astu eteenpäin poistaaksesi löysän köydestä. Käyntiasento tuo lisää tukea.',
  ],
  'Sled Push': [
    'Lastaa työntöreki haluttuun painoon.',
    'Asetu urheilulliseen asentoon, nojaa rekeen kädet suorina ja ota kahvoista kiinni. Työnnä rekeä niin nopeasti kuin pystyt ja keskity ojentamaan lantio ja polvet, niin takaketju tekee työn.',
  ],
  'Smith Machine Close-Grip Bench Press': [
    'Aseta tasainen penkki smith-laitteen alle ja tanko korkeudelle, johon yletät maaten kädet lähes suorina. Valitse paino ja asetu penkille. Ota tangosta hartioiden levyinen yliote, vapauta tanko telineestä ja pidä sitä suorilla käsillä yläpuolellasi.',
    'Laske tankoa hitaasti alas, kunnes se koskettaa keskirintaa. Toisin kuin tavallisessa penkkipunnerruksessa, pidä kyynärpäät lähellä vartaloa koko ajan, jotta ojentajat tekevät työn.',
    'Pidä sekunnin tauko ja työnnä tanko takaisin ylös ojentajilla. Ojenna kädet ylhäällä, pidä sekunti ja laske hitaasti alas. Laskuvaihe saa kestää vähintään kaksi kertaa noston verran.',
    'Toista ohjelman mukainen määrä toistoja.',
    'Lukitse tanko telineeseen sarjan päätteeksi.',
  ],
  // Added with the "Bulgarian Split Squat" alias fix (bug hunt, 2026-10-04): the
  // name used to open "Split Squats", a jumping bodyweight move. Four steps.
  'Split Squat with Dumbbells': [
    'Asetu porrastettuun asentoon niin, että takajalka on koholla ja etujalka edessä.',
    'Pidä käsipainoa kummassakin kädessä käsivarret sivuilla roikkuen. Tämä on alkuasento.',
    'Laskeudu koukistamalla polvea ja lonkkaa. Pidä ryhti hyvänä koko liikkeen ajan ja etupolvi jalkaterän linjassa.',
    'Työnnä alhaalta kantapään kautta ja ojenna polvi ja lonkka takaisin alkuasentoon.',
  ],
  'Split Squats': [
    'Aloita seisoma-asennosta. Hyppää käyntiasentoon toinen jalka edessä ja toinen takana, koukista polvia ja laske lantiota hieman.',
    'Vaihda suuntaa heti laskeutumisen jälkeen: nouse ylös ja hyppää vaihtaen jalkojen paikkaa. Toista 5–10 kertaa kummallakin jalalla.',
  ],
  Stairmaster: [
    'Astu porraslaitteeseen ja valitse haluamasi vaihtoehto valikosta. Voit valita manuaalisen asetuksen tai valmiin ohjelman. Yleensä voit syöttää ikäsi ja painosi, jolloin laite arvioi kulutetut kalorit.',
    'Pumppaa jalkoja tasaisessa rytmissä ja paina poljinta alas, mutta älä pohjaan asti. Pidä kiinni kahvoista, jotta et putoa. Kahvoista voi myös seurata sykettä ja pitää tehon oikeana.',
    'Älä nojaa kahvojen varaan. Kahvat ovat tasapainoa varten — jos joudut roikkumaan niissä pysyäksesi mukana, laske vauhtia.',
  ],
  'Standing Calf Raises': [
    'Säädä pohjelaitteen pehmuste pituutesi mukaan.',
    'Aseta hartiat pehmusteiden alle ja varpaat suoraan eteenpäin. Päkiät ovat askelman päällä ja kantapäät sen reunan yli. Työnnä vipu ylös ojentamalla lantio ja polvet, kunnes olet pystyasennossa. Pidä polvissa kevyt koukku — älä koskaan lukitse niitä.',
    'Nosta kantapäät niin ylös kuin pystyt ojentamalla nilkat ja purista pohkeet. Polvi pysyy paikallaan koko ajan. Pidä sekunti ääriasennossa ennen kuin lasket alas.',
    'Palaa hitaasti alkuasentoon laskemalla kantapäät alas, kunnes pohkeet ovat venyneet.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Standing Hamstring and Calf Stretch': [
    'Pujota vyö, kuminauha tai naru toisen jalkaterän ympäri. Seiso ja vie tämä jalka eteen.',
    'Koukista takajalkaa ja pidä etujalka suorana. Nosta etujalan varpaat irti lattiasta ja nojaa eteen.',
    'Vedä nauhalla jalkaterän päältä, jolloin venytys pohkeessa kasvaa. Pidä 10–20 sekuntia ja toista toisella jalalla.',
  ],
  'Standing Hip Circles': [
    'Seiso yhdellä jalalla ja ota tukea pystysuorasta tuesta.',
    'Nosta vapaa polvi 90 asteen kulmaan.',
    'Avaa lonkkaa niin pitkälle kuin pystyt ja piirrä polvella suuri ympyrä.',
    'Tee liike hitaasti muutaman toiston ajan ja toista toisella jalalla.',
  ],
  'Standing Military Press': [
    'Aseta tanko kyykkytelineeseen suunnilleen rinnan korkeudelle. Valitse painot ja ota tangosta yliote hieman hartioita leveämmältä.',
    'Koukista polvia hieman ja aseta tanko solisluiden päälle. Nosta tanko ylös rintaa vasten, astu askel taakse ja asetu jalat hartioiden leveydelle.',
    'Työnnä tanko pään yli suorille käsille. Pidä sitä hartioiden korkeudella hieman pään edessä.',
    'Laske tanko hitaasti alas solisluille.',
    'Työnnä tanko takaisin ylös alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Step-up with Knee Raise': [
    'Seiso sopivan korkuisen laatikon tai penkin edessä jalat vierekkäin.',
    'Astu vasemmalla jalalla penkin päälle. Ojenna etujalan lantio ja polvi ja nouse seisomaan penkille. Nosta samalla oikea polvi niin ylös kuin pystyt.',
    'Astu hallitusti takaisin alas ja toista sarja toisella jalalla.',
  ],
  'Stomach Vacuum': [
    'Seiso ryhdikkäästi jalat hartioiden leveydellä kädet lantiolla.',
    'Vedä keuhkot hitaasti täyteen ilmaa ja puhalla sitten kaikki ulos vetäen samalla vatsaa niin sisään kuin pystyt. Pidä asento ja kuvittele navan koskettavan selkärankaa.',
    'Yksi pito kestää noin 20 sekuntia. Yritä hengittää normaalisti pidon aikana. Vedä sitten henkeä ja päästä vatsa takaisin alkuasentoon.',
    'Kun liike on tuttu, pidennä pitoa yli 20 sekunnin. Tavoittele lopulta 40–60 sekuntia.',
    'Toista suositeltu määrä sarjoja.',
  ],
  'Straight-Arm Dumbbell Pullover': [
    'Aseta käsipaino pystyyn tasaisen penkin päälle.',
    'Varmista, että paino pysyy tukevasti penkin päällä, ja asetu makuulle poikittain penkin yli niin, että vain lapaluut ovat penkillä. Lantio on penkin alapuolella, polvet koukussa ja jalkaterät tukevasti lattiassa. Myös pää jää penkin ulkopuolelle.',
    'Ota painosta kiinni molemmin käsin ja pidä sitä suorilla käsillä rinnan yläpuolella. Molemmat kämmenet painavat painon toisen levyn alapuolta. Varmista aina, että käsipaino on ehjä: löysät levyt voivat irrota ja pudota kasvoille.',
    'Pidä kädet suorina ja laske paino hitaasti kaaressa pään taakse, kunnes tunnet venytyksen rinnassa.',
    'Tuo paino takaisin alkuasentoon samaa kaarta pitkin.',
    'Pidä sekunti alkuasennossa ja toista ohjelman mukainen määrä toistoja.',
  ],
  'Sumo Deadlift': [
    'Asetu ladatun tangon taakse niin, että tanko on jalkaterien keskikohdan päällä. Jalat ovat hyvin leveällä lähellä levyjä. Taivuta lantiosta ja ota tangosta kiinni. Kädet ovat suoraan olkapäiden alla jalkojen sisäpuolella. Käytä yliotetta, sekaotetta tai koukkuotetta. Rentouta hartiat, jolloin kädet pitenevät.',
    'Vedä henkeä ja laske lantiota, katse eteen ja rinta ylhäällä. Työnnä lattiaa vasten ja levitä jalkoja ulospäin paino jalkaterien takaosalla. Ojenna lantio ja polvet.',
    'Kun tanko ohittaa polvet, nojaa taakse ja työnnä lantio tankoa vasten vetäen lavat yhteen.',
    'Laske paino takaisin lattiaan taivuttamalla lantiosta ja hallitse liike koko matkan.',
  ],
  'Trap Bar Deadlift': [
    'Lastaa trap bar eli kuusikulmatanko sopivaan painoon lattialle. Asetu tangon keskelle ja ota molemmista kahvoista kiinni.',
    'Laske lantiota, katse eteen ja rinta ylhäällä.',
    'Aloita nosto työntämällä kantapäillä ja ojenna lantio ja polvet. Älä päästä selkää pyöristymään missään vaiheessa.',
    'Laske paino lopuksi hallitusti takaisin lattiaan.',
  ],
  'Tricep Dumbbell Kickback': [
    'Ota käsipaino kumpaankin käteen kämmenet vartaloa kohti. Pidä selkä suorana ja polvet kevyesti koukussa ja taivuta ylävartalo lantiosta lähes vaakatasoon. Pidä katse eteenpäin. Olkavarret ovat lähellä kylkiä vaakatasossa ja kyynärvarret osoittavat alas, jolloin kyynärvarren ja olkavarren väliin jää 90 asteen kulma.',
    'Pidä olkavarret paikallaan ja ojenna kädet suoriksi ojentajilla. Keskity liikuttamaan vain kyynärvartta.',
    'Pidä lyhyt tauko ääriasennossa ja laske painot hitaasti takaisin alkuasentoon.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  'Triceps Pushdown': [
    'Kiinnitä suora tai EZ-tanko ylätaljaan ja ota siitä yliote hartioiden leveydeltä.',
    'Seiso ryhdikkäästi hyvin kevyesti eteen nojaten. Pidä olkavarret lähellä vartaloa ja kohtisuorassa lattiaan nähden, kyynärvarret ylöspäin kohti taljaa.',
    'Työnnä tanko alas ojentajilla, kunnes se koskettaa reisiä ja kädet ovat suorina. Olkavarret pysyvät paikallaan vartalon vieressä — vain kyynärvarret liikkuvat.',
    'Pidä sekunti ääriasennossa ja palauta tanko hitaasti ylös.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Triceps Pushdown - Rope Attachment': [
    'Kiinnitä naruvedin ylätaljaan ja ota siitä neutraali ote kämmenet vastakkain.',
    'Seiso ryhdikkäästi hyvin kevyesti eteen nojaten. Pidä olkavarret lähellä vartaloa ja kohtisuorassa lattiaan nähden, kyynärvarret ylöspäin kohti taljaa kämmenet vastakkain.',
    'Työnnä naru alas ojentajilla ja vie narun päät reisien sivuille. Lopussa kädet ovat suorina kohtisuoraan lattiaan nähden. Olkavarret pysyvät paikallaan — vain kyynärvarret liikkuvat.',
    'Pidä sekunti ääriasennossa ja palauta naru hitaasti ylös.',
    'Toista suositeltu määrä toistoja.',
  ],
  // Pystysoutu. Käännetty kun liikkeestä tuli tavoiteliike ja se lisättiin
  // kahdelle olkapääpäivälle (1.9.2026): valmisohjelman määräämä liike ei saa
  // pudota englantiin.
  'Upright Barbell Row': [
    'Ota tangosta yliote hieman hartioita kapeammalta ja anna sen levätä reisiä vasten kädet suorina, kyynärpäissä kevyt koukku. Pidä selkä suorana.',
    'Nosta tankoa vartalon myötäisesti vetäen kyynärpäät ylös ja sivuille. Pidä tanko lähellä vartaloa ja jatka, kunnes se on lähes leuan tasolla. Kyynärpäät johtavat liikettä ja pysyvät kyynärvarsia ylempänä. Ylävartalo pysyy paikallaan. Pidä sekunti ääriasennossa.',
    'Laske tanko hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Weighted Pull Ups': [
    'Kiinnitä paino dippivyöhön ja aseta vyö vyötärölle. Ota leukatangosta yliote. Keskileveässä otteessa kädet ovat hartioiden leveydellä. Roiku suorilla käsillä.',
    'Kallista ylävartaloa noin 30 astetta taakse, alaselkä kevyessä notkossa ja rinta ulos.',
    'Vedä itsesi ylös, kunnes pää on käsien yläpuolella. Keskity vetämään lapaluita taakse ja alas ääriasennossa.',
    'Pidä hetki ylhäällä ja laskeudu hitaasti takaisin suorille käsille, jolloin leveät selkälihakset venyvät täysin.',
  ],
  'Weighted Sissy Squat': [
    'Seiso ryhdikkäästi jalat hartioiden leveydellä ja kantapäät koholla. Ota toisella kädellä kiinni kyykkytelineen pystytolpasta ja pidä toisella levyä rintaa vasten.',
    'Pidä kiinni tolpasta, koukista polvia ja laske ylävartaloa hitaasti kohti lattiaa viemällä lantiota ja polvia eteen. Pysähdy, kun reiden ja säären väliin jää lähes 90 asteen kulma. Pidä venytys sekunnin ajan.',
    'Nouse takaisin alkuasentoon etureisillä.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Wide-Grip Lat Pulldown': [
    'Istu ylätaljalaitteeseen, jossa on leveä tanko. Säädä polvituki pituutesi mukaan, jotta paino ei nosta sinua ylös.',
    'Ota tangosta yliote ohjelman mukaisella otteella. Leveä ote on hartioita leveämpi, keskileveä hartioiden levyinen ja kapea hartioita kapeampi.',
    'Ojenna kädet suoriksi ja kallista ylävartaloa noin 30 astetta taakse. Alaselkä kevyessä notkossa ja rinta ulos.',
    'Vedä tanko alas, kunnes se koskettaa ylärintaa. Vedä hartiat ja olkavarret alas ja taakse. Purista selkälihakset ääriasennossa. Ylävartalo pysyy paikallaan ja vain kädet liikkuvat — kyynärvarsi vain pitää tangosta kiinni.',
    'Pidä sekunti lapaluut yhdessä ja palauta tanko hitaasti ylös, kunnes kädet ovat suorina ja leveät selkälihakset venyneet.',
    'Toista ohjelman mukainen määrä toistoja.',
  ],
  "World's Greatest Stretch": [
    'Venytys on kolmiosainen. Aloita astumalla pitkälle eteen etujalka koko jalkaterällä ja takajalka varpaiden varassa. Koukista polvia ja laskeudu, kunnes takapolvi lähes koskettaa lattiaa. Pidä ylävartalo pystyssä ja asento 10–20 sekuntia.',
    'Aseta seuraavaksi etujalan puoleinen käsi lattialle kyynärpää jalkaterän vierellä. Toinen käsi tukee lattiassa etujalan rinnalla.',
    'Aseta 10–20 sekunnin jälkeen kädet etujalan molemmin puolin. Nosta etujalan varpaat irti lattiasta ja ojenna jalka suoraksi. Voit joutua siirtämään takajalkaa. Pidä 10–20 sekuntia ja toista koko sarja toiselle puolelle.',
  ],
  'Air Bike': [
    'Asetu selinmakuulle alaselkä lattiaa vasten ja kädet pään vierellä. Varo, ettet vedä niskasta. Nosta hartiat irti lattiasta rutistusasentoon.',
    'Nosta polvet niin, että reidet ovat kohtisuorassa lattiaan nähden ja sääret lattian suuntaisesti.',
    'Aloita polkeva liike: ojenna oikea jalka eteen ja vedä vasen polvi lähemmäs. Vie samalla oikea kyynärpää kohti vasenta polvea kiertämällä ylävartaloa.',
    'Palaa alkuasentoon.',
    'Kierrä toiselle puolelle ja vie vasen kyynärpää kohti oikeaa polvea samalla kun jatkat polkemista.',
    'Jatka vuorotellen, kunnes molemmille puolille on tehty suositeltu määrä toistoja.',
  ],
  'Band Pull Apart': [
    'Aloita kädet suorina edessäsi kuminauha molemmissa käsissä.',
    'Vie kädet sivuille kuin tekisit käänteisen vipunoston.',
    'Pidä kyynärpäät suorina koko liikkeen ajan ja vie nauha rintaa vasten. Pidä hartiat taakse vedettyinä.',
    'Pidä tauko ääriasennossa ja palaa hallitusti alkuasentoon.',
  ],
  'Bench Dips': [
    'Aseta penkki selkäsi taakse poikittain. Ota penkin reunasta kiinni kädet suorina hartioiden leveydellä ja katse poispäin penkistä. Jalat ovat suorina edessä lantiosta taivutettuna.',
    'Laskeudu hitaasti alas koukistamalla kyynärpäitä, kunnes olkavarren ja kyynärvarren väliin jää hieman alle 90 asteen kulma. Pidä kyynärpäät mahdollisimman lähellä toisiaan ja kyynärvarret pystysuunnassa.',
    'Nosta itsesi takaisin ylös ojentajilla.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Bicycling, Stationary': [
    'Istu pyörään ja säädä satula niin, että polvi jää alimmassa kohdassa kevyeen koukkuun.',
    'Valitse vastus, jolla pystyt pitämään tasaista 70–90 kierroksen kadenssia. Pidä ylävartalo rentona ja ote kahvoista kevyenä — jalat tekevät työn.',
  ],
  'Dumbbell Side Bend': [
    'Seiso ryhdikkäästi käsipaino vasemmassa kädessä kämmen vartaloa kohti ja oikea käsi lantiolla. Jalat ovat hartioiden leveydellä.',
    'Pidä selkä suorana ja katse eteenpäin ja taivuta vain vyötäröstä oikealle niin pitkälle kuin pystyt. Pidä sekunti ja palaa ylös alkuasentoon. Muu vartalo pysyy paikallaan.',
    'Toista sama taivuttamalla vasemmalle. Pidä sekunti ja palaa alkuasentoon.',
    'Toista suositeltu määrä toistoja ja vaihda sitten kättä.',
  ],
  'Kettlebell Pistol Squat': [
    'Ota kahvakuula molempiin käsiin sarvista kiinni. Nosta toinen jalka irti lattiasta ja kyykkää toisen varassa.',
    'Kyykkää alas koukistamalla polvea ja työntämällä lantiota taakse. Pidä kuulaa ylhäällä edessäsi.',
    'Pidä ala-asento sekunnin ajan ja nouse ylös työntämällä kantapäällä. Pidä katse ja rinta ylhäällä.',
    'Laskeudu uudelleen ja toista.',
  ],
  'Machine Shoulder (Military) Press': [
    'Istu olkapääprässiin ja valitse vastus.',
    'Ota kahvoista kiinni sivuilta kyynärpäät koukussa vartalon linjassa.',
    'Työnnä kahvat ylös ja ojenna kädet suoriksi. Pidä supistus sekunnin ajan ylhäällä.',
    'Laske kahvat hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Muscle Up': [
    'Ota renkaista valeote (false grip) niin, että kämmenten tyvi on renkaiden päällä. Aloita leuanveto vetämällä kyynärpäät alas kylkiin.',
    'Kun saavutat leuanvedon yläasennon, vedä renkaat kainaloihin ja rullaa hartiat eteen niin, että kyynärpäät pääsevät suoraan taakse. Tästä asennosta jatkat dippiin.',
    'Pidä liike hallittuna ja vakaana ja ojenna kyynärpäät suoriksi.',
    'Laskeudu alas varovasti.',
  ],
  'Plie Dumbbell Squat': [
    'Ota käsipainosta kiinni molemmin käsin sen alapäästä ja seiso suorana. Vie jalat hartioita leveämmälle polvet kevyesti koukussa.',
    'Varpaat osoittavat ulospäin. Kädet pysyvät paikallaan koko liikkeen ajan.',
    'Koukista polvia hitaasti ja laskeudu, kunnes reidet ovat lattian suuntaisesti.',
    'Nouse takaisin ylös työntämällä pääosin kantapäillä.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Quad Stretch': [
    'Asetu kyljellesi. Pujota vyö, naru tai kuminauha ylemmän jalan jalkaterän ympäri. Koukista polvea ja ojenna lonkkaa yrittäen koskettaa kantapäällä pakaraa, ja pidä nauhasta kiinni käsilläsi.',
    'Pidä nauhaa olkapään yli tai pään yläpuolella ja vedä varovasti, jolloin etureiden venytys kasvaa. Pidä 10–20 sekuntia ja vaihda puolta.',
  ],
  'Rowing, Stationary': [
    'Istu soutulaitteeseen. Varmista, että kantapäät ovat tukevasti poljinten pohjaa vasten ja hihnat kiristettyinä. Valitse haluamasi ohjelma, jos laitteessa on sellainen. Istu ryhdikkäästi ja taivuta lantiosta eteen.',
    'Vedossa on kolme vaihetta. Ensimmäisessä olet edessä: polvet koukussa lähellä rintaa ja ylävartalo hieman eteen nojaten mutta ryhdikkäänä. Työnnä sitten poljinlevyjä ja ojenna jalat samalla kun vedät kädet ylävatsalle ja puristat lapoja yhteen. Anna jalkojen ja lantion tehdä työ, niin selkä säästyy.',
    'Palautusvaiheessa ojennat kädet, koukistat polvet ja tuot vartalon takaisin eteen ensimmäiseen vaiheeseen.',
  ],
  'Standing Biceps Cable Curl': [
    'Seiso ryhdikkäästi ja pidä alataljaan kiinnitetystä EZ-tangosta kiinni hartioiden levyisellä alaotteella kämmenet ylöspäin. Kyynärpäät ovat lähellä vartaloa.',
    'Pidä olkavarret paikallaan ja käännä tanko ylös hauiksilla. Vain kyynärvarret liikkuvat. Jatka, kunnes hauikset ovat täysin supistuneet ja tanko on hartioiden korkeudella. Purista sekunnin ajan.',
    'Laske tanko hitaasti takaisin alkuasentoon.',
    'Toista suositeltu määrä toistoja.',
  ],
  'Standing Dumbbell Press': [
    'Seiso jalat hartioiden leveydellä käsipaino kummassakin kädessä. Nosta painot pään korkeudelle kyynärpäät sivuilla noin 90 asteen kulmassa.',
    'Pidä tekniikka tiukkana ilman jalkojen vauhtia tai taaksepäin nojaamista ja työnnä painot ylös suoraan pään yläpuolelle.',
    'Pidä tauko ja laske painot hitaasti takaisin alkuasentoon.',
  ],
  'Standing Long Jump': [
    'Tee liike mieluiten hiekassa tai muulla pehmeällä alustalla ja varmista, että voit mitata matkan. Asetu puolikyykkyyn jalat hartioiden leveydellä.',
    'Heilauta käsiä voimakkaasti ja tee jaloilla vastaliike. Hyppää eteenpäin niin pitkälle kuin pystyt.',
    'Pyri laskeutumaan jalat edessäsi ja kurota jaloilla niin pitkälle kuin pystyt.',
    'Mittaa matka lähtöpisteestä laskeutumiskohtaan ja kirjaa tulos ylös.',
  ],
  // The equipment fallbacks below are prescribed too — a plan swaps onto them
  // when the gear is missing — and they read in English until 2026-10-04.
  'Bulgarian Split Squat': [
    'Seiso pitkän askeleen päässä penkistä tai tukevasta tuolista selkä sitä kohti ja nosta takajalan jalkapöytä sen päälle. Pidä käsipainoa kummassakin kädessä, jos ohjelmasi kirjaa painon; muuten pidä kädet lantiolla.',
    'Laskeudu suoraan alas koukistamalla etupolvea, kunnes takapolvi melkein koskettaa lattiaa. Pidä ylävartalo pystyssä ja etupolvi jalkaterän päällä.',
    'Työnnä etukantapäällä takaisin ylös.',
    'Tee kaikki toistot yhdellä jalalla ja vaihda sitten jalkaa.',
  ],
  'Stiff-Legged Dumbbell Deadlift': [
    'Ota käsipaino kumpaankin käteen ja pidä ne suorin käsin kylkien vieressä.',
    'Seiso ryhti suorana jalat hartioiden leveydellä tai kapeammin, polvet hieman koukussa.',
    'Pidä polvet paikallaan ja laske painot jalkapöytien yläpuolelle taivuttamalla lantiosta selkä suorana, kunnes tunnet venytyksen takareisissä.',
    'Nouse takaisin pystyyn ojentamalla lantio.',
    'Toista ohjelman toistomäärä.',
  ],
  'Butt Lift (Bridge)': [
    'Asetu selinmakuulle kädet kylkien vieressä ja polvet koukussa, jalat noin hartioiden leveydellä.',
    'Työnnä pääasiassa kantapäillä ja nosta lantio irti lattiasta selkä suorana. Pidä yläasennossa sekunti.',
    'Laske lantio hitaasti takaisin alas.',
  ],
  'Bent Over Two-Dumbbell Row': [
    'Ota käsipaino kumpaankin käteen kämmenet vartaloa kohti, koukista polvia hieman ja kallista ylävartalo eteen selkä suorana, lähes lattian suuntaiseksi. Pidä pää ylhäällä ja anna painojen roikkua suoraan alaspäin.',
    'Pidä ylävartalo paikallaan ja vedä painot kylkiin kyynärpäät lähellä vartaloa. Purista yläasennossa lapoja yhteen sekunnin ajan.',
    'Laske painot hitaasti takaisin alas.',
    'Toista ohjelman toistomäärä.',
  ],
  'Reverse Plate Curls': [
    'Seiso suorana ja pidä levypainoa molemmin käsin kämmenet alaspäin, kädet suorina. Tartu levyyn kellotaulun kohdista 11 ja 1.',
    'Pidä jalat hartioiden leveydellä ja levy lantion edessä.',
    'Nosta levy hitaasti ylös kyynärpäät kyljissä ja olkavarret paikallaan, kunnes kyynärvarret ja hauikset kohtaavat.',
    'Pidä sekunti ja laske levy hitaasti takaisin alas.',
    'Toista ohjelman toistomäärä.',
  ],
  'Donkey Calf Raises': [
    'Liikkeeseen tarvitaan donkey-pohjenostolaite. Asetu laitteen pehmusteen alle niin, että se on häntäluun kohdalla.',
    'Ota kiinni sivukahvoista ja aseta päkiät korokkeelle kantapäät reunan yli. Ojenna polvet lukitsematta niitä.',
    'Nouse päkiöille niin korkealle kuin pystyt polvet paikallaan. Pidä yläasennossa sekunti.',
    'Laske kantapäät hitaasti alas, kunnes pohkeet venyvät.',
    'Toista ohjelman toistomäärä.',
  ],
  'Trail Running/Walking': [
    'Juokse tai kävele maastopolulla hyvissä kengissä. Ylämäessä työ tulee pohkeista ja pakaroista, alamäessä polvet ja nilkat ottavat iskut vastaan: lyhennä askelta, pidä polvet koukussa ja hidasta vauhtia.',
    'Ylämäki kuormittaa selvästi enemmän kuin tasainen maasto, ja juoksu enemmän kuin kävely.',
  ],
  'Reverse Crunch': [
    'Asetu selinmakuulle jalat suorina ja kädet vartalon vieressä kämmenet lattiassa. Kädet pysyvät paikallaan koko liikkeen ajan.',
    'Nosta jalat niin, että reidet ovat pystysuorassa ja sääret lattian suuntaisesti jalat yhdessä.',
    'Tuo polvet kohti rintaa kiertämällä lantiota taaksepäin, kunnes lantio nousee irti lattiasta.',
    'Pidä sekunti ja laske jalat hallitusti takaisin alkuasentoon.',
    'Toista ohjelman toistomäärä.',
  ],
};

/**
 * The steps to draw for one exercise.
 *
 * Falls back to the English steps rather than to nothing: the library is an
 * English dataset and a missing translation is a gap in this file, not a reason
 * to leave a reader without instructions.
 */
export function getExerciseInstructions(
  name: string | null | undefined,
  englishSteps: string[] | null | undefined,
  language: AppLanguage = 'en',
): string[] {
  const english = (englishSteps ?? []).filter(Boolean);
  if (language !== 'fi' || !name) {
    return english;
  }

  const finnish = EXERCISE_INSTRUCTIONS_FI[name.trim()];
  return finnish && finnish.length > 0 ? finnish : english;
}

/** Exported for the tests that keep this file paired with the library. */
export const EXERCISE_INSTRUCTIONS_FI_TABLE = EXERCISE_INSTRUCTIONS_FI;
