import { getWorkoutTemplateById } from '../features/workout/workoutCatalog';
import { Vinha_PROGRAM_RECOMMENDATIONS } from '../features/workout/gainerProgramCatalog';
import type { SetupFocusArea, SetupGoal, SetupLevel, SetupSecondaryOutcome } from '../types/models';
import type { RecommendationProgramDefinition, TemplateFamilyId } from '../types/recommendation';
import { readyTemplateCardMinutes } from './programmeMinutes';

function defineProgram(
  programId: string,
  config: {
    familyId: TemplateFamilyId;
    supportedGoals: SetupGoal[];
    backupGoals?: SetupGoal[];
    supportedLevels: SetupLevel[];
    equipmentTier: RecommendationProgramDefinition['equipmentTier'];
    recoveryDemand: RecommendationProgramDefinition['recoveryDemand'];
    styleTags: RecommendationProgramDefinition['styleTags'];
    secondaryOutcomeTags?: SetupSecondaryOutcome[];
    focusAreaTags?: SetupFocusArea[];
    lowFriction?: boolean;
    jointFriendly?: boolean;
    targetGender?: RecommendationProgramDefinition['targetGender'];
  },
): RecommendationProgramDefinition {
  const template = getWorkoutTemplateById(programId);
  if (!template) {
    throw new Error(`Unknown recommendation program: ${programId}`);
  }

  return {
    programId,
    familyId: config.familyId,
    supportedGoals: config.supportedGoals,
    backupGoals: config.backupGoals ?? [],
    supportedLevels: config.supportedLevels,
    equipmentTier: config.equipmentTier,
    recoveryDemand: config.recoveryDemand,
    styleTags: config.styleTags,
    secondaryOutcomeTags: config.secondaryOutcomeTags ?? [],
    focusAreaTags: config.focusAreaTags ?? [],
    lowFriction: config.lowFriction ?? false,
    jointFriendly: config.jointFriendly ?? false,
    targetGender: config.targetGender ?? 'unisex',
    daysPerWeek: template.daysPerWeek,
    // The minutes the cards and Home show, estimated from the sessions. The
    // hand-written figure is what was scored, and it differed from the card's
    // by 10 minutes or more on 39 of 51 programmes (catalog audit, 2026-10-05).
    estimatedSessionMinutes: readyTemplateCardMinutes(template),
  };
}

export const RECOMMENDATION_PROGRAMS: RecommendationProgramDefinition[] = [
  defineProgram('tpl_2_day_minimal_full_body_v1', {
    familyId: 'full_body_minimal',
    supportedGoals: ['general', 'general_fitness'],
    backupGoals: ['muscle', 'strength'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'low_equipment',
    recoveryDemand: 'low',
    styleTags: ['express', 'balanced'],
    secondaryOutcomeTags: ['consistency'],
    focusAreaTags: ['core', 'legs'],
    lowFriction: true,
    jointFriendly: true,
  }),
  defineProgram('tpl_2_day_beginner_strength_v1', {
    familyId: 'strength_base',
    supportedGoals: ['strength'],
    backupGoals: ['general', 'general_fitness'],
    supportedLevels: ['beginner'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['heavy', 'express'],
    secondaryOutcomeTags: ['consistency', 'strength'],
    focusAreaTags: ['legs', 'chest', 'back'],
    lowFriction: true,
  }),
  defineProgram('tpl_3_day_strength_base_v1', {
    familyId: 'strength_base',
    supportedGoals: ['strength'],
    backupGoals: ['muscle', 'general', 'lean_athletic'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['heavy', 'balanced'],
    secondaryOutcomeTags: ['strength', 'consistency'],
    focusAreaTags: ['legs', 'chest', 'back'],
  }),
  defineProgram('tpl_4_day_strength_size_v1', {
    familyId: 'powerbuilding',
    supportedGoals: ['strength'],
    backupGoals: ['general', 'lean_athletic'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['heavy', 'balanced'],
    secondaryOutcomeTags: ['strength', 'muscle'],
    focusAreaTags: ['legs', 'chest', 'back', 'shoulders'],
  }),
  defineProgram('tpl_4_day_powerbuilding_v1', {
    familyId: 'powerbuilding',
    supportedGoals: ['strength', 'muscle'],
    backupGoals: ['general', 'lean_athletic'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['heavy', 'pump'],
    secondaryOutcomeTags: ['strength', 'muscle'],
    focusAreaTags: ['legs', 'chest', 'back', 'arms'],
  }),
  // FIT is defined before FIT Lite on purpose: waterfall ties resolve to the
  // family flagship, and Lite stays the low-recovery variant.
  defineProgram('tpl_3_day_full_body_v1', {
    familyId: 'full_body_minimal',
    supportedGoals: ['general', 'general_fitness'],
    backupGoals: ['muscle'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['balanced', 'express'],
    secondaryOutcomeTags: ['consistency'],
    focusAreaTags: ['legs', 'chest', 'back'],
    lowFriction: true,
  }),
  defineProgram('tpl_3_day_upper_lower_lite_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['general', 'general_fitness'],
    backupGoals: ['strength', 'muscle', 'lean_athletic'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'low',
    styleTags: ['balanced', 'express'],
    secondaryOutcomeTags: ['consistency'],
    focusAreaTags: ['arms', 'back', 'chest'],
    lowFriction: true,
    jointFriendly: true,
  }),
  defineProgram('tpl_3_day_push_pull_legs_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'back', 'arms', 'legs'],
  }),
  defineProgram('tpl_4_day_muscle_builder_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general', 'lean_athletic'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['glutes', 'legs', 'chest', 'back'],
    jointFriendly: true,
  }),
  defineProgram('tpl_4_day_upper_lower_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general', 'lean_athletic', 'strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['balanced', 'pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['legs', 'chest', 'back'],
  }),
  defineProgram('tpl_5_day_hybrid_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['balanced', 'pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'back', 'arms', 'legs'],
  }),
  defineProgram('tpl_6_day_ppl_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle', 'general_fitness'],
    backupGoals: ['strength', 'general', 'lean_athletic'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle', 'strength'],
    focusAreaTags: ['chest', 'back', 'arms', 'legs', 'shoulders'],
  }),
  defineProgram('tpl_2_day_mobility_reset_v1', {
    familyId: 'joint_friendly',
    supportedGoals: ['general', 'general_fitness', 'run_mobility'],
    backupGoals: [],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'low_equipment',
    recoveryDemand: 'low',
    styleTags: ['recovery', 'express'],
    secondaryOutcomeTags: ['mobility', 'consistency'],
    focusAreaTags: ['mobility'],
    lowFriction: true,
    jointFriendly: true,
  }),
  defineProgram('tpl_2_day_yoga_recovery_v1', {
    familyId: 'joint_friendly',
    supportedGoals: ['run_mobility'],
    backupGoals: ['general', 'general_fitness'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'low_equipment',
    recoveryDemand: 'low',
    styleTags: ['recovery'],
    secondaryOutcomeTags: ['mobility', 'consistency'],
    focusAreaTags: ['mobility'],
    lowFriction: true,
    jointFriendly: true,
  }),
  defineProgram('tpl_3_day_run_mobility_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['run_mobility', 'general'],
    backupGoals: [],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'low_equipment',
    recoveryDemand: 'moderate',
    styleTags: ['conditioning', 'balanced'],
    secondaryOutcomeTags: ['conditioning', 'mobility'],
    focusAreaTags: ['conditioning'],
    jointFriendly: true,
  }),
  defineProgram('tpl_shred_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['lean_athletic', 'general'],
    backupGoals: ['general_fitness', 'muscle'],
    supportedLevels: ['beginner', 'advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['conditioning', 'balanced'],
    secondaryOutcomeTags: ['conditioning', 'consistency'],
    focusAreaTags: ['conditioning', 'legs'],
    lowFriction: true,
  }),
  defineProgram('tpl_huge_starter_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general', 'general_fitness'],
    supportedLevels: ['beginner'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'low',
    styleTags: ['pump', 'express'],
    secondaryOutcomeTags: ['muscle', 'consistency'],
    focusAreaTags: ['chest', 'back', 'legs'],
    lowFriction: true,
    jointFriendly: true,
  }),
  defineProgram('tpl_focus_chest_program_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'shoulders', 'arms'],
  }),
  defineProgram('tpl_focus_back_program_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['back', 'arms'],
  }),
  defineProgram('tpl_focus_arms_program_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['arms', 'shoulders'],
  }),
  defineProgram('tpl_focus_legs_program_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness', 'strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['legs', 'quads', 'hamstrings', 'calves'],
  }),
  defineProgram('tpl_focus_glutes_program_v1', {
    familyId: 'glute_priority',
    supportedGoals: ['muscle'],
    backupGoals: ['lean_athletic', 'general_fitness'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'moderate',
    styleTags: ['pump', 'balanced'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['glutes', 'hamstrings', 'legs'],
  }),
  // ── The top of each family ──────────────────────────────────────────────
  // These existed in the catalog with written copy and were reachable only by
  // browsing: nothing registered them here, so no set of onboarding answers
  // could ever produce them. That left the "pro" level with nothing above the
  // intermediate tier to hand out — it behaved exactly like "advanced".
  defineProgram('tpl_strong_elite_v1', {
    familyId: 'strength_base',
    supportedGoals: ['strength'],
    backupGoals: ['muscle', 'general_fitness'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['heavy'],
    secondaryOutcomeTags: ['strength'],
    focusAreaTags: ['back', 'legs', 'chest'],
  }),
  defineProgram('tpl_fit_elite_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['general', 'general_fitness'],
    backupGoals: ['lean_athletic', 'muscle'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['balanced', 'conditioning'],
    secondaryOutcomeTags: ['conditioning', 'strength'],
    focusAreaTags: ['core', 'legs', 'back'],
  }),
  defineProgram('tpl_shred_elite_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['lean_athletic', 'general_fitness'],
    backupGoals: ['general', 'muscle'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['conditioning', 'balanced'],
    secondaryOutcomeTags: ['conditioning'],
    focusAreaTags: ['core', 'legs'],
  }),
  defineProgram('tpl_6_day_arnold_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'back', 'arms', 'shoulders'],
  }),
  defineProgram('tpl_gainer_expert_powerbuilding_v1', {
    familyId: 'powerbuilding',
    supportedGoals: ['strength', 'muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['heavy', 'pump'],
    secondaryOutcomeTags: ['strength', 'muscle'],
    focusAreaTags: ['back', 'legs', 'chest'],
  }),
  defineProgram('tpl_gainer_athlete_conditioning_v1', {
    familyId: 'athletic_recomp',
    supportedGoals: ['lean_athletic', 'general_fitness'],
    backupGoals: ['general', 'run_mobility'],
    supportedLevels: ['pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['conditioning', 'balanced'],
    secondaryOutcomeTags: ['conditioning'],
    focusAreaTags: ['core', 'legs'],
  }),
  defineProgram('tpl_gainer_calisthenics_mastery_v1', {
    familyId: 'low_equipment',
    supportedGoals: ['muscle', 'general_fitness'],
    backupGoals: ['lean_athletic', 'general'],
    supportedLevels: ['pro'],
    // The one advanced program that needs no gym: without it a home lifter
    // past the beginner tier had nothing but beginner content.
    equipmentTier: 'low_equipment',
    recoveryDemand: 'moderate',
    styleTags: ['balanced', 'pump'],
    secondaryOutcomeTags: ['muscle', 'consistency'],
    focusAreaTags: ['core', 'arms', 'chest', 'back'],
  }),

  // ── The high-frequency middle of HUGE ───────────────────────────────────
  // Four, five and six sessions a week existed with nothing registered to
  // serve them, so asking for five days got a four-day program every time.
  defineProgram('tpl_4_day_ppl_plus_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness', 'strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'back', 'legs'],
  }),
  defineProgram('tpl_5_day_ppl_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump'],
    secondaryOutcomeTags: ['muscle'],
    focusAreaTags: ['chest', 'back', 'legs', 'arms'],
  }),
  defineProgram('tpl_5_day_upper_lower_full_v1', {
    familyId: 'mass_hypertrophy',
    supportedGoals: ['muscle'],
    backupGoals: ['general_fitness', 'strength'],
    supportedLevels: ['advanced', 'pro'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'high',
    styleTags: ['pump'],
    secondaryOutcomeTags: ['muscle', 'strength'],
    focusAreaTags: ['back', 'legs', 'chest'],
  }),

  // ── Joint-friendly, for the mobility branch that asks for this family ────
  defineProgram('tpl_gainer_joint_friendly_v1', {
    familyId: 'joint_friendly',
    supportedGoals: ['general', 'general_fitness'],
    backupGoals: ['muscle', 'run_mobility'],
    supportedLevels: ['beginner'],
    equipmentTier: 'full_gym',
    recoveryDemand: 'low',
    styleTags: ['balanced', 'recovery'],
    secondaryOutcomeTags: ['mobility', 'consistency'],
    focusAreaTags: ['core', 'legs', 'back'],
    lowFriction: true,
    jointFriendly: true,
  }),

  ...Vinha_PROGRAM_RECOMMENDATIONS.map((program) => defineProgram(program.programId, program)),
];

export function getRecommendationProgramDefinition(programId: string) {
  return RECOMMENDATION_PROGRAMS.find((entry) => entry.programId === programId) ?? null;
}
