/**
 * Compile-freshness gate. Runs before the first require, because the suites
 * themselves load .test-dist.
 *
 * The trap this closes has bitten more than once: tests import compiled
 * output, so editing src/ and re-running gives a green suite that proves
 * yesterday's code — and deleting a src file leaves its compiled module
 * behind, still importable, still green. "rm -rf .test-dist before trusting
 * green" lived in a note; now the runner refuses on its own.
 */
{
  const fs = require('node:fs');
  const path = require('node:path');
  const root = path.join(__dirname, '..');
  const srcDir = path.join(root, 'src');
  const distDir = path.join(root, '.test-dist');

  const walk = (dir, ext, out = []) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full, ext, out);
      else if (entry.name.endsWith(ext)) out.push(full);
    }
    return out;
  };

  const problems = [];
  if (!fs.existsSync(distDir)) {
    problems.push('.test-dist does not exist');
  } else {
    for (const source of walk(srcDir, '.ts')) {
      if (source.endsWith('.d.ts')) continue;
      const rel = path.relative(srcDir, source);
      const compiled = path.join(distDir, rel.replace(/\.ts$/, '.js'));
      if (!fs.existsSync(compiled)) {
        problems.push(`never compiled: src/${rel}`);
      } else if (fs.statSync(compiled).mtimeMs < fs.statSync(source).mtimeMs) {
        problems.push(`older than its source: src/${rel}`);
      }
    }

    for (const compiled of walk(distDir, '.js')) {
      const rel = path.relative(distDir, compiled);
      // tsc follows imports beyond the include list, so a compiled module's
      // source can be .ts or .tsx.
      const stem = path.join(srcDir, rel.replace(/\.js$/, ''));
      if (!fs.existsSync(`${stem}.ts`) && !fs.existsSync(`${stem}.tsx`)) {
        problems.push(`source deleted but still compiled: .test-dist/${rel}`);
      } else if (
        fs.existsSync(`${stem}.tsx`) &&
        fs.statSync(compiled).mtimeMs < fs.statSync(`${stem}.tsx`).mtimeMs
      ) {
        // .tsx staleness lands here; the src walk above only sees .ts.
        problems.push(`older than its source: ${path.relative(root, `${stem}.tsx`)}`);
      }
    }
  }

  if (problems.length > 0) {
    console.error('.test-dist does not match src/ — a green run would prove nothing:');
    for (const problem of problems.slice(0, 15)) {
      console.error(`  ${problem}`);
    }
    if (problems.length > 15) {
      console.error(`  ...and ${problems.length - 15} more`);
    }
    console.error('\nRecompile first:');
    console.error('  Remove-Item -Recurse -Force .test-dist; npx tsc -p tsconfig.test.json');
    process.exit(1);
  }
}

const suites = [
  ...require('./releaseReadiness.test.cjs'),
  ...require('./scripts/slackNotify.test.cjs'),
  ...require('./scripts/releaseGuard.test.cjs'),
  ...require('./scripts/claudeReviewWorkflow.test.cjs'),
  ...require('./lib/appIcon.test.cjs'),
  ...require('./lib/proBenefits.test.cjs'),
  ...require('./features/workout/workoutAppAdapter.test.cjs'),
  ...require('./features/workout/workoutState.test.cjs'),
  ...require('./features/workout/supersetSession.test.cjs'),
  ...require('./features/workout/removeSet.test.cjs'),
  ...require('./features/workout/editLoggedSet.test.cjs'),
  ...require('./features/workout/loggedHistory.test.cjs'),
  ...require('./features/workout/borrowedPrefill.test.cjs'),
  ...require('./features/workout/nextSessionPreview.test.cjs'),
  ...require('./features/workout/historyBelongsToLift.test.cjs'),
  ...require('./features/workout/swapIsTheLift.test.cjs'),
  ...require('./features/workout/workoutLifecycleInvariant.test.cjs'),
  ...require('./features/workout/addedThenSwappedBasis.test.cjs'),
  ...require('./features/workout/repeatLastAfterSwap.test.cjs'),
  ...require('./features/workout/guidedPlayerReliability.test.cjs'),
  ...require('./features/workout/resetClearsHistory.test.cjs'),
  ...require('./features/workout/setWeightInvariant.test.cjs'),
  ...require('./state/completedWorkoutPersistence.test.cjs'),
  ...require('./state/commitSavesPreferences.test.cjs'),
  ...require('./state/writesWaitForLoad.test.cjs'),
  ...require('./state/commitRollsBack.test.cjs'),
  ...require('./utils/haptics.test.cjs'),
  ...require('./utils/reduceMotion.test.cjs'),
  ...require('./utils/sessionNotifications.test.cjs'),
  ...require('./utils/scheduledNotificationsHydration.test.cjs'),
  ...require('./components/primaryCTAButton.test.cjs'),
  ...require('./components/sessionAnalysisScreen.test.cjs'),
  ...require('./components/supersetBorder.test.cjs'),
  ...require('./integration/liveWorkoutSavePipeline.test.cjs'),
  ...require('./lib/workoutInput.test.cjs'),
  ...require('./lib/workoutContentFit.test.cjs'),
  ...require('./lib/sessionGuidance.test.cjs'),
  ...require('./lib/guidedPlayer.test.cjs'),
  ...require('./lib/libraryLookupCache.test.cjs'),
  ...require('./lib/startupWorkBudget.test.cjs'),
  ...require('./lib/guidedClockHold.test.cjs'),
  ...require('./lib/sheetScrollBound.test.cjs'),
  ...require('./lib/guidedRunPreview.test.cjs'),
  ...require('./lib/guidedSetWeightSummary.test.cjs'),
  ...require('./lib/routineDrillSwap.test.cjs'),
  ...require('./lib/exerciseHistoryLookup.test.cjs'),
  ...require('./lib/prescribedInstructions.test.cjs'),
  ...require('./lib/exerciseLearning.test.cjs'),
  ...require('./lib/exerciseTeaching.test.cjs'),
  ...require('./lib/exerciseCollections.test.cjs'),
  ...require('./lib/programLadder.test.cjs'),
  ...require('./lib/programCatalogFilter.test.cjs'),
  ...require('./lib/strengthGoalPlan.test.cjs'),
  ...require('./lib/plainExerciseNames.test.cjs'),
  ...require('./lib/sessionAdaptation.test.cjs'),
  ...require('./lib/liftSegments.test.cjs'),
  ...require('./lib/swapTrackingMode.test.cjs'),
  ...require('./lib/typedIsLogged.test.cjs'),
  ...require('./lib/sessionDuration.test.cjs'),
  ...require('./lib/sessionOverviewRows.test.cjs'),
  ...require('./lib/ownBlockHistory.test.cjs'),
  ...require('./lib/warmupBrief.test.cjs'),
  ...require('./lib/warmupLadder.test.cjs'),
  ...require('./lib/exerciseSheetHistory.test.cjs'),
  ...require('./lib/sessionMovement.test.cjs'),
  ...require('./lib/holdTracking.test.cjs'),
  ...require('./lib/minutesTracking.test.cjs'),
  ...require('./lib/cardio.test.cjs'),
  ...require('./lib/cardioAudit.test.cjs'),
  ...require('./lib/activeWorkout.test.cjs'),
  ...require('./lib/guidedSaveTarget.test.cjs'),
  ...require('./lib/boardResave.test.cjs'),
  ...require('./state/cardioResave.test.cjs'),
  ...require('./lib/workoutLoggerNavigation.test.cjs'),
  ...require('./lib/exerciseSuggestions.test.cjs'),
  ...require('./lib/routeHistory.test.cjs'),
  ...require('./lib/completedSessions.test.cjs'),
  ...require('./lib/dashboard.test.cjs'),
  ...require('./lib/progressionActivePlan.test.cjs'),
  ...require('./lib/progressionSignal.test.cjs'),
  ...require('./lib/exerciseProgressForName.test.cjs'),
  ...require('./lib/liftHistoryIdentity.test.cjs'),
  ...require('./lib/lifetimeSummary.test.cjs'),
  ...require('./lib/bugHunt20261004Records.test.cjs'),
  ...require('./lib/bugHunt20261004Followups.test.cjs'),
  ...require('./lib/profileOverview.test.cjs'),
  ...require('./lib/homeStatCards.test.cjs'),
  ...require('./lib/homeStatCardGroups.test.cjs'),
  ...require('./storage/measurementKinds.test.cjs'),
  ...require('./lib/measurementReminder.test.cjs'),
  ...require('./lib/homePrompts.test.cjs'),
  ...require('./lib/firstRunTour.test.cjs'),
  ...require('./screens/firstRunTourWiring.test.cjs'),
  ...require('./screens/audit7Wiring.test.cjs'),
  ...require('./lib/homeCardSuggestions.test.cjs'),
  ...require('./lib/ratingPrompt.test.cjs'),
  ...require('./lib/storeLinks.test.cjs'),
  ...require('./lib/blurredPreviewText.test.cjs'),
  ...require('./lib/bodyweightCard.test.cjs'),
  ...require('./lib/bodyweightSeedOnce.test.cjs'),
  ...require('./lib/accountNameAdoption.test.cjs'),
  ...require('./lib/programFamilyIdentity.test.cjs'),
  ...require('./lib/programCatalogFocus.test.cjs'),
  ...require('./lib/seasonEnrolment.test.cjs'),
  ...require('./lib/deviceLanguage.test.cjs'),
  ...require('./lib/i18n.test.cjs'),
  ...require('./lib/finnishTerms.test.cjs'),
  ...require('./lib/trainingRhythm.test.cjs'),
  ...require('./lib/progressionAnalyzer.test.cjs'),
  ...require('./lib/fatigueModel.test.cjs'),
  ...require('./lib/progressNumbers.test.cjs'),
  ...require('./lib/progressActivity.test.cjs'),
  ...require('./lib/postSessionInsight.test.cjs'),
  ...require('./lib/proEntitlement.test.cjs'),
  ...require('./lib/proEntitlementRestore.test.cjs'),
  ...require('./lib/proLock.test.cjs'),
  ...require('./lib/proTiers.test.cjs'),
  ...require('./lib/runningProgrammes.test.cjs'),
  ...require('./lib/proSurfaces.test.cjs'),
  ...require('./lib/subscriptionView.test.cjs'),
  ...require('./lib/cancelSurvey.test.cjs'),
  ...require('./lib/legalDocuments.test.cjs'),
  ...require('./lib/accountDeletionPage.test.cjs'),
  ...require('./lib/legalAcceptance.test.cjs'),
  ...require('./lib/legalLinks.test.cjs'),
  ...require('./lib/transcriptEntry.test.cjs'),
  ...require('./lib/notificationPlan.test.cjs'),
  ...require('./lib/planNotificationSync.test.cjs'),
  ...require('./lib/programCsvExport.test.cjs'),
  ...require('./lib/setupHandoff.test.cjs'),
  ...require('./lib/quickLayoutExercises.test.cjs'),
  ...require('./lib/templateBuilderSteps.test.cjs'),
  ...require('./lib/exerciseSearch.test.cjs'),
  ...require('./lib/exerciseSearchWords.test.cjs'),
  ...require('./lib/exerciseListLabel.test.cjs'),
  ...require('./lib/libraryLabel.test.cjs'),
  ...require('./lib/goalProgramme.test.cjs'),
  ...require('./lib/liftIdentity.test.cjs'),
  ...require('./lib/programmeBrief.test.cjs'),
  ...require('./lib/programIntake.test.cjs'),
  ...require('./lib/widgetPayload.test.cjs'),
  ...require('./lib/widgetResources.test.cjs'),
  ...require('./lib/theming.test.cjs'),
  ...require('./lib/proInsights.test.cjs'),
  ...require('./lib/aiCoachQuota.test.cjs'),
  ...require('./lib/coachChat.test.cjs'),
  ...require('./lib/coachDemoMoments.test.cjs'),
  ...require('./lib/coachSmallTalk.test.cjs'),
  ...require('./lib/coachConversation.test.cjs'),
  ...require('./lib/analytics.test.cjs'),
  ...require('./lib/analyticsRetention.test.cjs'),
  ...require('./lib/analyticsMoments.test.cjs'),
  ...require('./lib/analyticsRead.test.cjs'),
  ...require('./api/eventsEndpoint.test.cjs'),
  ...require('./lib/errorReport.test.cjs'),
  ...require('./api/eventsErrors.test.cjs'),
  ...require('./features/errorReporting/errorReporting.test.cjs'),
  ...require('./scripts/analyticsReport.test.cjs'),
  ...require('./screens/analyticsTruth.test.cjs'),
  ...require('./lib/coachSuggestions.test.cjs'),
  ...require('./lib/aiCoachCostModel.test.cjs'),
  ...require('./lib/trainingCalendar.test.cjs'),
  ...require('./lib/trainingHistory.test.cjs'),
  ...require('./lib/serialTaskQueue.test.cjs'),
  ...require('./lib/catalogExercisePools.test.cjs'),
  ...require('./lib/libraryEquipment.test.cjs'),
  ...require('./lib/onboardingPlanSweep.test.cjs'),
  ...require('./lib/progressionGate.test.cjs'),
  ...require('./lib/progressionPerSet.test.cjs'),
  ...require('./lib/missedRepsTarget.test.cjs'),
  ...require('./lib/coachChatMemory.test.cjs'),
  ...require('./lib/coachAdviceMemory.test.cjs'),
  ...require('./lib/entryDeletion.test.cjs'),
  ...require('./lib/readyProgrammeCopy.test.cjs'),
  ...require('./lib/successToasts.test.cjs'),
  ...require('./lib/programSessionEdit.test.cjs'),
  ...require('./lib/supersetGrouping.test.cjs'),
  ...require('./lib/guidedSuperset.test.cjs'),
  ...require('./lib/supersetAcrossSurfaces.test.cjs'),
  ...require('./lib/supersetsSurviveSaves.test.cjs'),
  ...require('./lib/catalogSupersets.test.cjs'),
  ...require('./lib/programSessionOrder.test.cjs'),
  ...require('./lib/programSessionList.test.cjs'),
  ...require('./lib/emptyProgrammeDays.test.cjs'),
  ...require('./lib/recoverySheet.test.cjs'),
  ...require('./lib/recoveryWeekAgreement.test.cjs'),
  ...require('./lib/planSessionOrder.test.cjs'),
  ...require('./lib/weightDial.test.cjs'),
  ...require('./lib/welcomeMarquee.test.cjs'),
  ...require('./lib/programSlots.test.cjs'),
  ...require('./lib/programLimitNotice.test.cjs'),
  ...require('./lib/programSeasons.test.cjs'),
  ...require('./lib/personalRecords.test.cjs'),
  ...require('./lib/progression.test.cjs'),
  ...require('./lib/exerciseLog.test.cjs'),
  ...require('./lib/serverNotice.test.cjs'),
  ...require('./lib/loggedSetPlan.test.cjs'),
  ...require('./lib/workoutCompletionCards.test.cjs'),
  ...require('./lib/recordDefinitionAgreement.test.cjs'),
  ...require('./lib/deadLibModules.test.cjs'),
  ...require('./lib/sessionFeel.test.cjs'),
  ...require('./lib/exerciseNameBook.test.cjs'),
  ...require('./lib/programImageImport.test.cjs'),
  ...require('./lib/recordWindow.test.cjs'),
  ...require('./lib/exerciseSetLog.test.cjs'),
  ...require('./lib/logRecordedWork.test.cjs'),
  ...require('./lib/authoredProgramCount.test.cjs'),
  ...require('./lib/uncalledExports.test.cjs'),
  ...require('./lib/cutCorner.test.cjs'),
  ...require('./lib/formatPercent.test.cjs'),
  ...require('./lib/appWrittenNamesTranslated.test.cjs'),
  ...require('./lib/numericDates.test.cjs'),
  ...require('./lib/programEquipment.test.cjs'),
  ...require('./lib/programEquipmentBucket.test.cjs'),
  ...require('./lib/progressionRuleLabel.test.cjs'),
  ...require('./lib/singleRepTarget.test.cjs'),
  ...require('./lib/onboardingRepTarget.test.cjs'),
  ...require('./lib/intervalScheme.test.cjs'),
  ...require('./lib/todaySessionPick.test.cjs'),
  ...require('./lib/programBrowse.test.cjs'),
  ...require('./lib/readyProgramCards.test.cjs'),
  ...require('./lib/exerciseInstructionsFi.test.cjs'),
  ...require('./lib/buildArchitectures.test.cjs'),
  ...require('./lib/season.test.cjs'),
  ...require('./lib/programCategories.test.cjs'),
  ...require('./lib/programFingerprint.test.cjs'),
  ...require('./lib/strengthGoals.test.cjs'),
  ...require('./lib/historyWindow.test.cjs'),
  ...require('./lib/workoutLogCsvExport.test.cjs'),
  ...require('./lib/aiCoachBudget.test.cjs'),
  ...require('./lib/aiCoachLiveGate.test.cjs'),
  ...require('./lib/aiCoachAppKey.test.cjs'),
  ...require('./lib/appUpdateGate.test.cjs'),
  ...require('./lib/aiLogConsent.test.cjs'),
  ...require('./lib/accountBackup.test.cjs'),
  ...require('./lib/accountBackupCompression.test.cjs'),
  ...require('./features/account/accountBackupHook.test.cjs'),
  ...require('./features/account/appleAuth.test.cjs'),
  ...require('./features/account/backupApiDelete.test.cjs'),
  ...require('./features/account/backupSync.test.cjs'),
  ...require('./lib/accountRestoreAwaitsErase.test.cjs'),
  ...require('./features/account/signedOutAccounts.test.cjs'),
  ...require('./features/account/accountSession.test.cjs'),
  ...require('./features/account/accountSafetyInvariant.test.cjs'),
  ...require('./features/account/backupRoundTripInvariant.test.cjs'),
  ...require('./features/account/googleFreshTokenSub.test.cjs'),
  ...require('./api/backupEndpoint.test.cjs'),
  ...require('./api/backupWebDeletion.test.cjs'),
  ...require('./api/backupAppleSession.test.cjs'),
  ...require('./state/accountBackupWiring.test.cjs'),
  ...require('./lib/hevyImport.test.cjs'),
  ...require('./lib/csvRecords.test.cjs'),
  ...require('./lib/measurementIntent.test.cjs'),
  ...require('./lib/goalIntent.test.cjs'),
  ...require('./lib/aiCoachBody.test.cjs'),
  ...require('./lib/aiCoachEval.test.cjs'),
  ...require('./lib/aiCoachEvalMatrix.test.cjs'),
  ...require('./api/aiCoachEndpoint.test.cjs'),
  ...require('./api/aiCoachLimits.test.cjs'),
  ...require('./lib/aiCoachContextCap.test.cjs'),
  ...require('./lib/coachKeyHealth.test.cjs'),
  ...require('./lib/aiCoachModules.test.cjs'),
  ...require('./lib/sessionAnalysis.test.cjs'),
  ...require('./lib/coachHighlight.test.cjs'),
  ...require('./lib/homeProgramSelection.test.cjs'),
  ...require('./lib/homePlanProgress.test.cjs'),
  ...require('./lib/homeSessionHero.test.cjs'),
  ...require('./lib/sessionFocusClassification.test.cjs'),
  ...require('./lib/substitutionGroups.test.cjs'),
  ...require('./lib/workoutCompleteView.test.cjs'),
  ...require('./lib/homeCalendar.test.cjs'),
  ...require('./lib/trainingSchedule.test.cjs'),
  ...require('./lib/planTrainingCycle.test.cjs'),
  ...require('./lib/trainingScheduleZones.test.cjs'),
  ...require('./lib/homePlanBugHunt41004.test.cjs'),
  ...require('./lib/trainingWeekLoad.test.cjs'),
  ...require('./lib/readableOn.test.cjs'),
  ...require('./lib/workoutPauseClock.test.cjs'),
  ...require('./lib/sessionClock.test.cjs'),
  ...require('./lib/sessionClockWindow.test.cjs'),
  ...require('./lib/programmeDeletion.test.cjs'),
  ...require('./screens/programmeCopyRollback.test.cjs'),
  ...require('./features/workout/liveWorkoutKept.test.cjs'),
  ...require('./features/workout/warmupSets.test.cjs'),
  ...require('./features/workout/warmupMovement.test.cjs'),
  ...require('./features/workout/warmupSwapCount.test.cjs'),
  ...require('./features/workout/rampTargets.test.cjs'),
  ...require('./screens/liveWorkoutWiring.test.cjs'),
  ...require('./screens/workoutSaveLock.test.cjs'),
  ...require('./lib/historyDelete.test.cjs'),
  ...require('./screens/guidedPlayerSwap.test.cjs'),
  ...require('./screens/guidedPlayerSetWeightsVisible.test.cjs'),
  ...require('./screens/guidedPlayerAddExercise.test.cjs'),
  ...require('./screens/sessionAdaptationWiring.test.cjs'),
  ...require('./screens/exerciseSheet.test.cjs'),
  ...require('./screens/keyboardPersistTaps.test.cjs'),
  ...require('./screens/onboardingCopyLink.test.cjs'),
  ...require('./screens/homeWeekTruth.test.cjs'),
  ...require('./screens/weekAndDayTruth.test.cjs'),
  ...require('./screens/programmeHeld.test.cjs'),
  ...require('./screens/freestyleSurvives.test.cjs'),
  ...require('./screens/resumeIntent.test.cjs'),
  ...require('./screens/teachingSections.test.cjs'),
  ...require('./screens/completionHero.test.cjs'),
  ...require('./screens/leadProgram.test.cjs'),
  ...require('./lib/aiTrainingContext.test.cjs'),
  ...require('./lib/coachLocalDates.test.cjs'),
  ...require('./lib/aiCoachSystemContext.test.cjs'),
  ...require('./lib/coachLastSession.test.cjs'),
  ...require('./lib/coachRound30_9.test.cjs'),
  ...require('./lib/aiCoachAnswerDecimals.test.cjs'),
  ...require('./lib/aiCoachAnswerExtras.test.cjs'),
  ...require('./lib/coachAnswerReport.test.cjs'),
  ...require('./lib/breakRoundApp.test.cjs'),
  ...require('./lib/aiCoachProgramme.test.cjs'),
  ...require('./lib/coachComposeOffer.test.cjs'),
  ...require('./lib/briefProgrammeMatch.test.cjs'),
  ...require('./lib/extraExerciseLibrary.test.cjs'),
  ...require('./lib/sessionDrops.test.cjs'),
  ...require('./lib/programCapNotice.test.cjs'),
  ...require('./lib/exerciseBrowseFilter.test.cjs'),
  ...require('./lib/swapShortlist.test.cjs'),
  ...require('./lib/swapBrowsePrefilter.test.cjs'),
  ...require('./lib/swapPickerLists.test.cjs'),
  ...require('./lib/exerciseFilterInvariants.test.cjs'),
  ...require('./lib/pickerRules.test.cjs'),
  ...require('./lib/programFilterInvariants.test.cjs'),
  ...require('./lib/exerciseMechanicTruth.test.cjs'),
  ...require('./lib/trackingCategoryMigration.test.cjs'),
  ...require('./lib/coachProgrammeTracking.test.cjs'),
  ...require('./lib/equipmentBuckets.test.cjs'),
  ...require('./lib/librarySweep.test.cjs'),
  ...require('./lib/drillsAreNotSets.test.cjs'),
  ...require('./lib/pickerAuditClassification.test.cjs'),
  ...require('./lib/aiCoachPreview.test.cjs'),
  ...require('./lib/aiCoachScope.test.cjs'),
  ...require('./lib/coachChipAnswers.test.cjs'),
  ...require('./lib/displayLabel.test.cjs'),
  ...require('./lib/decimalSeparator.test.cjs'),
  ...require('./lib/localizedFormatting.test.cjs'),
  ...require('./lib/tailoringFit.test.cjs'),
  ...require('./lib/recommendationExplanation.test.cjs'),
  ...require('./lib/recommendationProfile.test.cjs'),
  ...require('./lib/recommendationPresentation.test.cjs'),
  ...require('./lib/recommendationProgramme.test.cjs'),
  ...require('./lib/csvProgramImport.test.cjs'),
  ...require('./lib/recommendationScoring.test.cjs'),
  ...require('./lib/recommendationBackfill.test.cjs'),
  ...require('./lib/recommendationWaterfall.test.cjs'),
  ...require('./lib/recommendationReach.test.cjs'),
  ...require('./lib/recommendationAccuracy.test.cjs'),
  ...require('./lib/recommendationFixes20261005.test.cjs'),
  ...require('./lib/recommendationFixes20261006.test.cjs'),
  ...require('./lib/reviewFixes20261007.test.cjs'),
  ...require('./lib/swapHunt20261007.test.cjs'),
  ...require('./lib/sessionMinutesOneTruth.test.cjs'),
  ...require('./lib/catalogGapProgrammes20261005.test.cjs'),
  ...require('./lib/readyProgrammeAudit.test.cjs'),
  ...require('./lib/recommendationWaterfallCopy.test.cjs'),
  ...require('./lib/firstRunSetup.test.cjs'),
  ...require('./lib/focusAreaPresentation.test.cjs'),
  ...require('./lib/programFocusSplit.test.cjs'),
  ...require('./lib/programDayComposer.test.cjs'),
  ...require('./lib/cautionExerciseFilter.test.cjs'),
  ...require('./lib/cautionNameMatching.test.cjs'),
  ...require('./lib/sourceEncoding.test.cjs'),
  ...require('./lib/focusEmphasis.test.cjs'),
  ...require('./lib/equipmentExerciseFilter.test.cjs'),
  ...require('./lib/programmeMinutes.test.cjs'),
  ...require('./lib/savedCopyFidelity.test.cjs'),
  ...require('./lib/programEquipmentFit.test.cjs'),
  ...require('./lib/onboardingStructure.test.cjs'),
  ...require('./screens/homeScreenStructure.test.cjs'),
  ...require('./screens/historyScrollWiring.test.cjs'),
  ...require('./lib/progressChartTicks.test.cjs'),
  ...require('./screens/progressTrend.test.cjs'),
  ...require('./screens/programsHomeStructure.test.cjs'),
  ...require('./screens/programPlanOverview.test.cjs'),
  ...require('./screens/addExerciseSheet.test.cjs'),
  ...require('./screens/pickerWiring.test.cjs'),
  ...require('./screens/equipmentLabelWiring.test.cjs'),
  ...require('./screens/cardioPlayer.test.cjs'),
  ...require('./screens/cardioAuditWiring.test.cjs'),
  ...require('./screens/emptyWorkoutRestBar.test.cjs'),
  ...require('./screens/emptyWorkoutHeader.test.cjs'),
  ...require('./screens/emptyWorkoutGuards.test.cjs'),
  ...require('./screens/onboardingShellInsets.test.cjs'),
  ...require('./screens/startPathChoices.test.cjs'),
  ...require('./screens/restAlertsAsk.test.cjs'),
  ...require('./screens/restAlertsBanner.test.cjs'),
  ...require('./screens/preferenceToggleSnapshots.test.cjs'),
  ...require('./screens/weekEditAndDayDoor.test.cjs'),
  ...require('./lib/profileMilestones.test.cjs'),
  ...require('./lib/milestoneLedger.test.cjs'),
  ...require('./lib/notificationGroups.test.cjs'),
  ...require('./screens/notificationGroups.test.cjs'),
  ...require('./screens/settingsAccountRows.test.cjs'),
  ...require('./screens/notificationsScheduledRecheck.test.cjs'),
  ...require('./screens/searchRankingReachesTheList.test.cjs'),
  ...require('./screens/profileMilestoneSection.test.cjs'),
  ...require('./screens/milestonesScreen.test.cjs'),
  ...require('./screens/proScreens34.test.cjs'),
  ...require('./lib/countWord.test.cjs'),
  ...require('./screens/proScreens12.test.cjs'),
  ...require('./screens/settingsSurfaces.test.cjs'),
  ...require('./lib/aiLogDeletion.test.cjs'),
  ...require('./lib/restAlertAnswer.test.cjs'),
  ...require('./lib/notificationAccessState.test.cjs'),
  ...require('./lib/reminderOptIn.test.cjs'),
  ...require('./lib/reminderSchedule.test.cjs'),
  ...require('./screens/onboardingVisualPolish.test.cjs'),
  ...require('./screens/headerBackReachable.test.cjs'),
  ...require('./lib/workoutDiscovery.test.cjs'),
  ...require('./lib/impossibleLoads.test.cjs'),
  ...require('./lib/notificationRoute.test.cjs'),
  ...require('./lib/historyView.test.cjs'),
  ...require('./lib/historyScrollMemory.test.cjs'),
  ...require('./lib/programDetails.test.cjs'),
  ...require('./lib/programPickSeam.test.cjs'),
  ...require('./lib/finnishHyphenation.test.cjs'),
  ...require('./lib/programmeRouteTruth.test.cjs'),
  ...require('./lib/customProgramDuplication.test.cjs'),
  ...require('./lib/programRename.test.cjs'),
  ...require('./lib/programInsights.test.cjs'),
  ...require('./lib/readyProgramCatalog.test.cjs'),
  ...require('./lib/readyProgramCollections.test.cjs'),
  ...require('./lib/readyProgramDuration.test.cjs'),
  ...require('./lib/workoutTemplateSessions.test.cjs'),
  ...require('./lib/workoutEditorNaming.test.cjs'),
  ...require('./lib/plateMath.test.cjs'),
  ...require('./lib/programAdoption.test.cjs'),
  ...require('./lib/planRotation.test.cjs'),
  ...require('./lib/programLineage.test.cjs'),
  ...require('./lib/programmeCopyLink.test.cjs'),
  ...require('./integration/planRotationAdvances.test.cjs'),
  ...require('./lib/programTrainingDays.test.cjs'),
  ...require('./lib/trainingWeekSync.test.cjs'),
  ...require('./lib/restSchedule.test.cjs'),
  ...require('./lib/restActionBus.test.cjs'),
  ...require('./screens/summaryBackExit.test.cjs'),
  ...require('./lib/programCompletion.test.cjs'),
  ...require('./screens/completionCardSourceLink.test.cjs'),
  ...require('./lib/programEmphasis.test.cjs'),
  ...require('./lib/programEmphasisAdjust.test.cjs'),
  ...require('./lib/activeProgramSet.test.cjs'),
  ...require('./lib/programCapWiring.test.cjs'),
  ...require('./lib/emptyWorkoutSession.test.cjs'),
  ...require('./lib/exerciseSelectionOrder.test.cjs'),
  ...require('./lib/restPreference.test.cjs'),
  ...require('./lib/sessionNameLabel.test.cjs'),
  ...require('./lib/readyProgramContentFi.test.cjs'),
  ...require('./lib/exerciseNameLabel.test.cjs'),
  ...require('./storage/firstLaunchIsEmpty.test.cjs'),
  ...require('./storage/corruptDatabase.test.cjs'),
  ...require('./storage/loaderJunk.test.cjs'),
  ...require('./storage/workoutBundleJunk.test.cjs'),
  ...require('./storage/prescriptionRoundTrip.test.cjs'),
  ...require('./storage/runningSetMatchesPlans.test.cjs'),
  ...require('./lib/storageChunks.test.cjs'),
  ...require('./storage/largeItem.test.cjs'),
  ...require('./storage/workoutAside.test.cjs'),
  ...require('./storage/coachAdviceMemoryStore.test.cjs'),
  ...require('./storage/preferencesWithBlob.test.cjs'),
  ...require('./storage/loadWithRetry.test.cjs'),
  ...require('./storage/longHistoryLoads.test.cjs'),
  ...require('./storage/resetKeepsInstall.test.cjs'),
  ...require('./lib/storageSize.test.cjs'),
  ...require('./lib/allowBackup.test.cjs'),
  ...require('./lib/dataExtractionRules.test.cjs'),
  ...require('./lib/androidPermissions.test.cjs'),
  ...require('./storage/preferenceBounds.test.cjs'),
  ...require('./lib/untranslatedCopy.test.cjs'),
  ...require('./lib/homeCalendarPaging.test.cjs'),
  ...require('./lib/drillMedia.test.cjs'),
  ...require('./lib/userFitnessProfile.test.cjs'),
  ...require('./lib/calendarDayCounts.test.cjs'),
  ...require('./lib/setupSeed.test.cjs'),
  ...require('./screens/onboardingEntryAndSaves.test.cjs'),
  ...require('./screens/onePressOneWrite.test.cjs'),
  ...require('./lib/planTemplateSync.test.cjs'),
  ...require('./screens/audit3Promises.test.cjs'),
  ...require('./screens/audit3Numbers.test.cjs'),
  ...require('./screens/audit3Actions.test.cjs'),
  ...require('./screens/audit3DeadScreens.test.cjs'),
  ...require('./lib/sessionTotals.test.cjs'),
  ...require('./storage/loaderSessionTotals.test.cjs'),
  ...require('./storage/storageLoadInvariant.test.cjs'),
  ...require('./storage/trackingAfterCategoryCorrection.test.cjs'),
  ...require('./storage/minutesModeForOldCopies.test.cjs'),
  ...require('./lib/minutesLogEntry.test.cjs'),
  ...require('./lib/minutesClockSchedule.test.cjs'),
  ...require('./features/workout/minutesClockKept.test.cjs'),
  ...require('./features/workout/minutesClockSessionTime.test.cjs'),
  ...require('./features/workout/workoutLifecycleInvariant2.test.cjs'),
  ...require('./storage/storageLoadInvariant2.test.cjs'),
  ...require('./storage/minutesLegacyPlausible.test.cjs'),
  ...require('./lib/setCountChanges.test.cjs'),
  ...require('./storage/planEntryLabel.test.cjs'),
  ...require('./storage/corruptCopies.test.cjs'),
  ...require('./screens/oneCount.test.cjs'),
  ...require('./lib/themeContrast.test.cjs'),
  ...require('./lib/accessibilityLabels.test.cjs'),
  ...require('./screens/accessibilityAudit.test.cjs'),
  ...require('./screens/sheetBottomInset.test.cjs'),
  ...require('./screens/finishRouteGuard.test.cjs'),
  ...require('./screens/bugSweep20261001.test.cjs'),
  ...require('./screens/bugSweep20261004.test.cjs'),
];

(async () => {
  let failed = 0;

  for (const suite of suites) {
    try {
      // Await so async suites (e.g. serialTaskQueue) can actually fail; sync
      // suites are unaffected.
      await suite.run();
      console.log(`PASS ${suite.name}`);
    } catch (error) {
      failed += 1;
      console.error(`FAIL ${suite.name}`);
      console.error(error);
    }
  }

  if (failed > 0) {
    process.exitCode = 1;
    console.error(`\n${failed} test(s) failed.`);
  } else {
    console.log(`\n${suites.length} test(s) passed.`);
  }
})();
