"""Bundle the exercise pictures into the app.

The pictures used to be fetched from a public CDN when an exercise was
shown, which sent the user's IP address to a third party the privacy policy
does not name. They ship inside the APK instead (owner decision 2026-10-09), so
the app makes no request for them at all.

What this does, for every `imageKey` in src/data/generatedExerciseLibrary.ts:
  1. downloads <key>/0.jpg from yuhonas/free-exercise-db (Unlicense) once,
  2. resizes it to 720 px wide and saves it as WebP quality 75 in
     assets/exercises/<key lowercased>.webp (about 23 KB each; 480 px looked
     soft on the full-width exercise sheet, owner 2026-10-09),
  3. rewrites src/assets/exerciseImages.ts, the lazy map the app reads.

Only the first picture of an exercise is ever shown, so only that one is kept.

free-exercise-db reuses one photo for several different exercises. After the
files are written every byte-identical group is checked against
ACCEPTED_SHARED_FRAMES (frames that fairly picture each exercise using them),
and the run stops on any other. A key whose shared frame shows another
movement is in NO_PICTURE: it gets no file and no map entry, so the app shows
its placeholder (owner decision 2026-10-09). Both sets live in
scripts/exercise-pictures.json, which the library generator and
tests/lib/exerciseImagesBundled.test.cjs read too.
Existing .webp files are skipped, so re-running is cheap; delete a file to
refetch it. Run it (it needs Pillow with WebP, and the network) with:

    python -P scripts/bundle_exercise_images.py

`npm run exercise:sync` runs the library generator first and this after it.
"""

import hashlib
import io
import json
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LIBRARY = ROOT / "src" / "data" / "generatedExerciseLibrary.ts"
OUT_DIR = ROOT / "assets" / "exercises"
MAP_FILE = ROOT / "src" / "assets" / "exerciseImages.ts"
PICTURE_RULES = ROOT / "scripts" / "exercise-pictures.json"
SOURCE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{key}/0.jpg"
WIDTH = 720
QUALITY = 75
KEY_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")

_rules = json.loads(PICTURE_RULES.read_text(encoding="utf8"))
NO_PICTURE = frozenset(_rules["noPicture"])
ACCEPTED_SHARED_FRAMES = [frozenset(group) for group in _rules["acceptedSharedFrames"]]


def library_keys():
    text = LIBRARY.read_text(encoding="utf8")
    keys = sorted(set(re.findall(r'"imageKey": "([^"]+)"', text)), key=str.lower)
    for key in keys:
        if not KEY_PATTERN.match(key):
            sys.exit(f"Unsafe image key in the library: {key!r}")
    return [key for key in keys if key not in NO_PICTURE]


def unaccepted_shared_frames(keys):
    """Groups of keys whose written files are byte-identical and not allowlisted."""
    by_hash = {}
    for key in keys:
        digest = hashlib.sha1((OUT_DIR / file_name(key)).read_bytes()).hexdigest()
        by_hash.setdefault(digest, set()).add(key)
    return [
        sorted(group)
        for group in by_hash.values()
        if len(group) > 1 and not any(group <= accepted for accepted in ACCEPTED_SHARED_FRAMES)
    ]


def file_name(key):
    return key.lower() + ".webp"


def fetch(key):
    target = OUT_DIR / file_name(key)
    if target.exists():
        return key, "skipped"
    request = urllib.request.Request(
        SOURCE.format(key=key), headers={"User-Agent": "gymlog-exercise-image-bundle"}
    )
    last_error = None
    for _ in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                raw = response.read()
            break
        except Exception as error:  # network hiccup: try again, then report
            last_error = error
    else:
        return key, f"failed: {last_error}"
    image = Image.open(io.BytesIO(raw)).convert("RGB")
    if image.width > WIDTH:
        image = image.resize((WIDTH, round(image.height * WIDTH / image.width)), Image.LANCZOS)
    image.save(target, "WEBP", quality=QUALITY, method=6)
    return key, "written"


def write_map(keys):
    lines = [
        "/* eslint-disable */",
        "import type { ImageSourcePropType } from 'react-native';",
        "import { exerciseImageKeyFrom } from '../lib/exerciseImageKey';",
        "",
        "// GENERATED by scripts/bundle_exercise_images.py - do not edit by hand.",
        "// Regenerate with: npm run exercise:sync  (or python -P scripts/bundle_exercise_images.py)",
        "//",
        "// One bundled picture per exercise, keyed by the library's `imageKey`. Every",
        "// value is a thunk, not a require() result: a table of 873 eager require()s",
        "// would be evaluated before the first render on every cold start (Hermes has",
        "// no JIT), so a picture is only resolved when it is shown. Keep it that way;",
        "// tests/lib/exerciseImagesBundled.test.cjs fails on an eager entry.",
        "// Use getExerciseImageSource().",
        "const EXERCISE_IMAGES: Record<string, () => ImageSourcePropType> = {",
    ]
    for key in keys:
        lines.append(f"  '{key}': () => require('../../assets/exercises/{file_name(key)}'),")
    lines += [
        "};",
        "",
        "// Takes a key or a legacy stored URL (see exerciseImageKeyFrom). Null when there",
        "// is no bundled picture for it, which is also what any other URL gives.",
        "export function getExerciseImageSource(value: string | null | undefined): ImageSourcePropType | null {",
        "  const key = exerciseImageKeyFrom(value);",
        "  if (key === null || !Object.prototype.hasOwnProperty.call(EXERCISE_IMAGES, key)) {",
        "    return null;",
        "  }",
        "  return EXERCISE_IMAGES[key]();",
        "}",
        "",
    ]
    MAP_FILE.write_text("\n".join(lines), encoding="utf8", newline="\n")


def main():
    keys = library_keys()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(fetch, keys))
    failed = [(k, r) for k, r in results if r.startswith("failed")]
    written = sum(1 for _, r in results if r == "written")
    print(f"{len(keys)} keys: {written} written, {len(keys) - written - len(failed)} skipped, {len(failed)} failed")
    for key, reason in failed:
        print(f"  {key}: {reason}")
    if failed:
        sys.exit(1)
    wanted = {file_name(key) for key in keys}
    for stale in sorted(OUT_DIR.glob("*.webp")):
        if stale.name not in wanted:
            stale.unlink()
            print(f"Removed {stale.name}: no exercise uses it any more")
    clashes = unaccepted_shared_frames(keys)
    if clashes:
        for group in clashes:
            print(f"  same picture for different exercises: {', '.join(group)}")
        sys.exit(
            "Look at the pictures, then add each key to NO_PICTURE or the group to "
            "ACCEPTED_SHARED_FRAMES in scripts/exercise-pictures.json"
        )
    write_map(keys)
    print(f"Wrote {MAP_FILE}")


if __name__ == "__main__":
    main()
